# Imports

In [1]:
import sklearn
import pandas as pd
import numpy as np
import re
import plotly.graph_objects as go
import plotly.express as px
import plotly
import math

# Reading Data

In [2]:
df_17 = pd.read_csv('./Dataset/FIFA17_official_data.csv')
df_18 = pd.read_csv('./Dataset/FIFA18_official_data.csv')
df_19 = pd.read_csv('./Dataset/FIFA19_official_data.csv')
df_20 = pd.read_csv('./Dataset/FIFA20_official_data.csv')
df_21 = pd.read_csv('./Dataset/FIFA21_official_data.csv')
df_22 = pd.read_csv('./Dataset/FIFA22_official_data.csv')
datalist = [df_17,df_18,df_19,df_20,df_21,df_22]

In [3]:
df_22.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'Crossing', 'Finishing', 'HeadingAccuracy',
       'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
       'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
       'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
       'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Best Position', 'Best Overall Rating', 'Release Clause',
       'DefensiveAwareness'],
      dtype='object')

# Cleaning Data

In [4]:
curr_set = df_17
for next_set in datalist[1:]:
    print(set(next_set) - set(curr_set))
    curr_set = next_set

for dataset in datalist:
    if 'Release Clause' in list(dataset.columns):
        dataset.drop("Release Clause", axis = 1, inplace = True)
    if 'DefensiveAwareness' in list(dataset.columns):
        dataset.drop("DefensiveAwareness", axis = 1, inplace = True)
print("--------------------")
curr_set = df_17
for next_set in datalist[1:]:
    print(set(next_set) - set(curr_set))
    curr_set = next_set

{'Release Clause'}
set()
{'DefensiveAwareness'}
set()
set()
--------------------
set()
set()
set()
set()
set()

In [5]:
#Now we can join the datasets\
F_all_df = pd.concat(datalist, ignore_index=True)
F_all_df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'Crossing', 'Finishing', 'HeadingAccuracy',
       'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
       'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
       'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
       'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Best Position', 'Best Overall Rating'],
      dtype='object')

In [6]:
Unimportant_features  = ["Photo", "Flag", "Club Logo", "Wage", "Special", "International Reputation", "Work Rate", "Body Type", "Real Face", "Jersey Number", "Contract Valid Until", "Best Overall Rating","Joined","Loaned From"]
F_all_df.drop(Unimportant_features, axis = 1, inplace = True)
F_all_df["Ovr_pot"] = (F_all_df["Overall"] + F_all_df["Potential"])/2

In [7]:
# One-hot encode Preferred_foot
F_all_df = pd.get_dummies(F_all_df, columns = ["Preferred Foot"])
F_all_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right
0,176580,L. Suárez,29,Uruguay,92,92,FC Barcelona,€83M,4.0,4.0,...,38.0,27.0,25.0,31.0,33.0,37.0,ST,92.0,0,1
1,178518,R. Nainggolan,28,Belgium,86,86,Roma,€37.5M,3.0,3.0,...,88.0,11.0,11.0,14.0,8.0,11.0,CDM,86.0,0,1
2,181872,A. Vidal,29,Chile,87,87,FC Bayern München,€41.5M,4.0,3.0,...,84.0,4.0,2.0,4.0,2.0,4.0,CDM,87.0,0,1
3,197445,D. Alaba,24,Austria,86,89,FC Bayern München,€41.5M,4.0,3.0,...,83.0,5.0,7.0,14.0,15.0,9.0,LB,87.5,1,0
4,195864,P. Pogba,23,France,88,94,Manchester United,€71.5M,4.0,5.0,...,73.0,5.0,6.0,2.0,4.0,3.0,CAM,91.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104347,240558,18 L. Clayton,17,England,53,70,Cheltenham Town,€100K,2.0,1.0,...,12.0,55.0,54.0,52.0,50.0,59.0,GK,61.5,0,1
104348,262846,�. Dobre,20,Romania,53,63,FC Academica Clinceni,€180K,2.0,1.0,...,12.0,57.0,52.0,53.0,48.0,58.0,GK,58.0,0,1
104349,241317,21 Xue Qinghao,19,China PR,47,60,Shanghai Shenhua FC,€100K,2.0,1.0,...,9.0,49.0,48.0,45.0,38.0,52.0,GK,53.5,0,1
104350,259646,A. Shaikh,18,India,47,67,ATK Mohun Bagan FC,€110K,3.0,1.0,...,13.0,49.0,41.0,39.0,45.0,49.0,GK,57.0,0,1
104351,178453,07 A. Censori,17,Italy,28,38,Arezzo,€0,2.0,1.0,...,NaN,7.0,1.0,36.0,6.0,9.0,ST,33.0,0,1

In [8]:
detailed_features = ['Age','Overall', 'Potential', 'Weak Foot', 'Skill Moves', 'Height', 'Weight', 'Crossing', 'Finishing',
       'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve',
       'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', "Ovr_pot", 'Preferred Foot_Left', 'Preferred Foot_Right']

In [9]:
F_all_df[detailed_features] = F_all_df[detailed_features].fillna(0)
F_all_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right
0,176580,L. Suárez,29,Uruguay,92,92,FC Barcelona,€83M,4.0,4.0,...,38.0,27.0,25.0,31.0,33.0,37.0,ST,92.0,0,1
1,178518,R. Nainggolan,28,Belgium,86,86,Roma,€37.5M,3.0,3.0,...,88.0,11.0,11.0,14.0,8.0,11.0,CDM,86.0,0,1
2,181872,A. Vidal,29,Chile,87,87,FC Bayern München,€41.5M,4.0,3.0,...,84.0,4.0,2.0,4.0,2.0,4.0,CDM,87.0,0,1
3,197445,D. Alaba,24,Austria,86,89,FC Bayern München,€41.5M,4.0,3.0,...,83.0,5.0,7.0,14.0,15.0,9.0,LB,87.5,1,0
4,195864,P. Pogba,23,France,88,94,Manchester United,€71.5M,4.0,5.0,...,73.0,5.0,6.0,2.0,4.0,3.0,CAM,91.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104347,240558,18 L. Clayton,17,England,53,70,Cheltenham Town,€100K,2.0,1.0,...,12.0,55.0,54.0,52.0,50.0,59.0,GK,61.5,0,1
104348,262846,�. Dobre,20,Romania,53,63,FC Academica Clinceni,€180K,2.0,1.0,...,12.0,57.0,52.0,53.0,48.0,58.0,GK,58.0,0,1
104349,241317,21 Xue Qinghao,19,China PR,47,60,Shanghai Shenhua FC,€100K,2.0,1.0,...,9.0,49.0,48.0,45.0,38.0,52.0,GK,53.5,0,1
104350,259646,A. Shaikh,18,India,47,67,ATK Mohun Bagan FC,€110K,3.0,1.0,...,13.0,49.0,41.0,39.0,45.0,49.0,GK,57.0,0,1
104351,178453,07 A. Censori,17,Italy,28,38,Arezzo,€0,2.0,1.0,...,0.0,7.0,1.0,36.0,6.0,9.0,ST,33.0,0,1

In [10]:
# Clean height column
feet_inches_re = re.compile(r"(\d)'(\d+)")

# Define a function to convert feet'inches to cm
def feet_inches_to_cm(s):
    match = feet_inches_re.match(s)
    if match:
        feet = int(match.group(1))
        inches = int(match.group(2))
        return round((feet*12 + inches) * 2.54, 2)
    else:
        return float(s.replace('cm', ''))
F_all_df['Height'] = pd.to_numeric(F_all_df['Height'].apply(feet_inches_to_cm))

In [11]:
F_all_df['Height'].value_counts()

182.88    13593
177.80    12221
175.26    10661
180.34    10380
187.96     9448
          ...
159.00        3
156.00        2
155.00        1
157.00        1
206.00        1
Name: Height, Length: 71, dtype: int64

In [12]:
# Clean Weight Column
def convert_weight(weight_str):
    if 'kg' in weight_str:
        # If weight is in kg, remove the 'kg' suffix and return as float
        return float(weight_str.replace('kg', ''))
    elif 'lbs' in weight_str:
        # If weight is in lbs, convert to kg and return as float
        return float(weight_str.replace('lbs', '')) * 0.453592
    else:
        print("oops")
        # Return NaN if weight format is not recognized
        return pd.np.nan

# Apply the function to the Weight column and create a new column 'Weight_kg'
F_all_df['Weight'] = F_all_df['Weight'].apply(convert_weight)

In [13]:
F_all_df['Weight'].value_counts()

69.853168     7042
74.842680     6815
79.832192     4958
72.121128     4800
78.017824     4717
              ...
104.000000       1
51.000000        1
53.000000        1
48.080752        1
105.000000       1
Name: Weight, Length: 117, dtype: int64

In [14]:
# Define a function to convert cost to millions
def convert_cost(cost_str):
    if 'M' in cost_str:
        # If cost is in millions, remove the '$' and 'M' suffix and return as float
        return float(cost_str.replace('€', '').replace('M', ''))
    elif 'K' in cost_str:
        # If cost is in thousands, remove the '$' and 'K' suffix, divide by 1000, and return as float
        return float(cost_str.replace('€', '').replace('K', '')) / 1000
    # else:
    #     # Return NaN if cost format is not recognized
    #     return pd.np.nan

# Apply the function to the Cost column and create a new column 'Cost_millions'
F_all_df['Value'] = F_all_df['Value'].apply(convert_cost)

# Feature Creation - BMI

In [15]:
F_all_df['Bmi'] = F_all_df['Weight'] / (F_all_df['Height']/100)**2

In [16]:
F_all_df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Weak Foot', 'Skill Moves', 'Position', 'Height', 'Weight',
       'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys',
       'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance',
       'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Best Position', 'Ovr_pot', 'Preferred Foot_Left',
       'Preferred Foot_Right', 'Bmi'],
      dtype='object')

# EDA

In [17]:
# fig = go.Figure()

# fig = go.Figure(data=go.Scatter(
#     x = df_20['Overall'],
#     y = df_20['Value'],
#     mode='markers',
#     marker=dict(
#         size=16,
#         color=df_20['Age'], #set color equal to a variable
#         colorscale='Plasma', # one of plotly colorscales
#         showscale=True
#     ),
#     text= df_20['Name'],
# ))

# fig.update_layout(title='Styled Scatter Plot (colored by Age) year 2020 - Overall Rating vs Value in Euros',
#                   xaxis_title='Overall Rating',
#                   yaxis_title='Value in Euros',
#                   paper_bgcolor='rgba(0,0,0,0)',
#                   plot_bgcolor='rgba(0,0,0,0)',
#                   font=dict(family='Cambria, monospace', size=12, color='#000000'))
# fig.show()

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = sklearn.preprocessing.StandardScaler()
F_norm_df = F_all_df.copy(deep = True)
F_norm_df[detailed_features] = scaler.fit_transform(F_norm_df[detailed_features].to_numpy())
F_norm_df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Weak Foot', 'Skill Moves', 'Position', 'Height', 'Weight',
       'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys',
       'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance',
       'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Best Position', 'Ovr_pot', 'Preferred Foot_Left',
       'Preferred Foot_Right', 'Bmi'],
      dtype='object')

In [19]:
df_17 = F_all_df.iloc[:df_17.shape[0]]
df_17

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,176580,L. Suárez,29,Uruguay,92,92,FC Barcelona,83.00,4.0,4.0,...,27.0,25.0,31.0,33.0,37.0,ST,92.0,0,1,25.768347
1,178518,R. Nainggolan,28,Belgium,86,86,Roma,37.50,3.0,3.0,...,11.0,11.0,14.0,8.0,11.0,CDM,86.0,0,1,21.117175
2,181872,A. Vidal,29,Chile,87,87,FC Bayern München,41.50,4.0,3.0,...,4.0,2.0,4.0,2.0,4.0,CDM,87.0,0,1,23.012574
3,197445,D. Alaba,24,Austria,86,89,FC Bayern München,41.50,4.0,3.0,...,5.0,7.0,14.0,15.0,9.0,LB,87.5,1,0,23.430985
4,195864,P. Pogba,23,France,88,94,Manchester United,71.50,4.0,5.0,...,5.0,6.0,2.0,4.0,3.0,CAM,91.0,0,1,23.123158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17555,233215,C. Addai,18,Ghana,54,72,Coventry City,0.13,2.0,1.0,...,51.0,51.0,48.0,59.0,60.0,GK,63.0,0,1,19.353873
17556,232911,R. Kamiyama,31,Japan,57,57,Avispa Fukuoka,0.09,3.0,1.0,...,59.0,46.0,41.0,62.0,59.0,GK,57.0,0,1,26.576933
17557,235387,B. Gaye,18,Germany,53,67,DSC Arminia Bielefeld,0.10,3.0,1.0,...,54.0,50.0,49.0,54.0,58.0,GK,60.0,0,1,23.370715
17558,237904,K. Olifirenko,18,Russia,50,66,FC Tom Tomsk,0.06,3.0,1.0,...,47.0,59.0,52.0,44.0,49.0,GK,58.0,0,1,21.498288
17559,237463,A. Kelsey,16,England,46,63,Scunthorpe United,0.06,2.0,1.0,...,46.0,47.0,54.0,43.0,48.0,GK,54.5,0,1,20.927730

In [20]:
df_18 = F_all_df.iloc[df_17.shape[0]:df_18.shape[0] + df_17.shape[0]]
df_18

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
17560,176580,L. Suárez,30,Uruguay,92,92,FC Barcelona,97.00,4.0,4.0,...,27.0,25.0,31.0,33.0,37.0,CF,92.0,0,1,25.768347
17561,178518,R. Nainggolan,29,Belgium,86,86,Roma,42.50,3.0,3.0,...,11.0,11.0,14.0,8.0,11.0,CDM,86.0,0,1,25.104333
17562,203551,A. Florenzi,26,Italy,82,83,Roma,21.00,3.0,3.0,...,9.0,8.0,10.0,11.0,10.0,CF,82.5,0,1,22.503074
17563,197445,D. Alaba,25,Austria,85,87,FC Bayern München,38.50,4.0,3.0,...,5.0,7.0,14.0,15.0,9.0,LB,86.0,1,0,23.430985
17564,195864,P. Pogba,24,France,88,92,Manchester United,76.00,4.0,5.0,...,5.0,6.0,2.0,4.0,3.0,CM,90.0,0,1,23.123158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35482,240757,A. Viscovo,18,Italy,51,70,Crotone,0.06,2.0,1.0,...,58.0,46.0,57.0,52.0,47.0,GK,60.5,0,1,21.748268
35483,237463,A. Kelsey,17,England,46,63,Scunthorpe United,0.05,2.0,1.0,...,46.0,47.0,49.0,42.0,48.0,GK,54.5,0,1,20.927730
35484,240790,A. Giacomel,18,Italy,49,64,Empoli,0.05,2.0,1.0,...,45.0,55.0,48.0,45.0,56.0,GK,56.5,0,1,23.869627
35485,241206,D. Maekawa,22,Japan,54,61,Vissel Kobe,0.07,3.0,1.0,...,55.0,51.0,44.0,55.0,59.0,GK,57.5,0,1,23.748109
35486,243202,A. Jones,16,England,48,66,Milton Keynes Dons,0.05,2.0,1.0,...,56.0,43.0,42.0,39.0,52.0,GK,57.0,0,1,21.241154

In [21]:
df_19 = F_all_df.iloc[df_17.shape[0] + df_18.shape[0]:df_18.shape[0] + df_17.shape[0] + df_19.shape[0]]
df_19

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
35487,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,80.000,4.0,3.0,...,27.0,25.0,31.0,33.0,37.0,ST,91.0,0,1,25.768347
35488,194765,A. Griezmann,27,France,89,89,Atlético Madrid,71.000,3.0,4.0,...,14.0,8.0,14.0,13.0,14.0,LW,89.0,1,0,23.775280
35489,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67.000,4.0,4.0,...,13.0,9.0,7.0,14.0,9.0,CM,91.0,0,1,22.198978
35490,224334,M. Acuña,26,Argentina,81,81,Sporting CP,19.000,3.0,4.0,...,8.0,14.0,13.0,13.0,14.0,LM,81.0,1,0,23.111265
35491,192985,K. De Bruyne,27,Belgium,91,91,Manchester City,93.000,5.0,4.0,...,15.0,13.0,5.0,10.0,13.0,CAM,91.0,0,1,21.478402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53425,233940,M. Brzozowski,19,Poland,49,60,Queens Park Rangers,0.040,3.0,1.0,...,52.0,52.0,52.0,44.0,51.0,GK,54.5,0,1,19.873417
53426,245370,E. Destanoglu,17,Turkey,50,68,Beşiktaş JK,0.050,1.0,1.0,...,52.0,52.0,50.0,47.0,52.0,GK,59.0,0,1,23.004788
53427,233215,C. Addai,20,Ghana,51,61,Coventry City,0.045,2.0,1.0,...,51.0,48.0,40.0,54.0,56.0,GK,56.0,0,1,20.084208
53428,246648,O. Battersby,16,England,50,70,Grimsby Town,0.050,2.0,1.0,...,47.0,51.0,50.0,52.0,53.0,GK,60.0,0,1,20.998328
53429,248182,H. Sveijer,16,Sweden,48,63,IK Sirius,0.050,2.0,1.0,...,50.0,49.0,48.0,47.0,51.0,GK,55.5,0,1,20.713424

In [22]:
df_20 = F_all_df.iloc[df_17.shape[0] + df_18.shape[0] + df_19.shape[0]:df_18.shape[0] + df_17.shape[0] + df_19.shape[0] + df_20.shape[0]]
df_20

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
53430,176580,L. Suárez,32,Uruguay,89,89,FC Barcelona,53.000,4.0,3.0,...,27.0,25.0,31.0,33.0,37.0,ST,89.0,0,1,25.768347
53431,194765,A. Griezmann,28,France,89,89,FC Barcelona,69.000,3.0,4.0,...,14.0,8.0,14.0,13.0,14.0,CF,89.0,1,0,23.775280
53432,212198,Bruno Fernandes,24,Portugal,86,89,Manchester United,56.500,4.0,4.0,...,12.0,14.0,15.0,8.0,14.0,CAM,87.5,0,1,21.809488
53433,192985,K. De Bruyne,28,Belgium,91,91,Manchester City,90.000,5.0,4.0,...,15.0,13.0,5.0,10.0,13.0,CAM,91.0,0,1,21.478402
53434,224334,M. Acuña,27,Argentina,82,82,Sporting CP,20.000,3.0,4.0,...,8.0,14.0,13.0,13.0,14.0,LB,82.0,1,0,23.111265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70529,251433,B. Voll,18,Germany,51,63,FC Hansa Rostock,0.050,2.0,1.0,...,52.0,55.0,52.0,42.0,57.0,GK,57.0,0,1,22.174718
70530,239426,18 N. Krucker,18,Switzerland,50,61,FC St. Gallen,0.035,3.0,1.0,...,53.0,51.0,55.0,49.0,51.0,GK,55.5,0,1,23.869627
70531,240757,18 A. Viscovo,18,Italy,51,70,Crotone,0.060,2.0,1.0,...,58.0,46.0,57.0,52.0,47.0,GK,60.5,0,1,21.748268
70532,248182,H. Sveijer,17,Sweden,48,63,IK Sirius,0.050,2.0,1.0,...,50.0,49.0,48.0,47.0,51.0,GK,55.5,0,1,22.164682
70533,178453,07 A. Censori,17,Italy,28,38,Arezzo,NaN,2.0,1.0,...,7.0,1.0,36.0,6.0,9.0,ST,33.0,0,1,21.809488

In [23]:
df_21 = F_all_df.iloc[df_17.shape[0] + df_18.shape[0] + df_19.shape[0] + df_20.shape[0]:df_18.shape[0] + df_17.shape[0] + df_19.shape[0] + df_20.shape[0] + df_21.shape[0]]
df_21

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
70534,176580,L. Suárez,33,Uruguay,87,87,Atlético Madrid,31.50,4.0,3.0,...,27.0,25.0,31.0,33.0,37.0,ST,87.0,0,1,25.768347
70535,192985,K. De Bruyne,29,Belgium,91,91,Manchester City,87.00,5.0,4.0,...,15.0,13.0,5.0,10.0,13.0,CAM,91.0,0,1,21.478402
70536,212198,Bruno Fernandes,25,Portugal,87,90,Manchester United,63.00,4.0,4.0,...,12.0,14.0,15.0,8.0,14.0,CAM,88.5,0,1,21.809488
70537,194765,A. Griezmann,29,France,87,87,FC Barcelona,50.50,3.0,4.0,...,14.0,8.0,14.0,13.0,14.0,ST,87.0,1,0,23.775280
70538,224334,M. Acuña,28,Argentina,83,83,Sevilla FC,22.00,3.0,4.0,...,8.0,14.0,13.0,13.0,14.0,LB,83.0,1,0,23.111265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87637,247866,19 C. Miszta,16,Poland,50,70,Legia Warszawa,0.05,3.0,1.0,...,48.0,51.0,56.0,40.0,56.0,GK,60.0,0,1,21.423155
87638,251433,B. Voll,19,Germany,51,63,FC Hansa Rostock,0.05,2.0,1.0,...,52.0,55.0,52.0,42.0,57.0,GK,57.0,0,1,22.174718
87639,252420,T. Parker,18,Northern Ireland,51,70,Luton Town,0.06,3.0,1.0,...,50.0,49.0,50.0,53.0,55.0,GK,60.5,0,1,21.998248
87640,248182,H. Sveijer,18,Sweden,49,63,IK Sirius,0.05,2.0,1.0,...,50.0,51.0,49.0,50.0,51.0,GK,56.0,0,1,22.164682
87641,245862,19 J. Milli,18,Italy,47,65,Lecce,0.05,3.0,1.0,...,52.0,52.0,52.0,40.0,44.0,GK,56.0,0,1,23.327135

In [24]:
df_22 = F_all_df.tail(df_22.shape[0])

In [25]:
df_22

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
87642,212198,Bruno Fernandes,26,Portugal,88,89,Manchester United,107.50,3.0,4.0,...,12.0,14.0,15.0,8.0,14.0,CAM,88.5,0,1,21.534908
87643,209658,L. Goretzka,26,Germany,87,88,FC Bayern München,93.00,4.0,3.0,...,13.0,8.0,15.0,11.0,9.0,CM,87.5,0,1,22.955684
87644,176580,L. Suárez,34,Uruguay,88,88,Atlético de Madrid,44.50,4.0,3.0,...,27.0,25.0,31.0,33.0,37.0,ST,88.0,0,1,25.057360
87645,192985,K. De Bruyne,30,Belgium,91,91,Manchester City,125.50,5.0,4.0,...,15.0,13.0,5.0,10.0,13.0,CM,91.0,0,1,21.366869
87646,224334,M. Acuña,29,Argentina,84,84,Sevilla FC,37.00,3.0,4.0,...,8.0,14.0,13.0,13.0,14.0,LB,84.0,1,0,23.323418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104347,240558,18 L. Clayton,17,England,53,70,Cheltenham Town,0.10,2.0,1.0,...,55.0,54.0,52.0,50.0,59.0,GK,61.5,0,1,22.634676
104348,262846,�. Dobre,20,Romania,53,63,FC Academica Clinceni,0.18,2.0,1.0,...,57.0,52.0,53.0,48.0,58.0,GK,58.0,0,1,22.850462
104349,241317,21 Xue Qinghao,19,China PR,47,60,Shanghai Shenhua FC,0.10,2.0,1.0,...,49.0,48.0,45.0,38.0,52.0,GK,53.5,0,1,21.913580
104350,259646,A. Shaikh,18,India,47,67,ATK Mohun Bagan FC,0.11,3.0,1.0,...,49.0,41.0,39.0,45.0,49.0,GK,57.0,0,1,21.389756
104351,178453,07 A. Censori,17,Italy,28,38,Arezzo,NaN,2.0,1.0,...,7.0,1.0,36.0,6.0,9.0,ST,33.0,0,1,22.024323

In [26]:
# fig = go.Figure()
# sample = F_norm_df.sort_values(by='Ovr_pot')

# fig.add_trace(go.Box(
#     x = sample['Ovr_pot'],
#     y = sample['Bmi'],
#     name="Suspected Outliers",
#     boxpoints='suspectedoutliers', # only suspected outliers
#     marker=dict(
#         size=12,
#         color='rgb(251, 158, 58)',
#         outliercolor='rgba(216, 87, 107, 0.6)',
#         line=dict(
#             outliercolor='rgba(216, 87, 107, 0.6)',
#             outlierwidth=2)),
#     line_color='rgb(73, 3, 159)',
#     text= sample['Name']
# ))

# fig.update_layout(title='Styled Box Plot (with Suspected Outliers) - Overall Rating vs BMI',
#                   xaxis_title='Overall Rating',
#                   yaxis_title='BMI',
#                   paper_bgcolor='rgba(0,0,0,0)',
#                   plot_bgcolor='rgba(0,0,0,0)',
#                   font=dict(family='Cambria, monospace', size=12, color='#000000'),
#                   xaxis_rangeslider_visible=True)
# fig.show()

In [27]:
F_norm_df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Weak Foot', 'Skill Moves', 'Position', 'Height', 'Weight',
       'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys',
       'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance',
       'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Best Position', 'Ovr_pot', 'Preferred Foot_Left',
       'Preferred Foot_Right', 'Bmi'],
      dtype='object')

In [28]:
F_norm_df["Best Position"].value_counts()

CB     20687
ST     15332
CAM    12517
GK     10890
RM      8359
CDM     7824
CM      6018
RB      5116
LB      4840
LM      4711
RW      2656
RWB     1861
LWB     1779
LW      1279
CF       480
LF         2
SW         1
Name: Best Position, dtype: int64

# Strikers

In [29]:
striker_df = F_norm_df[(F_norm_df["Best Position"] == "ST") | (F_norm_df["Best Position"] == "CF") | (F_norm_df["Best Position"] == "LF")]
striker_df  =  striker_df.reset_index(drop = True)
striker_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,176580,L. Suárez,0.873366,Uruguay,3.647373,3.353318,FC Barcelona,83.00,1.552616,2.090192,...,0.618657,0.538418,0.922738,1.007493,1.168766,ST,3.876224,-0.558918,0.558918,25.768347
1,173731,G. Bale,0.249592,Wales,3.360388,3.020577,Real Madrid,72.00,0.053943,2.090192,...,-0.071239,-0.062607,-0.302515,-0.658054,-0.584877,ST,3.536013,1.789172,-1.789172,22.106529
2,20801,Cristiano Ronaldo,1.289216,Portugal,3.934357,3.686059,Real Madrid,87.00,1.552616,3.387573,...,-0.531171,-0.303018,-0.057464,-0.122700,-0.302032,ST,4.216436,-0.558918,0.558918,23.220144
3,184941,A. Sánchez,0.457517,Chile,3.073404,2.687836,Arsenal,55.00,0.053943,2.090192,...,-0.358697,-0.363120,-0.057464,-0.241667,-0.188893,ST,3.195802,-0.558918,0.558918,21.456996
4,54050,W. Rooney,1.081291,England,2.212450,1.689612,Manchester United,18.50,1.552616,0.792811,...,-0.358697,-0.303018,-0.179990,-0.479603,-0.528308,ST,2.175168,-0.558918,0.558918,27.024076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15809,262034,R. Mahon,-1.413805,Republic of Ireland,-2.666287,-1.970541,Bohemian FC,0.11,0.053943,-0.504570,...,-0.531171,-0.122710,-0.608828,-0.479603,-0.075755,ST,-2.587790,1.789172,-1.789172,20.549887
15810,259650,F. Molla,-1.205880,India,-2.809779,-0.805947,ATK Mohun Bagan FC,0.13,-1.444731,-0.504570,...,-0.473679,-0.603530,-0.118727,-0.301151,-0.132324,ST,-2.077473,-0.558918,0.558918,24.304618
15811,161659,07 Danilo,-0.166257,Brazil,-0.370411,-0.805947,Gallos Blancos de Querétaro,NaN,0.053943,-1.801951,...,-0.301205,-0.603530,2.515567,-0.063216,-0.245462,ST,-0.631575,1.789172,-1.789172,24.930748
15812,150597,09 J. Moukoko,-0.374181,Congo DR,-1.805333,-1.637800,NaN,NaN,0.053943,-1.801951,...,-0.473679,0.538418,1.474102,0.531623,0.489936,ST,-1.907368,-0.558918,0.558918,23.503556
15813,178453,07 A. Censori,-1.621729,Italy,-5.536132,-5.630694,Arezzo,NaN,-1.444731,-1.801951,...,-0.531171,-0.904043,1.229051,-0.598570,-0.415170,ST,-6.160009,-0.558918,0.558918,22.024323

In [30]:
ST_detailed_features = ['Weak Foot', 'Skill Moves', 'Height', 'Weight','Bmi', 'Crossing', 'Finishing',
       'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve',
       'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle']

In [31]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
X = striker_df[ST_detailed_features].to_numpy()
y = striker_df["Ovr_pot"].to_numpy()
# define feature selection
fs = SelectKBest(score_func=f_regression, k = 10)
# apply feature selection
X_selected = fs.fit_transform(X, y)

In [32]:
ST_essential_ft = list(fs.get_feature_names_out(ST_detailed_features))
ST_essential_ft

['Finishing',
 'HeadingAccuracy',
 'ShortPassing',
 'Volleys',
 'Dribbling',
 'BallControl',
 'Reactions',
 'ShotPower',
 'LongShots',
 'Positioning']

# Wingers

In [33]:
wingers_df = F_norm_df[(F_norm_df["Best Position"] == "LW") | (F_norm_df["Best Position"] == "RW")]
wingers_df  =  wingers_df.reset_index(drop = True)
wingers_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,190871,Neymar,-0.166257,Brazil,3.647373,3.686059,FC Barcelona,106.00,3.051289,3.387573,...,-0.416188,-0.423223,-0.057464,-0.063216,-0.302032,LW,4.046330,-0.558918,0.558918,22.150882
1,193130,A. Schürrle,0.041668,Germany,2.068958,1.689612,Borussia Dortmund,19.00,1.552616,0.792811,...,-0.531171,-0.303018,-0.241252,-0.420119,-0.245462,RW,2.090115,-0.558918,0.558918,22.106529
2,209331,M. Salah,-0.166257,Egypt,2.212450,2.188724,Roma,26.00,-1.444731,2.090192,...,-0.128731,-0.122710,-0.425040,-0.301151,-0.132324,RW,2.430326,1.789172,-1.789172,23.479935
3,222492,L. Sané,-0.997955,Germany,2.212450,3.186947,Manchester City,31.00,0.053943,0.792811,...,-0.473679,-0.242915,-0.425040,-0.420119,-0.132324,LW,2.940643,1.789172,-1.789172,22.784644
4,185020,José Callejón,0.873366,Spain,2.355942,1.855983,Napoli,22.50,-1.444731,0.792811,...,-0.473679,-0.663633,-0.118727,-0.301151,-0.302032,RW,2.345273,-0.558918,0.558918,23.100839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3930,248281,20 D. Borrero,-1.621729,Colombia,-1.518349,0.525018,Club Independiente Santa Fe,0.18,0.053943,0.792811,...,-0.243714,-0.423223,-0.425040,-0.658054,-0.188893,RW,-0.631575,-0.558918,0.558918,21.847009
3931,263090,J. Eng,-1.829654,Norway,-1.948825,0.691388,Vålerenga Fotball,0.30,0.053943,0.792811,...,-0.358697,-0.363120,-0.547565,-0.360635,-0.641446,RW,-0.801681,-0.558918,0.558918,24.074074
3932,264675,J. Dickman,-0.997955,Sweden,-2.092318,-0.805947,FC Nordsjælland,0.19,0.053943,-0.504570,...,-0.128731,-0.062607,-0.241252,-0.539087,-0.584877,RW,-1.652209,-0.558918,0.558918,22.582709
3933,261677,R. O'Kane,-1.621729,Republic of Ireland,-2.235810,0.525018,Dundalk FC,0.18,-1.444731,-0.504570,...,-0.301205,-0.242915,-0.118727,-0.360635,-0.584877,RW,-1.056840,-0.558918,0.558918,20.904195
3934,256458,K. Swaleh,-1.413805,Norway,-2.379302,-0.306835,FK Bodø/Glimt,0.13,0.053943,-0.504570,...,-0.301205,-0.122710,-0.179990,-0.598570,-0.471739,RW,-1.567157,-0.558918,0.558918,20.761246

In [34]:
Wing_detailed_features = ['Weak Foot', 'Skill Moves', 'Height', 'Weight','Bmi', 'Crossing', 'Finishing',
       'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve',
       'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle']

In [35]:
X = wingers_df[Wing_detailed_features].to_numpy()
y = wingers_df["Ovr_pot"].to_numpy()
# define feature selection
fs = SelectKBest(score_func=f_regression, k = 10)
# apply feature selection
X_selected = fs.fit_transform(X, y)

In [36]:
Wing_essential_ft = list(fs.get_feature_names_out(Wing_detailed_features))
Wing_essential_ft

['Crossing',
 'Finishing',
 'ShortPassing',
 'Dribbling',
 'BallControl',
 'Reactions',
 'ShotPower',
 'LongShots',
 'Positioning',
 'Vision']

# Midfield

In [37]:
mids_df = F_norm_df[(F_norm_df["Best Position"] == "RM") | (F_norm_df["Best Position"] == "CM") | (F_norm_df["Best Position"] == "CDM") | (F_norm_df["Best Position"] == "LM")]
mids_df  =  mids_df.reset_index(drop = True)
mids_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,178518,R. Nainggolan,0.665442,Belgium,2.786419,2.355094,Roma,37.50,0.053943,0.792811,...,-0.301205,-0.303018,-0.118727,-0.479603,-0.302032,CDM,2.855590,-0.558918,0.558918,21.117175
1,181872,A. Vidal,0.873366,Chile,2.929911,2.521465,FC Bayern München,41.50,1.552616,0.792811,...,-0.703645,-0.843941,-0.731353,-0.836506,-0.698015,CDM,3.025696,-0.558918,0.558918,23.012574
2,177003,L. Modrić,1.081291,Croatia,3.216896,2.854206,Real Madrid,54.00,1.552616,2.090192,...,-0.186222,-0.423223,-0.547565,-0.122700,-0.415170,CM,3.365907,-0.558918,0.558918,21.117175
3,173210,C. Marchisio,1.081291,Italy,2.786419,2.355094,Juventus,35.00,1.552616,2.090192,...,-0.703645,-0.783838,-0.731353,-0.836506,-0.698015,CM,2.855590,-0.558918,0.558918,22.454694
4,139997,D. Srna,1.912989,Croatia,2.068958,1.523241,Shakhtar Donetsk,4.80,0.053943,0.792811,...,-0.358697,-0.363120,-0.608828,-0.598570,-0.245462,CM,2.005062,-0.558918,0.558918,22.813872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26907,4174,07 P. Sarr,0.665442,Senegal,-0.226918,-0.306835,Stade Brestois 29,NaN,0.053943,-1.801951,...,-0.416188,-0.242915,3.189456,-0.479603,-0.302032,CDM,-0.291364,-0.558918,0.558918,23.456790
26908,246839,21 C. Bargary,-1.205880,Republic of Ireland,-2.235810,-0.805947,Cork City,0.15,0.053943,-0.504570,...,-0.358697,-0.603530,-0.302515,-0.598570,-0.641446,RM,-1.737262,-0.558918,0.558918,21.777553
26909,235352,18 T. Käßemodel,0.665442,Germany,-2.953271,-4.299729,FC Erzgebirge Aue,0.03,0.053943,-0.504570,...,-0.358697,-0.242915,-0.608828,-0.182184,-0.584877,CM,-3.948636,-0.558918,0.558918,25.059307
26910,4373,07 S. Valakari,1.705065,Finland,-0.083426,-0.805947,FC Dallas,NaN,0.053943,-1.801951,...,-0.588662,-0.783838,2.270516,-0.598570,-0.754585,CDM,-0.461470,1.789172,-1.789172,26.753864
26911,19334,10 I. Baraclough,2.744688,England,-3.240256,-1.138688,NaN,NaN,0.053943,-1.801951,...,-0.646154,0.237905,1.841678,0.234203,0.207091,CM,-2.502738,1.789172,-1.789172,23.666910

In [38]:
Mid_detailed_features = ['Weak Foot', 'Skill Moves', 'Height', 'Weight','Bmi', 'Crossing', 'Finishing',
       'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve',
       'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle']

In [39]:
X = mids_df[Mid_detailed_features].to_numpy()
y = mids_df["Ovr_pot"].to_numpy()
# define feature selection
fs = SelectKBest(score_func=f_regression, k = 10)
# apply feature selection
X_selected = fs.fit_transform(X, y)

In [40]:
Mid_essential_ft = list(fs.get_feature_names_out(Mid_detailed_features))
Mid_essential_ft

['ShortPassing',
 'Dribbling',
 'LongPassing',
 'BallControl',
 'Reactions',
 'ShotPower',
 'LongShots',
 'Positioning',
 'Vision',
 'Composure']

# CAM

In [41]:
cam_df = F_norm_df[(F_norm_df["Best Position"] == "CAM")]
cam_df  =  cam_df.reset_index(drop = True)
cam_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,195864,P. Pogba,-0.374181,France,3.073404,3.686059,Manchester United,71.50,1.552616,3.387573,...,-0.646154,-0.603530,-0.853879,-0.717538,-0.754585,CAM,3.706119,-0.558918,0.558918,23.123158
1,20289,Y. Touré,1.705065,Ivory Coast,2.499435,2.022353,Manchester City,18.00,1.552616,0.792811,...,-0.186222,-0.122710,-0.608828,-0.241667,-0.471739,CAM,2.515379,-0.558918,0.558918,25.421414
2,189509,Thiago,0.041668,Spain,2.786419,2.687836,FC Bayern München,46.00,0.053943,3.387573,...,-0.588662,-0.303018,-0.547565,-0.420119,-0.188893,CAM,3.025696,-0.558918,0.558918,22.741573
3,171877,M. Hamšik,0.665442,Slovakia,2.786419,2.355094,Napoli,37.50,1.552616,0.792811,...,-0.473679,-0.603530,-0.731353,-0.122700,-0.132324,CAM,2.855590,-0.558918,0.558918,23.598381
4,180206,M. Pjanić,0.249592,Bosnia Herzegovina,2.642927,2.355094,Juventus,37.50,1.552616,2.090192,...,-0.531171,-0.543428,-0.179990,-0.539087,-0.471739,CAM,2.770538,-0.558918,0.558918,21.478402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12512,252881,21 H. Hopper,-1.205880,England,-2.379302,-0.805947,Rochdale,0.12,-1.444731,-0.504570,...,-0.473679,-0.543428,-0.670091,-0.479603,-0.358601,CAM,-1.822315,-0.558918,0.558918,21.877551
12513,243725,D. Collins,-0.997955,Republic of Ireland,-2.809779,-2.636023,Sligo Rovers,0.10,0.053943,-0.504570,...,-0.588662,-0.423223,-0.670091,-0.182184,-0.471739,CAM,-3.013055,-0.558918,0.558918,22.460034
12514,259857,A. Majok,-0.997955,South Sudan,-2.379302,-0.805947,Western United FC,0.12,-1.444731,-0.504570,...,-0.473679,-0.303018,-0.363777,-0.479603,-0.358601,CAM,-1.822315,-0.558918,0.558918,21.132713
12515,261748,C. McLaughlin,-1.205880,Republic of Ireland,-2.235810,-2.136912,Derry City,0.13,0.053943,0.792811,...,-0.243714,-0.423223,-0.302515,-0.122700,-0.528308,CAM,-2.417685,1.789172,-1.789172,22.857143
12516,261818,R. Gallagher,-0.997955,Republic of Ireland,-2.809779,-1.804170,Finn Harps,0.11,0.053943,-0.504570,...,-0.128731,-0.363120,-0.547565,-0.182184,-0.471739,CAM,-2.587790,-0.558918,0.558918,22.839506

In [42]:
Cam_detailed_features = ['Weak Foot', 'Skill Moves', 'Height', 'Weight','Bmi', 'Crossing', 'Finishing',
       'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve',
       'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle']

In [43]:
X = cam_df[Cam_detailed_features].to_numpy()
y = cam_df["Ovr_pot"].to_numpy()
# define feature selection
fs = SelectKBest(score_func=f_regression, k = 10)
# apply feature selection
X_selected = fs.fit_transform(X, y)

In [44]:
Cam_essential_ft = list(fs.get_feature_names_out(Cam_detailed_features))
Cam_essential_ft

['Crossing',
 'Finishing',
 'ShortPassing',
 'Dribbling',
 'Curve',
 'BallControl',
 'Reactions',
 'LongShots',
 'Positioning',
 'Vision']

# Defenders

In [45]:
centrebacks_df = F_norm_df[(F_norm_df["Best Position"] == "CB")]
centrebacks_df  = centrebacks_df.reset_index(drop = True)
centrebacks_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,185103,A. Kolarov,1.081291,Serbia,1.925466,1.356871,Manchester City,10.00,0.053943,-0.504570,...,-0.013748,-0.062607,-0.486303,-0.003732,-0.584877,CB,1.834957,1.789172,-1.789172,23.495549
1,155862,Sergio Ramos,1.081291,Spain,3.216896,2.854206,Real Madrid,43.50,0.053943,0.792811,...,-0.301205,-0.483325,-0.425040,-0.539087,-0.302032,CB,3.365907,-0.558918,0.558918,22.377775
2,164240,Thiago Silva,1.289216,Brazil,3.216896,2.854206,Paris Saint-Germain,39.50,0.053943,0.792811,...,-0.416188,-0.242915,-0.670091,-0.420119,-0.358601,CB,3.365907,-0.558918,0.558918,23.598381
3,179944,David Luiz,0.873366,Brazil,2.499435,2.022353,Chelsea,22.00,0.053943,0.792811,...,-0.301205,-0.242915,-0.363777,-0.539087,-0.132324,CB,2.515379,-0.558918,0.558918,23.752331
4,205600,S. Umtiti,-0.582106,France,2.355942,2.687836,FC Barcelona,27.00,0.053943,-0.504570,...,-0.071239,-0.363120,-0.118727,-0.241667,-0.075755,CB,2.770538,1.789172,-1.789172,22.377775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20682,164945,07 Nuno Mendes,0.665442,Portugal,0.634035,-0.306835,US Créteil-Lusitanos,NaN,0.053943,-1.801951,...,-0.301205,-0.242915,0.616425,-0.182184,-0.188893,CB,0.218953,-0.558918,0.558918,24.075474
20683,252561,Zhang Yu,-1.413805,China PR,-2.379302,-0.473206,Hebei FC,0.11,-1.444731,-0.504570,...,-0.646154,-0.182813,-0.241252,-0.658054,-0.075755,CB,-1.652209,-0.558918,0.558918,21.132713
20684,262041,P. Maguire,-1.413805,Republic of Ireland,-2.522794,-0.805947,Sligo Rovers,0.11,0.053943,-0.504570,...,-0.186222,-0.663633,-0.057464,-0.539087,-0.584877,CB,-1.907368,-0.558918,0.558918,20.233553
20685,239427,21 A. Ajeti,-0.374181,Switzerland,-1.805333,-1.804170,FC St. Gallen 1879,0.20,0.053943,-0.504570,...,-0.128731,-0.182813,-0.363777,-0.420119,-0.358601,CB,-1.992421,1.789172,-1.789172,23.702162
20686,220806,16 E. Redman,-1.413805,Wales,-3.240256,-2.469653,Newport County,0.05,-1.444731,-0.504570,...,-0.186222,-0.543428,0.003798,-0.420119,-0.528308,CB,-3.183160,-0.558918,0.558918,23.924858

In [46]:
Def_detailed_features = ['Weak Foot', 'Skill Moves', 'Height', 'Weight','Bmi', 'Crossing', 'Finishing',
       'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve',
       'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle']

In [47]:
X = centrebacks_df[Def_detailed_features].to_numpy()
y = centrebacks_df["Ovr_pot"].to_numpy()
# define feature selection
fs = SelectKBest(score_func=f_regression, k = 10)
# apply feature selection
X_selected = fs.fit_transform(X, y)

In [48]:
Def_essential_ft = list(fs.get_feature_names_out(Def_detailed_features))
Def_essential_ft

['HeadingAccuracy',
 'ShortPassing',
 'LongPassing',
 'BallControl',
 'Reactions',
 'Aggression',
 'Interceptions',
 'Composure',
 'StandingTackle',
 'SlidingTackle']

# Fullbacks

In [49]:
fullbacks_df = F_norm_df[(F_norm_df["Best Position"] == "LB") | (F_norm_df["Best Position"] == "RB") | (F_norm_df["Best Position"] == "LWB") | (F_norm_df["Best Position"] == "RWB")]
fullbacks_df  = fullbacks_df.reset_index(drop = True)
fullbacks_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,197445,D. Alaba,-0.166257,Austria,2.786419,2.854206,FC Bayern München,41.500,1.552616,0.792811,...,-0.646154,-0.543428,-0.118727,-0.063216,-0.415170,LB,3.110749,1.789172,-1.789172,23.430985
1,203551,A. Florenzi,0.041668,Italy,2.212450,2.188724,Roma,20.500,0.053943,0.792811,...,-0.416188,-0.483325,-0.363777,-0.301151,-0.358601,RB,2.430326,-0.558918,0.558918,22.503074
2,163631,L. Baines,1.289216,England,2.355942,1.855983,Everton,14.500,0.053943,0.792811,...,-0.473679,-0.062607,-0.363777,-0.182184,-0.245462,LWB,2.345273,1.789172,-1.789172,24.119543
3,189332,Jordi Alba,0.457517,Spain,2.786419,2.355094,FC Barcelona,31.500,0.053943,0.792811,...,-0.186222,-0.062607,-0.179990,-0.598570,-0.188893,LWB,2.855590,1.789172,-1.789172,23.493061
4,146530,Dani Alves,1.705065,Brazil,2.499435,2.022353,Juventus,12.500,0.053943,0.792811,...,-0.646154,-0.303018,-0.425040,-0.598570,-0.528308,RWB,2.515379,-0.558918,0.558918,22.807169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13591,248815,K. Berkoe,-1.205880,England,-1.948825,-1.138688,Salford City,0.210,0.053943,-0.504570,...,-0.416188,-0.543428,-0.547565,-0.479603,-0.188893,LB,-1.737262,1.789172,-1.789172,20.515086
13592,261549,B. Ganesan,-1.205880,India,-2.666287,-1.804170,Chennaiyin FC,0.110,0.053943,-0.504570,...,-0.128731,-0.303018,-0.179990,-0.598570,-0.584877,RB,-2.502738,-0.558918,0.558918,19.814053
13593,260767,Z. Bello,-1.621729,Australia,-2.379302,-0.306835,Melbourne Victory,0.120,0.053943,-0.504570,...,-0.531171,-0.423223,-0.547565,-0.479603,-0.415170,RB,-1.567157,-0.558918,0.558918,21.857278
13594,252466,21 D. Bouah,-1.413805,Italy,-2.522794,-0.805947,Roma,0.110,-1.444731,-0.504570,...,-0.128731,-0.663633,-0.302515,-0.182184,-0.302032,RB,-1.907368,-0.558918,0.558918,23.620288
13595,260623,21 M. Wright,1.705065,England,-2.809779,-4.133359,Crawley Town,0.025,-2.943404,-0.504570,...,-0.128731,-0.423223,-0.118727,-0.479603,-0.641446,LB,-3.778530,1.789172,-1.789172,25.564954

In [50]:
Def_detailed_features = ['Weak Foot', 'Skill Moves', 'Height', 'Weight','Bmi', 'Crossing', 'Finishing',
       'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve',
       'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle']

In [51]:
X = fullbacks_df[Def_detailed_features].to_numpy()
y = fullbacks_df["Ovr_pot"].to_numpy()
# define feature selection
fs = SelectKBest(score_func=f_regression, k = 10)
# apply feature selection
X_selected = fs.fit_transform(X, y)

In [52]:
Fullback_essential_ft = list(fs.get_feature_names_out(Def_detailed_features))
Fullback_essential_ft

['Crossing',
 'ShortPassing',
 'Dribbling',
 'LongPassing',
 'BallControl',
 'Reactions',
 'Interceptions',
 'Composure',
 'StandingTackle',
 'SlidingTackle']

# Goalkeeper

In [53]:
gk_df = F_norm_df[(F_norm_df["Best Position"] == "GK")]
gk_df  = gk_df.reset_index(drop = True)
gk_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,230167,Mateus Tangil,0.665442,Brazil,0.060066,-0.805947,Atlético Mineiro,0.625,0.053943,-1.801951,...,2.860822,3.122829,2.883143,2.851492,3.148685,GK,-0.376417,-0.558918,0.558918,24.009113
1,230318,Nelsildo Reis,0.665442,Brazil,1.351496,0.691388,Internacional,4.600,0.053943,-1.801951,...,3.435736,3.663752,3.740820,3.565298,3.261823,GK,1.154534,-0.558918,0.558918,24.248069
2,167495,M. Neuer,1.081291,Germany,3.647373,3.353318,FC Bayern München,69.500,1.552616,-1.801951,...,4.183124,4.445085,4.843547,4.457556,4.110360,GK,3.876224,-0.558918,0.558918,24.709662
3,230171,Carlos Travisso,1.497140,Brazil,-0.513903,-1.471429,Botafogo,0.250,0.053943,-1.801951,...,2.975805,1.620264,2.944405,2.851492,3.148685,GK,-1.056840,-0.558918,0.558918,23.012574
4,230322,Teixe Gaúcho,0.665442,Brazil,-1.374856,-2.469653,Ponte Preta,0.100,-1.444731,-1.801951,...,3.090788,2.341495,2.331779,1.483364,2.582993,GK,-2.077473,-0.558918,0.558918,23.238767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10885,251433,B. Voll,-0.997955,Germany,-1.231364,-0.473206,F.C. Hansa Rostock,0.375,-1.444731,-1.801951,...,2.458382,2.642008,2.454304,2.316138,2.526424,GK,-0.971787,-0.558918,0.558918,22.353715
10886,240558,18 L. Clayton,-1.621729,England,-1.948825,-0.306835,Cheltenham Town,0.100,-1.444731,-1.801951,...,2.228417,2.281393,2.209254,2.018719,2.413286,GK,-1.311998,-0.558918,0.558918,22.634676
10887,262846,�. Dobre,-0.997955,Romania,-1.948825,-1.471429,FC Academica Clinceni,0.180,-1.444731,-1.801951,...,2.343399,2.161187,2.270516,1.899751,2.356717,GK,-1.907368,-0.558918,0.558918,22.850462
10888,241317,21 Xue Qinghao,-1.205880,China PR,-2.809779,-1.970541,Shanghai Shenhua FC,0.100,-1.444731,-1.801951,...,1.883468,1.920777,1.780415,1.304912,2.017302,GK,-2.672843,-0.558918,0.558918,21.913580
10889,259646,A. Shaikh,-1.413805,India,-2.809779,-0.805947,ATK Mohun Bagan FC,0.110,0.053943,-1.801951,...,1.883468,1.500059,1.412839,1.721299,1.847595,GK,-2.077473,-0.558918,0.558918,21.389756

In [54]:
Gk_detailed_features = ['Height', 'Weight','Bmi', 'ShortPassing', 'Volleys', 'Curve','Agility', 'Reactions', 'Balance',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
        'Positioning', 'Vision', 'Composure','GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes']

In [55]:
gk_df[gk_df["ID"]==167495]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
2,167495,M. Neuer,1.081291,Germany,3.647373,3.353318,FC Bayern München,69.5,1.552616,-1.801951,...,4.183124,4.445085,4.843547,4.457556,4.110360,GK,3.876224,-0.558918,0.558918,24.709662
1995,167495,M. Neuer,1.289216,Germany,3.647373,3.353318,FC Bayern München,61.0,1.552616,-1.801951,...,4.298107,4.445085,4.843547,4.457556,4.110360,GK,3.876224,-0.558918,0.558918,24.709662
4040,167495,M. Neuer,1.497140,Germany,3.073404,2.687836,FC Bayern München,34.0,1.552616,-1.801951,...,4.125633,4.204675,4.537234,4.100653,3.997221,GK,3.195802,-0.558918,0.558918,24.709662
6098,167495,M. Neuer,1.705065,Germany,3.216896,2.854206,FC Bayern München,36.0,1.552616,-1.801951,...,4.068142,4.264777,4.598497,4.160137,3.997221,GK,3.365907,-0.558918,0.558918,24.709662
7744,167495,M. Neuer,1.912989,Germany,3.216896,2.854206,FC Bayern München,29.0,1.552616,-1.801951,...,4.068142,4.264777,4.598497,4.160137,4.110360,GK,3.365907,-0.558918,0.558918,24.709662
9346,167495,M. Neuer,2.120914,Germany,3.360388,3.020577,FC Bayern München,13.5,1.552616,-1.801951,...,4.125633,4.324880,4.598497,4.338588,4.053791,GK,3.536013,-0.558918,0.558918,24.967113

In [56]:
X = gk_df[Gk_detailed_features].to_numpy()
y = gk_df["Ovr_pot"].to_numpy()
# define feature selection
fs = SelectKBest(score_func=f_regression, k = 10)
# apply feature selection
X_selected = fs.fit_transform(X, y)

In [57]:
Gk_essential_ft = list(fs.get_feature_names_out(Gk_detailed_features))
Gk_essential_ft

['Agility',
 'Reactions',
 'Jumping',
 'Vision',
 'Composure',
 'GKDiving',
 'GKHandling',
 'GKKicking',
 'GKPositioning',
 'GKReflexes']

# Finalizing all dataframes

In [58]:
# gk_df=gk_df[Gk_essential_ft]
# fullbacks_df = fullbacks_df[Fullback_essential_ft]
# centrebacks_df = centrebacks_df[Def_essential_ft]
# cam_df = cam_df[Cam_essential_ft]
# mids_df = mids_df[Mid_essential_ft]
# wingers_df = wingers_df[Wing_essential_ft]
# striker_df= striker_df[ST_essential_ft]

In [59]:
# F_all_df["Club"].unique().shape

In [60]:
# F_all_df[(F_all_df["Club"] == "Manchester United")].columns

In [61]:
all_clubs = list(F_all_df["Club"].unique())

In [62]:
all_clubs

['FC Barcelona',
 'Roma',
 'FC Bayern München',
 'Manchester United',
 'Real Madrid',
 'Everton',
 'Juventus',
 'Shakhtar Donetsk',
 'AS Monaco',
 'VfL Wolfsburg',
 'Milan',
 'Olympique de Marseille',
 'Olympique Lyonnais',
 'Beşiktaş JK',
 'Manchester City',
 'Liverpool',
 'FC Rostov',
 'Tottenham Hotspur',
 'Sporting CP',
 'Arsenal',
 'Paris Saint-Germain',
 'Napoli',
 nan,
 'FC Schalke 04',
 'OGC Nice',
 'SL Benfica',
 'Borussia Dortmund',
 'UD Las Palmas',
 'FC Porto',
 'Lazio',
 'Borussia Mönchengladbach',
 'PFC CSKA Moscow',
 'Chievo Verona',
 'Chelsea',
 'Leicester City',
 'Lokomotiv Moscow',
 'Atlético Madrid',
 'Sevilla FC',
 'Crystal Palace',
 'Chicago Fire',
 'Genoa',
 'Bournemouth',
 'Club Athletico Paranaense',
 'Athletic Club de Bilbao',
 'Montpellier HSC',
 'West Ham United',
 'SV Werder Bremen',
 'Villarreal CF',
 'Zenit St. Petersburg',
 '1. FC Köln',
 'Stoke City',
 'Inter',
 'Valencia CF',
 'Southampton',
 'Watford',
 'Club Brugge KV',
 'FC Krasnodar',
 'LOSC Lille',
 'Feyenoord',
 'RC Celta',
 'Toronto FC',
 'AS Saint-Étienne',
 'RSC Anderlecht',
 'Spartak Moscow',
 'PSV',
 'Udinese',
 'Ajax',
 'San Lorenzo de Almagro',
 'Hamburger SV',
 'Trabzonspor',
 'Fiorentina',
 'Grêmio',
 'Aston Villa',
 'Torino',
 'Burnley',
 'Montreal Impact',
 'Standard de Liège',
 'Swansea City',
 'Hertha BSC',
 'Monterrey',
 'Racing Club',
 'KAA Gent',
 'Universidad de Chile',
 'FC Basel 1893',
 'Sunderland',
 'TSG 1899 Hoffenheim',
 'Bayer 04 Leverkusen',
 'Granada CF',
 'Vitória Guimarães',
 'Deportivo de La Coruña',
 'Birmingham City',
 'Bologna',
 'Club Atlético Lanús',
 'Internacional',
 'Osmanlıspor',
 'VfB Stuttgart',
 'SV Darmstadt 98',
 'Toulouse Football Club',
 '1. FSV Mainz 05',
 'Levante UD',
 'Fenerbahçe SK',
 'Malmö FF',
 'FC Sion',
 'Vitesse',
 'Cagliari',
 'LA Galaxy',
 'Norwich City',
 'Legia Warszawa',
 'Guadalajara',
 'Tigres U.A.N.L.',
 'Newcastle United',
 'Angers SCO',
 'Rosenborg BK',
 'FC Utrecht',
 'Fluminense',
 'Sampdoria',
 'Al Ahli',
 'Galatasaray SK',
 'Bursaspor',
 'Medipol Başakşehir FK',
 'RCD Espanyol',
 'Seattle Sounders FC',
 'SD Eibar',
 'Atiker Konyaspor',
 'Al Nassr',
 'Sheffield Wednesday',
 'Real Betis',
 'FC Dallas',
 'FC Augsburg',
 'Kawasaki Frontale',
 'Derby County',
 'Huddersfield Town',
 'Rubin Kazan',
 'Boca Juniors',
 'Atalanta',
 'Vissel Kobe',
 'Sporting Kansas City',
 'Stade Rennais FC',
 'FC St. Gallen',
 'Sassuolo',
 'Universidad Católica',
 'Málaga CF',
 'Joinville',
 'RB Leipzig',
 'FC Ingolstadt 04',
 'Deportivo Alavés',
 'Hull City',
 'Çaykur Rizespor',
 'Olympiacos CFP',
 'Colo-Colo',
 'CD Leganés',
 'Club América',
 'Antalyaspor',
 'Kayserispor',
 'Clube Sport Marítimo',
 'Middlesbrough',
 'Independiente',
 'Getafe CF',
 'Palmeiras',
 'Panathinaikos FC',
 'CA Osasuna',
 'Hellas Verona',
 'AZ Alkmaar',
 'Real Sociedad',
 'West Bromwich Albion',
 'FC Metz',
 'FC Girondins de Bordeaux',
 'Al Hilal',
 'Club León',
 'IF Elfsborg',
 'Gimnàstic de Tarragona',
 'Brescia',
 'Colorado Rapids',
 'En Avant de Guingamp',
 'PAOK',
 'Kasimpaşa SK',
 'KV Oostende',
 'Philadelphia Union',
 'Goiás',
 'Reading',
 'Eintracht Braunschweig',
 'KRC Genk',
 'Deportivo Toluca',
 'Empoli',
 'Djurgårdens IF',
 'River Plate',
 'Santos',
 'Eintracht Frankfurt',
 'U.N.A.M.',
 'Orlando Pirates',
 'Kalmar FF',
 'Once Caldas',
 'Brighton & Hove Albion',
 'Club Tijuana',
 'New York City FC',
 'Al Shabab',
 'Independiente Medellín',
 'Pogoń Szczecin',
 'Odds BK',
 'Sporting Club de Bastia',
 'Sangju Sangmu FC',
 'Fulham',
 'Cesena',
 'Pachuca',
 'Akhisar Belediyespor',
 'Strømsgodset IF',
 'Football Bourg En Bresse Peronnas 01',
 'FC Ufa',
 'New York Red Bulls',
 'SC Braga',
 'Atlético Nacional',
 'Santos Laguna',
 'América FC (Minas Gerais)',
 'Gimnasia y Esgrima La Plata',
 'Jeju United FC',
 'Stade Malherbe Caen',
 'FC Paços de Ferreira',
 'Vitória',
 'Rayo Vallecano',
 'Pohang Steelers',
 'Brøndby IF',
 'Kashiwa Reysol',
 'Estudiantes de La Plata',
 'Bolton Wanderers',
 'Lech Poznań',
 "Newell's Old Boys",
 'Elche CF',
 'Northampton Town',
 'Gençlerbirliği SK',
 'Hannover 96',
 'Columbus Crew SC',
 'Tiburones Rojos de Veracruz',
 'Celtic',
 'Jaguares de Chiapas',
 'Rionegro Águilas',
 'SC Freiburg',
 'VfL Bochum 1848',
 'Gamba Osaka',
 'PEC Zwolle',
 'Portland Timbers',
 'Rio Ave FC',
 'Botafogo',
 'Kaizer Chiefs',
 'FC Lorient',
 'CD Tenerife',
 'Club Atlas',
 '1. FC Union Berlin',
 'FC Nantes',
 'Amkar Perm',
 'US Salernitana 1919',
 'Atlético Mineiro',
 'Terek Grozny',
 'Ternana',
 'Pescara',
 'SC Heerenveen',
 'Bristol City',
 'Inverness Caledonian Thistle',
 'Alanyaspor',
 'FC Groningen',
 'UD Almería',
 'Vancouver Whitecaps FC',
 'Dijon FCO',
 'Vitória de Setúbal',
 'Sport Club do Recife',
 'ADO Den Haag',
 'FC København',
 'Moreirense FC',
 'SD Huesca',
 'Coritiba',
 'CD Numancia',
 'Kardemir Karabükspor',
 'Palermo',
 'Crotone',
 'Wellington Phoenix',
 'Orlando City SC',
 'Real Sporting de Gijón',
 'Brentford',
 'Albirex Niigata',
 'New England Revolution',
 'RC Strasbourg Alsace',
 'Trapani',
 'Defensa y Justicia',
 'Nottingham Forest',
 'Stade Lavallois Mayenne FC',
 'Real Zaragoza',
 'Os Belenenses',
 'CD Mirandés',
 'FC Red Bull Salzburg',
 'São Paulo',
 'Girona FC',
 'Wolverhampton Wanderers',
 'Perth Glory',
 'Querétaro',
 'KV Kortrijk',
 'Junior FC',
 'Arsenal Tula',
 'Stade de Reims',
 '1. FC Nürnberg',
 'RCD Mallorca',
 'CD Feirense',
 'Boavista FC',
 'Monarcas Morelia',
 'KVC Westerlo',
 'Preston North End',
 'Grasshopper Club Zürich',
 'Sporting de Charleroi',
 'Bari',
 'Urawa Red Diamonds',
 'FC Orenburg',
 'Millonarios FC',
 'Leeds United',
 'Estoril Praia',
 'Godoy Cruz',
 'SV Zulte-Waregem',
 'Korona Kielce',
 'Gaziantepspor',
 'Fortuna Düsseldorf',
 'GD Chaves',
 'Jagiellonia Białystok',
 'FC Erzgebirge Aue',
 'Cardiff City',
 'Racing Club de Lens',
 'DSC Arminia Bielefeld',
 'Atlético Bucaramanga',
 'Heracles Almelo',
 'FC Arouca',
 'Sint-Truidense VV',
 'Plymouth Argyle',
 'Rosario Central',
 'SG Dynamo Dresden',
 'DC United',
 'Port Vale',
 'FC Ural Yekaterinburg',
 'Sporting Lokeren',
 'Melbourne City FC',
 'Ulsan Hyundai FC',
 'Aarhus GF',
 'FC Seoul',
 'Cruz Azul',
 'KV Mechelen',
 'Cruzeiro',
 'Sheffield United',
 'Bury',
 'AS Nancy Lorraine',
 'St. Johnstone FC',
 'FC St. Pauli',
 'Independiente Santa Fe',
 'Club Atlético Huracán',
 'Karlsruher SC',
 'Sydney FC',
 'Carpi',
 'Valenciennes FC',
 'Jeonbuk Hyundai Motors',
 'Chamois Niortais Football Club',
 'Figueirense',
 'Aalborg BK',
 'Pisa',
 'San Luis de Quillota',
 'Real Valladolid CF',
 'La Equidad',
 'CD Universidad de Concepción',
 'Bristol Rovers',
 'Club Atlético Talleres',
 'FC Pro Vercelli 1892',
 'CD Tondela',
 'CD Nacional',
 'Houston Dynamo',
 'IFK Göteborg',
 'Kashima Antlers',
 'Unión Española',
 '1. FC Kaiserslautern',
 'Suwon Samsung Bluewings',
 'Gillingham',
 'FC Twente',
 'Nîmes Olympique',
 'Dundee FC',
 'FC Midtjylland',
 'SK Brann',
 'Seongnam FC',
 'SK Rapid Wien',
 'Cracovia',
 'FC Würzburger Kickers',
 'Puebla FC',
 'Silkeborg IF',
 'Wisła Kraków',
 'Omiya Ardija',
 'Wolfsberger AC',
 'Ascoli',
 'TSV 1860 München',
 'FK Austria Wien',
 'Club Atlético Aldosivi',
 'Cádiz CF',
 'Real Oviedo',
 'Brisbane Roar',
 'Vasco da Gama',
 'Rangers FC',
 'Excelsior',
 'Real Salt Lake',
 'UCAM Murcia CF',
 'BK Häcken',
 'AC Ajaccio',
 'Vålerenga Fotball',
 'Deportivo Cali',
 'Ipswich Town',
 'Benevento',
 'Molde FK',
 'BSC Young Boys',
 'Sparta Rotterdam',
 'SPAL',
 'Santa Cruz',
 'Viking FK',
 'Millwall',
 'Unión de Santa Fe',
 'Grimsby Town',
 'Santiago Wanderers',
 'Willem II',
 'Suwon FC',
 'Lechia Gdańsk',
 'Fleetwood Town',
 'Club Atlético Sarmiento',
 'Notts County',
 'Blackburn Rovers',
 'Jeonnam Dragons',
 'Deportivo Pasto',
 'Perugia',
 'Southend United',
 'Zagłębie Lubin',
 'Queens Park Rangers',
 'Ponte Preta',
 'Novara',
 'Patriotas Boyacá FC',
 'Adanaspor',
 'FC Tokyo',
 'Wigan Athletic',
 'SpVgg Greuther Fürth',
 'Júbilo Iwata',
 'Avellino',
 'Club Atlético Banfield',
 'FC Sochaux-Montbéliard',
 'Criciúma',
 'Hamilton Academical FC',
 'Waasland-Beveren',
 'Chapecoense',
 'Córdoba CF',
 'Sanfrecce Hiroshima',
 'FC Tom Tomsk',
 'CD Lugo',
 'FC Vaduz',
 'Belgrano de Córdoba',
 'Charlton Athletic',
 'FC Lausanne-Sport',
 'Heart of Midlothian',
 'Aalesunds FK',
 'SønderjyskE',
 'Bruk-Bet Termalica Nieciecza',
 'Frosinone',
 'Shrewsbury',
 'Stade Brestois 29',
 'Jaguares de Córdoba',
 'Club Atlético Tigre',
 'NEC Nijmegen',
 'AIK',
 'Melbourne Victory',
 'Barnsley',
 'GFC Ajaccio',
 'Vicenza',
 'Deportes Tolima',
 'ESTAC Troyes',
 'Go Ahead Eagles',
 'Al Fateh',
 'Al Taawoun',
 '1. FC Heidenheim 1846',
 'Adelaide United',
 'Deportes Iquique',
 'Lillestrøm SK',
 'Club Atlético Colón',
 'Spezia',
 'FC Admira Wacker Mödling',
 'Atlético Tucumán',
 'FC Anzhi Makhachkala',
 'FK Haugesund',
 'Rotherham United',
 'Hammarby IF',
 'KAS Eupen',
 'US Orléans Loiret Football',
 'Club Atlético Temperley',
 'Clermont Foot 63',
 'Club Olimpo',
 'AD Alcorcón',
 'Audax Italiano',
 'Milton Keynes Dons',
 'Roda JC Kerkrade',
 'FC Lugano',
 'Coventry City',
 'Oxford United',
 'Cortuluá',
 'Western Sydney Wanderers',
 'Club Necaxa',
 'Bradford City',
 'Vélez Sarsfield',
 'Al Ittihad',
 'Rochdale',
 'Nagoya Grampus',
 'Colchester United',
 'Östersunds FK',
 'CF Reus Deportiu',
 'Piast Gliwice',
 'Aberdeen',
 'CD Huachipato',
 'Lyngby BK',
 'SCR Altach',
 'Esbjerg fB',
 'SV Mattersburg',
 'Ettifaq FC',
 'Al Qadisiyah',
 'Wisła Płock',
 'Sagan Tosu',
 'HJK Helsinki',
 'IFK Norrköping',
 'Latina',
 'Mansfield Town',
 'SV Ried',
 'Blackpool',
 'Yokohama F. Marinos',
 'Avaí FC',
 'SK Sturm Graz',
 'Incheon United FC',
 'Red Star FC',
 'Sarpsborg 08 FF',
 'Cittadella',
 'Arsenal de Sarandí',
 'GwangJu FC',
 'Ross County FC',
 'Leyton Orient',
 'Scunthorpe United',
 'Randers FC',
 'Doncaster Rovers',
 'Sevilla Atlético',
 'Odense Boldklub',
 'FC Thun',
 'Atlético de Rafaela',
 'Morecambe',
 'Burton Albion',
 'Helsingborgs IF',
 'Stabæk Fotball',
 'San Jose Earthquakes',
 'Oldham Athletic',
 'Walsall',
 'FC Luzern',
 'Tromsø IL',
 'CD Antofagasta',
 'Ventforet Kofu',
 'Quilmes Atlético Club',
 'SV Sandhausen',
 'San Martín de San Juan',
 "CD O'Higgins",
 'CD Palestino',
 'Cambridge United',
 'Örebro SK',
 'FC Nordsjælland',
 'Peterborough United',
 'Portsmouth',
 'Le Havre AC',
 'Jönköpings Södra IF',
 'Śląsk Wrocław',
 'Royal Excel Mouscron',
 'Kilmarnock',
 'Al Khaleej',
 'Cork City',
 'Atlético Huila',
 'Stevenage',
 'Krylya Sovetov Samara',
 'AC Horsens',
 'Swindon Town',
 "St. Patrick's Athletic",
 'Chesterfield',
 'Wycombe Wanderers',
 'Partick Thistle FC',
 'Amiens SC',
 'Arka Gdynia',
 'Górnik Łęczna',
 'Patronato',
 'AJ Auxerre',
 'Sligo Rovers',
 'GIF Sundsvall',
 'CD Everton de Viña del Mar',
 'Motherwell',
 'Crewe Alexandra',
 'Luton Town',
 'Al Wehda',
 'AFC Wimbledon',
 'IK Start',
 'Sogndal Fotball',
 'Tours FC',
 'Alianza Petrolera',
 'Boyacá Chicó FC',
 'Vegalta Sendai',
 'Virtus Entella',
 'Al Faisaly',
 'Dundalk',
 'CD Cobresal',
 'Exeter City',
 'Carlisle United',
 'Newcastle Jets',
 'Crawley Town',
 'Yeovil Town',
 'FK Bodø/Glimt',
 'Gefle IF',
 'Newport County',
 'Hartlepool United',
 'Derry City',
 'Al Raed',
 'Cheltenham Town',
 'Central Coast Mariners',
 'Shamrock Rovers',
 'Club Deportes Temuco',
 'Avispa Fukuoka',
 'Envigado FC',
 'Falkenbergs FF',
 'Bray Wanderers',
 'Viborg FF',
 'Ruch Chorzów',
 'Accrington Stanley',
 'Shonan Bellmare',
 'Galway United',
 'SKN St. Pölten',
 'Fortaleza CEIF',
 'Al Batin',
 'Finn Harps',
 'Barnet',
 'Bohemian FC',
 'Longford Town',
 'Wexford Youths',
 'AEK Athens',
 'Lobos BUAP',
 'Sivasspor',
 'Royal Antwerp FC',
 'AFC Eskilstuna',
 'Dinamo Moscow',
 'América de Cali',
 'CD Aves',
 'Göztepe SK',
 'NAC Breda',
 'Atlanta United',
 'MSV Duisburg',
 'Parma',
 'Sparta Praha',
 'Atlético Clube Goianiense',
 'VVV-Venlo',
 'Cultural Leonesa',
 'Cerezo Osaka',
 'Hibernian',
 'US Quevilly Rouen Métropole',
 'US Cremonese',
 'Portimonense SC',
 'FC Tosno',
 'SSV Jahn Regensburg',
 'Venezia FC',
 'Argentinos Juniors',
 'Minnesota United FC',
 'La Berrichonne de Châteauroux',
 'Yeni Malatyaspor',
 'Foggia',
 'Sandecja Nowy Sącz',
 'Albacete BP',
 'SKA Khabarovsk',
 '1. FC Magdeburg',
 'FC Barcelona B',
 'SC Preußen Münster',
 'SG Sonnenhof Großaspach',
 'Holstein Kiel',
 'Lincoln City',
 'Sandefjord Fotball',
 'Al Fayha',
 'Shimizu S-Pulse',
 'VfL Osnabrück',
 'VfL Sportfreunde Lotte',
 'Gangwon FC',
 'Ohod Club',
 'FC Zürich',
 'Hallescher FC',
 'Chemnitzer FC',
 'IK Sirius',
 'FSV Zwickau',
 'SV Meppen',
 'LASK Linz',
 'SC Paderborn 07',
 'Hokkaido Consadole Sapporo',
 'Górnik Zabrze',
 'SV Werder Bremen II',
 'FC Rot-Weiß Erfurt',
 'SC Fortuna Köln',
 'SpVgg Unterhaching',
 'Lorca FC',
 'VfR Aalen',
 'Curicó Unido',
 'SV Wehen Wiesbaden',
 'Hobro IK',
 'Kristiansund BK',
 'Paris FC',
 'FC Hansa Rostock',
 'Daegu FC',
 'Chacarita Juniors',
 'Forest Green Rovers',
 'Halmstads BK',
 'FC Carl Zeiss Jena',
 'Limerick FC',
 'Drogheda United',
 'FC Helsingør',
 'Tigres FC',
 'Guangzhou Evergrande Taobao FC',
 'Dalian YiFang FC',
 'Guangzhou R&F FC',
 'Shanghai SIPG FC',
 'Beijing Sinobo Guoan FC',
 'Hebei China Fortune FC',
 'Beijing Renhe FC',
 'Bahia',
 'Tianjin TEDA FC',
 'Viktoria Plzeň',
 'Jiangsu Suning FC',
 'Dynamo Kyiv',
 'Shanghai Greenland Shenhua FC',
 'MKE Ankaragücü',
 'SK Slavia Praha',
 'Los Angeles FC',
 'Shandong Luneng TaiShan FC',
 'Chongqing Dangdai Lifan FC SWM Team',
 'Cosenza',
 'Al Hazem',
 'Dinamo Zagreb',
 'Paraná',
 'Tianjin Quanjian FC',
 'Padova',
 'BB Erzurumspor',
 'Zagłębie Sosnowiec',
 'Neuchâtel Xamax',
 'Livorno',
 'Henan Jianye FC',
 'Fortuna Sittard',
 'Grenoble Foot 38',
 'CF Rayo Majadahonda',
 'Santa Clara',
 'FC Emmen',
 'San Martin de Tucumán',
 'V-Varen Nagasaki',
 'Ceará Sporting Club',
 'St. Mirren',
 'KSV Cercle Brugge',
 'Lecce',
 'Ranheim Fotball',
 'Unión La Calera',
 'KFC Uerdingen 05',
 'Vejle Boldklub',
 'Livingston FC',
 'FC Energie Cottbus',
 'Gyeongnam FC',
 'AS Béziers',
 'Extremadura UD',
 'Miedź Legnica',
 'Macclesfield Town',
 'De Graafschap',
 'Vendsyssel FF',
 'Tranmere Rovers',
 'FC Wacker Innsbruck',
 'Guizhou Hengfeng FC',
 'Trelleborgs FF',
 'Dalkurd FF',
 'Changchun Yatai FC',
 'IF Brommapojkarna',
 'Itagüí Leones FC',
 'TSV Hartberg',
 'Waterford FC',
 'CSA - AL',
 'Olimpia Asunción',
 'Denizlispor',
 'Independiente del Valle',
 'Atlético de San Luis',
 'LDU Quito',
 'Shenzhen FC',
 'Famalicão',
 'Sol de América',
 'FC Juárez',
 'Pordenone',
 'CFR Cluj',
 'Fortaleza',
 'Castellammare di Stabia',
 'Astra Giurgiu',
 'Universitatea Craiova',
 'FC Cincinnati',
 'Flamengo',
 'Peñarol',
 'Nacional de Montevideo',
 'Deportivo Binacional',
 'Club Bolívar',
 'Central Córdoba',
 'Al Ain FC',
 'Club Libertad',
 'FCSB (Steaua)',
 'FC Viitorul',
 'SD Ponferradina',
 'RKC Waalwijk',
 'Wuhan Zall',
 'Gil Vicente FC',
 'Gazişehir Gaziantep F.K.',
 'FC Botoşani',
 'CF Fuenlabrada',
 'UE Llagostera',
 'Oriente Petrolero',
 'Western United FC',
 'Damac FC',
 'Barcelona Sporting Club',
 'Catania',
 'Sepsi OSK',
 'Club Guaraní',
 'Salford City',
 'Real Madrid Castilla',
 'Raków Częstochowa',
 'Delfín SC',
 'Sport Huancayo',
 'Kuban Krasnodar',
 'SV Waldhof Mannheim',
 'Unión Magdalena',
 'Melgar FBC',
 'SD Aucas',
 'Nacional Asunción',
 'Politehnica Iaşi',
 'Coquimbo Unido',
 'Alianza Lima',
 'Emelec',
 'Bayern München II',
 'FC Voluntari',
 'Viktoria Köln',
 'Servette FC',
 'Club Atlético Grau',
 'Dinamo Bucureşti',
 'Gaz Metan Mediaş',
 'Liverpool Fútbol Club',
 'Racing Santander',
 'Le Mans FC',
 'Jorge Wilstermann',
 'Club Plaza Colonia',
 'Cusco FC',
 'Mjøndalen IF',
 'Oita Trinita',
 'AC Arles Avignon',
 'River Plate Montevideo',
 'El Nacional',
 'FC Chambly Oise',
 'Matsumoto Yamaga',
 'Chindia Târgovişte',
 'Nacional Potosí',
 'Corinthians',
 'Universidad Católica del Ecuador',
 'WSG Tirol',
 'Daejeon Citizen',
 'Centro Atlético Fénix',
 'Academica Clinceni',
 'Always Ready',
 'Abha Club',
 'Associação Académica de Coimbra',
 'Dundee United',
 'Como',
 'Al Adalah',
 'River Plate Asunción',
 'FC Hermannstadt',
 'Club Blooming',
 'UC AlbinoLeffe',
 'Estudiantes de Mérida',
 'Caracas FC',
 'AC Mineros de Guayana',
 'LKS Lodz',
 'Rodez Aveyron Football',
 'Rangers de Talca',
 'Aragua FC',
 'Grosseto',
 'UCD AFC',
 'Llaneros de Guanare',
 'Estudiantes Tecos',
 'Lierse SK',
 'Dynamo České Budějovice',
 'Cúcuta Deportivo',
 'Leones Negros de la UdeG',
 '111648',
 'Åtvidabergs FF',
 'Sportivo Luqueño',
 'Mersin İdman Yurdu',
 'GKS Bełchatów',
 'Zamora FC',
 'Clube Náutico Capibaribe',
 'Najran SC',
 'Sandnes Ulf',
 'RC Recreativo de Huelva',
 'Torquay United',
 'Podbeskidzie Bielsko-Biała',
 'Al Nahdha Dammam',
 'US Créteil-Lusitanos',
 'Atlante',
 'UD Vecindario',
 'FC Cartagena',
 'Arezzo',
 'Inter Miami',
 'AC Monza',
 'Fatih Karagümrük S.K.',
 'Qingdao Huanghai F.C.',
 'Shijiazhuang Ever Bright F.C.',
 'Farense',
 'Hatayspor',
 'Oceânico FC',
 'Mazatlán FC',
 'Beerschot AC',
 'C.D. Castellón',
 'VfB Lübeck',
 'Oud-Heverlee Leuven',
 'Volga Nizhny Novgorod',
 'UD Logroñés',
 'Busan IPark',
 'Nashville SC',
 'Pau FC',
 'Dorados de Sinaloa',
 'Yokohama FC',
 'CE Sabadell FC',
 'Stal Mielec',
 'UTA Arad',
 'Barrow',
 '1. FC Saarbrücken',
 'Macarthur FC',
 'Türkgücü München',
 'Harrogate Town',
 'Mjällby AIF',
 'FC Argeș',
 'SC Verl',
 '113974',
 'Varbergs BoIS',
 'USL Dunkerque',
 'Alemannia Aachen',
 'Shelbourne FC',
 'Hércules CF',
 '114912',
 'Warta Poznań',
 'União de Leiria',
 'Siena',
 'Santo André',
 'KSV 1919',
 'CF Estrela da Amadora',
 'CD Trofense',
 'Sakaryaspor',
 'Atlético de Madrid',
 'Real Madrid CF',
 'Real Betis Balompié',
 'AC Milan',
 'Beijing Guoan FC',
 'Unión Deportiva Almería',
 'Shanghai Port FC',
 'Montpellier Hérault SC',
 'Levante Unión Deportiva',
 'RB Bragantino',
 'Unión Deportiva Las Palmas',
 'Guangzhou City',
 'Jiangsu FC',
 'Udinese Calcio',
 'Shanghai Shenhua FC',
 'TSG Hoffenheim',
 'Torino F.C.',
 'Guangzhou FC',
 'RCD Espanyol de Barcelona',
 'Club Olimpia',
 'RC Celta de Vigo',
 'Inter Miami CF',
 'Al Ain',
 'Spartak Moskva',
 'Gallos Blancos de Querétaro',
 'Sport-Club Freiburg',
 'Hebei FC',
 'Adana Demirspor',
 'Club Atlético Independiente',
 'İstanbul Başakşehir FK',
 'Clube Atlético Mineiro',
 'CF Monterrey ',
 'F.C. København',
 'FC Lokomotiv Moscow',
 'U.C. Sampdoria',
 'AFC Bournemouth',
 'Fútbol Club Juárez',
 'AC Sparta Praha',
 'FC Viktoria Plzeň',
 'Columbus Crew',
 'Atakaş Hatayspor',
 'Sport Club Corinthians Paulista',
 'U.S. Sassuolo Calcio',
 'Yukatel Kayserispor',
 'Demir Grup Sivasspor',
 'İttifak Holding Konyaspor',
 'Shandong Taishan',
 'Qingdao FC',
 'Austin FC',
 'Club Atlético Central Córdoba',
 'Orlando City Soccer Club',
 'N.E.C. Nijmegen',
 'Tianjin Jinmen Tiger FC',
 ...]

# Previous players in a club

In [63]:
# strikers_in_club={}

# for club in all_clubs:
#     all_features = striker_df[striker_df["Club"] == club]
#     essential_features = all_features[ST_essential_ft]
#     weights_vector=[]
#     for i in essential_features:
#         if essential_features[i].std() !=0:
#             weights_vector.append(1/essential_features[i].std())
#         else:
#             weights_vector.append(0)
#     # print(weights_vector)
#     strikers_in_club[club] = weights_vector

# Get weights of a particular position for all clubs

Weights are how dense the essential feature is. This is reciprocal of standard deviation

In [64]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
def get_pos_weights(pos_df,pos_essential_ft):
    pos_players_in_club={}

    for club in all_clubs:
        all_features = pos_df[pos_df["Club"] == club]
        all_features = all_features.sort_values('Ovr_pot',ascending = False).head(20)
        essential_features = all_features[pos_essential_ft]
        weights_vector=[]
        sum = 0
        for i in essential_features:
            if essential_features[i].std() != 0:
                weights_vector.append(1/essential_features[i].std())
                sum += 1/essential_features[i].std()
            else:
                weights_vector.append(0)
                sum += 0
        # print(pos_essential_ft,club,weights_vector)
        if(sum != 0):
            for x in range(len(weights_vector)):
                weights_vector[x] = weights_vector[x] / sum
        pos_players_in_club[club] = weights_vector
        #print(sum)
    np_array = np.empty((0,len(pos_essential_ft)))
    for club in all_clubs:
        n_row = np.array(pos_players_in_club[club])
        n_row.shape = (1,len(pos_essential_ft))
        np_array = np.append(np_array, n_row, axis = 0)
    scaler = StandardScaler()
    np_array = scaler.fit_transform(np_array)
    count = 0
    for club in all_clubs:
        scaler = MinMaxScaler()
        n_ar = np_array[count]
        n_ar.shape = (len(pos_essential_ft),1)
        n_ar = scaler.fit_transform(n_ar)
        n_ar.shape = (len(pos_essential_ft),)
        pos_players_in_club[club] = (n_ar/np.sum(n_ar)).tolist()
        count += 1

    return pos_players_in_club

# Extracting Common features across positions

In [65]:
pos_essential_features = [ST_essential_ft,Wing_essential_ft,Mid_essential_ft,Cam_essential_ft,Def_essential_ft,Fullback_essential_ft]
# common_features =   []
# d={}
# for i in pos_essential_features:
#     for j in i:
#         if j not in d:
#             d[j]=1
#         else:
#             d[j]+=1

# for i in d:
#     if d[i]==len(pos_essential_features):
#         common_features.append(i)

#Can be optimized 

#basically removing all common features from the essential features of a position
# for i in common_features:
#     ST_essential_ft.remove(i)
#     Wing_essential_ft.remove(i)
#     Mid_essential_ft.remove(i)
#     Cam_essential_ft.remove(i)
#     Def_essential_ft.remove(i)
#     Fullback_essential_ft.remove(i)
    # Gk_essential_ft.remove(i)

In [66]:
# common_features

In [67]:
#common_features.extend(["Age", "Height", "Weight", "Weak Foot"])
common_features = (["Age"])

More features to be appended to common features.

# Training Data Preparation

In [68]:
from sklearn.preprocessing import MinMaxScaler
scaler = sklearn.preprocessing.MinMaxScaler()
F_std_df = F_all_df.copy(deep = True)
F_std_df[detailed_features] = scaler.fit_transform(F_std_df[detailed_features].to_numpy())
F_std_df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Weak Foot', 'Skill Moves', 'Position', 'Height', 'Weight',
       'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys',
       'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance',
       'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Best Position', 'Ovr_pot', 'Preferred Foot_Left',
       'Preferred Foot_Right', 'Bmi'],
      dtype='object')

In [69]:
df_17_std = F_std_df.iloc[:df_17.shape[0]]
df_18_std = F_std_df.iloc[df_17.shape[0]:df_18.shape[0] + df_17.shape[0]]
df_19_std = F_std_df.iloc[df_17.shape[0] + df_18.shape[0]:df_18.shape[0] + df_17.shape[0] + df_19.shape[0]]
df_20_std = F_std_df.iloc[df_17.shape[0] + df_18.shape[0] + df_19.shape[0]:df_18.shape[0] + df_17.shape[0] + df_19.shape[0] + df_20.shape[0]]
df_21_std = F_std_df.iloc[df_17.shape[0] + df_18.shape[0] + df_19.shape[0] + df_20.shape[0]:df_18.shape[0] + df_17.shape[0] + df_19.shape[0] + df_20.shape[0] + df_21.shape[0]]
df_22_std = F_std_df.tail(df_22.shape[0])

# Weights per Position

In [70]:
striker_df = F_std_df[(F_std_df["Best Position"] == "ST") | (F_std_df["Best Position"] == "CF") | (F_std_df["Best Position"] == "LF")]
striker_df  =  striker_df.reset_index(drop = True)
striker_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,176580,L. Suárez,0.358974,Uruguay,0.969697,0.947368,FC Barcelona,83.00,0.75,0.75,...,0.288889,0.263736,0.319149,0.347826,0.391304,ST,0.967213,0.0,1.0,25.768347
1,173731,G. Bale,0.282051,Wales,0.939394,0.912281,Real Madrid,72.00,0.50,0.75,...,0.155556,0.153846,0.106383,0.043478,0.054348,ST,0.934426,1.0,0.0,22.106529
2,20801,Cristiano Ronaldo,0.410256,Portugal,1.000000,0.982456,Real Madrid,87.00,0.75,1.00,...,0.066667,0.109890,0.148936,0.141304,0.108696,ST,1.000000,0.0,1.0,23.220144
3,184941,A. Sánchez,0.307692,Chile,0.909091,0.877193,Arsenal,55.00,0.50,0.75,...,0.100000,0.098901,0.148936,0.119565,0.130435,ST,0.901639,0.0,1.0,21.456996
4,54050,W. Rooney,0.384615,England,0.818182,0.771930,Manchester United,18.50,0.75,0.50,...,0.100000,0.109890,0.127660,0.076087,0.065217,ST,0.803279,0.0,1.0,27.024076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15809,262034,R. Mahon,0.076923,Republic of Ireland,0.303030,0.385965,Bohemian FC,0.11,0.50,0.25,...,0.066667,0.142857,0.053191,0.076087,0.152174,ST,0.344262,1.0,0.0,20.549887
15810,259650,F. Molla,0.102564,India,0.287879,0.508772,ATK Mohun Bagan FC,0.13,0.25,0.25,...,0.077778,0.054945,0.138298,0.108696,0.141304,ST,0.393443,0.0,1.0,24.304618
15811,161659,07 Danilo,0.230769,Brazil,0.545455,0.508772,Gallos Blancos de Querétaro,NaN,0.50,0.00,...,0.111111,0.054945,0.595745,0.152174,0.119565,ST,0.532787,1.0,0.0,24.930748
15812,150597,09 J. Moukoko,0.205128,Congo DR,0.393939,0.421053,NaN,NaN,0.50,0.00,...,0.077778,0.263736,0.414894,0.260870,0.260870,ST,0.409836,0.0,1.0,23.503556
15813,178453,07 A. Censori,0.051282,Italy,0.000000,0.000000,Arezzo,NaN,0.25,0.00,...,0.066667,0.000000,0.372340,0.054348,0.086957,ST,0.000000,0.0,1.0,22.024323

In [71]:
wingers_df = F_std_df[(F_std_df["Best Position"] == "LW") | (F_std_df["Best Position"] == "RW")]
wingers_df  =  wingers_df.reset_index(drop = True)
wingers_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,190871,Neymar,0.230769,Brazil,0.969697,0.982456,FC Barcelona,106.00,1.00,1.00,...,0.088889,0.087912,0.148936,0.152174,0.108696,LW,0.983607,0.0,1.0,22.150882
1,193130,A. Schürrle,0.256410,Germany,0.803030,0.771930,Borussia Dortmund,19.00,0.75,0.50,...,0.066667,0.109890,0.117021,0.086957,0.119565,RW,0.795082,0.0,1.0,22.106529
2,209331,M. Salah,0.230769,Egypt,0.818182,0.824561,Roma,26.00,0.25,0.75,...,0.144444,0.142857,0.085106,0.108696,0.141304,RW,0.827869,1.0,0.0,23.479935
3,222492,L. Sané,0.128205,Germany,0.818182,0.929825,Manchester City,31.00,0.50,0.50,...,0.077778,0.120879,0.085106,0.086957,0.141304,LW,0.877049,1.0,0.0,22.784644
4,185020,José Callejón,0.358974,Spain,0.833333,0.789474,Napoli,22.50,0.25,0.50,...,0.077778,0.043956,0.138298,0.108696,0.108696,RW,0.819672,0.0,1.0,23.100839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3930,248281,20 D. Borrero,0.051282,Colombia,0.424242,0.649123,Club Independiente Santa Fe,0.18,0.50,0.50,...,0.122222,0.087912,0.085106,0.043478,0.130435,RW,0.532787,0.0,1.0,21.847009
3931,263090,J. Eng,0.025641,Norway,0.378788,0.666667,Vålerenga Fotball,0.30,0.50,0.50,...,0.100000,0.098901,0.063830,0.097826,0.043478,RW,0.516393,0.0,1.0,24.074074
3932,264675,J. Dickman,0.128205,Sweden,0.363636,0.508772,FC Nordsjælland,0.19,0.50,0.25,...,0.144444,0.153846,0.117021,0.065217,0.054348,RW,0.434426,0.0,1.0,22.582709
3933,261677,R. O'Kane,0.051282,Republic of Ireland,0.348485,0.649123,Dundalk FC,0.18,0.25,0.25,...,0.111111,0.120879,0.138298,0.097826,0.054348,RW,0.491803,0.0,1.0,20.904195
3934,256458,K. Swaleh,0.076923,Norway,0.333333,0.561404,FK Bodø/Glimt,0.13,0.50,0.25,...,0.111111,0.142857,0.127660,0.054348,0.076087,RW,0.442623,0.0,1.0,20.761246

In [72]:
mids_df = F_std_df[(F_std_df["Best Position"] == "RM") | (F_std_df["Best Position"] == "CM") | (F_std_df["Best Position"] == "CDM") | (F_norm_df["Best Position"] == "LM")]
mids_df  =  mids_df.reset_index(drop = True)
mids_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,178518,R. Nainggolan,0.333333,Belgium,0.878788,0.842105,Roma,37.50,0.50,0.50,...,0.111111,0.109890,0.138298,0.076087,0.108696,CDM,0.868852,0.0,1.0,21.117175
1,181872,A. Vidal,0.358974,Chile,0.893939,0.859649,FC Bayern München,41.50,0.75,0.50,...,0.033333,0.010989,0.031915,0.010870,0.032609,CDM,0.885246,0.0,1.0,23.012574
2,177003,L. Modrić,0.384615,Croatia,0.924242,0.894737,Real Madrid,54.00,0.75,0.75,...,0.133333,0.087912,0.063830,0.141304,0.086957,CM,0.918033,0.0,1.0,21.117175
3,173210,C. Marchisio,0.384615,Italy,0.878788,0.842105,Juventus,35.00,0.75,0.75,...,0.033333,0.021978,0.031915,0.010870,0.032609,CM,0.868852,0.0,1.0,22.454694
4,139997,D. Srna,0.487179,Croatia,0.803030,0.754386,Shakhtar Donetsk,4.80,0.50,0.50,...,0.100000,0.098901,0.053191,0.054348,0.119565,CM,0.786885,0.0,1.0,22.813872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26907,4174,07 P. Sarr,0.333333,Senegal,0.560606,0.561404,Stade Brestois 29,NaN,0.50,0.00,...,0.088889,0.120879,0.712766,0.076087,0.108696,CDM,0.565574,0.0,1.0,23.456790
26908,246839,21 C. Bargary,0.102564,Republic of Ireland,0.348485,0.508772,Cork City,0.15,0.50,0.25,...,0.100000,0.054945,0.106383,0.054348,0.043478,RM,0.426230,0.0,1.0,21.777553
26909,235352,18 T. Käßemodel,0.333333,Germany,0.272727,0.140351,FC Erzgebirge Aue,0.03,0.50,0.25,...,0.100000,0.120879,0.053191,0.130435,0.054348,CM,0.213115,0.0,1.0,25.059307
26910,4373,07 S. Valakari,0.461538,Finland,0.575758,0.508772,FC Dallas,NaN,0.50,0.00,...,0.055556,0.021978,0.553191,0.054348,0.021739,CDM,0.549180,1.0,0.0,26.753864
26911,19334,10 I. Baraclough,0.589744,England,0.242424,0.473684,NaN,NaN,0.50,0.00,...,0.044444,0.208791,0.478723,0.206522,0.206522,CM,0.352459,1.0,0.0,23.666910

In [73]:
cam_df = F_std_df[(F_std_df["Best Position"] == "CAM")]
cam_df  =  cam_df.reset_index(drop = True)
cam_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,195864,P. Pogba,0.205128,France,0.909091,0.982456,Manchester United,71.50,0.75,1.00,...,0.044444,0.054945,0.010638,0.032609,0.021739,CAM,0.950820,0.0,1.0,23.123158
1,20289,Y. Touré,0.461538,Ivory Coast,0.848485,0.807018,Manchester City,18.00,0.75,0.50,...,0.133333,0.142857,0.053191,0.119565,0.076087,CAM,0.836066,0.0,1.0,25.421414
2,189509,Thiago,0.256410,Spain,0.878788,0.877193,FC Bayern München,46.00,0.50,1.00,...,0.055556,0.109890,0.063830,0.086957,0.130435,CAM,0.885246,0.0,1.0,22.741573
3,171877,M. Hamšik,0.333333,Slovakia,0.878788,0.842105,Napoli,37.50,0.75,0.50,...,0.077778,0.054945,0.031915,0.141304,0.141304,CAM,0.868852,0.0,1.0,23.598381
4,180206,M. Pjanić,0.282051,Bosnia Herzegovina,0.863636,0.842105,Juventus,37.50,0.75,0.75,...,0.066667,0.065934,0.127660,0.065217,0.076087,CAM,0.860656,0.0,1.0,21.478402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12512,252881,21 H. Hopper,0.102564,England,0.333333,0.508772,Rochdale,0.12,0.25,0.25,...,0.077778,0.065934,0.042553,0.076087,0.097826,CAM,0.418033,0.0,1.0,21.877551
12513,243725,D. Collins,0.128205,Republic of Ireland,0.287879,0.315789,Sligo Rovers,0.10,0.50,0.25,...,0.055556,0.087912,0.042553,0.130435,0.076087,CAM,0.303279,0.0,1.0,22.460034
12514,259857,A. Majok,0.128205,South Sudan,0.333333,0.508772,Western United FC,0.12,0.25,0.25,...,0.077778,0.109890,0.095745,0.076087,0.097826,CAM,0.418033,0.0,1.0,21.132713
12515,261748,C. McLaughlin,0.102564,Republic of Ireland,0.348485,0.368421,Derry City,0.13,0.50,0.50,...,0.122222,0.087912,0.106383,0.141304,0.065217,CAM,0.360656,1.0,0.0,22.857143
12516,261818,R. Gallagher,0.128205,Republic of Ireland,0.287879,0.403509,Finn Harps,0.11,0.50,0.25,...,0.144444,0.098901,0.063830,0.130435,0.076087,CAM,0.344262,0.0,1.0,22.839506

In [74]:
centrebacks_df = F_std_df[(F_std_df["Best Position"] == "CB")]
centrebacks_df  = centrebacks_df.reset_index(drop = True)
centrebacks_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,185103,A. Kolarov,0.384615,Serbia,0.787879,0.736842,Manchester City,10.00,0.50,0.25,...,0.166667,0.153846,0.074468,0.163043,0.054348,CB,0.770492,1.0,0.0,23.495549
1,155862,Sergio Ramos,0.384615,Spain,0.924242,0.894737,Real Madrid,43.50,0.50,0.50,...,0.111111,0.076923,0.085106,0.065217,0.108696,CB,0.918033,0.0,1.0,22.377775
2,164240,Thiago Silva,0.410256,Brazil,0.924242,0.894737,Paris Saint-Germain,39.50,0.50,0.50,...,0.088889,0.120879,0.042553,0.086957,0.097826,CB,0.918033,0.0,1.0,23.598381
3,179944,David Luiz,0.358974,Brazil,0.848485,0.807018,Chelsea,22.00,0.50,0.50,...,0.111111,0.120879,0.095745,0.065217,0.141304,CB,0.836066,0.0,1.0,23.752331
4,205600,S. Umtiti,0.179487,France,0.833333,0.877193,FC Barcelona,27.00,0.50,0.25,...,0.155556,0.098901,0.138298,0.119565,0.152174,CB,0.860656,1.0,0.0,22.377775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20682,164945,07 Nuno Mendes,0.333333,Portugal,0.651515,0.561404,US Créteil-Lusitanos,NaN,0.50,0.00,...,0.111111,0.120879,0.265957,0.130435,0.130435,CB,0.614754,0.0,1.0,24.075474
20683,252561,Zhang Yu,0.076923,China PR,0.333333,0.543860,Hebei FC,0.11,0.25,0.25,...,0.044444,0.131868,0.117021,0.043478,0.152174,CB,0.434426,0.0,1.0,21.132713
20684,262041,P. Maguire,0.076923,Republic of Ireland,0.318182,0.508772,Sligo Rovers,0.11,0.50,0.25,...,0.133333,0.043956,0.148936,0.065217,0.054348,CB,0.409836,0.0,1.0,20.233553
20685,239427,21 A. Ajeti,0.205128,Switzerland,0.393939,0.403509,FC St. Gallen 1879,0.20,0.50,0.25,...,0.144444,0.131868,0.095745,0.086957,0.097826,CB,0.401639,1.0,0.0,23.702162
20686,220806,16 E. Redman,0.076923,Wales,0.242424,0.333333,Newport County,0.05,0.25,0.25,...,0.133333,0.065934,0.159574,0.086957,0.065217,CB,0.286885,0.0,1.0,23.924858

In [75]:
fullbacks_df = F_std_df[(F_std_df["Best Position"] == "LB") | (F_std_df["Best Position"] == "RB") | (F_std_df["Best Position"] == "LWB") | (F_std_df["Best Position"] == "RWB")]
fullbacks_df  = fullbacks_df.reset_index(drop = True)
fullbacks_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,197445,D. Alaba,0.230769,Austria,0.878788,0.894737,FC Bayern München,41.500,0.75,0.50,...,0.044444,0.065934,0.138298,0.152174,0.086957,LB,0.893443,1.0,0.0,23.430985
1,203551,A. Florenzi,0.256410,Italy,0.818182,0.824561,Roma,20.500,0.50,0.50,...,0.088889,0.076923,0.095745,0.108696,0.097826,RB,0.827869,0.0,1.0,22.503074
2,163631,L. Baines,0.410256,England,0.833333,0.789474,Everton,14.500,0.50,0.50,...,0.077778,0.153846,0.095745,0.130435,0.119565,LWB,0.819672,1.0,0.0,24.119543
3,189332,Jordi Alba,0.307692,Spain,0.878788,0.842105,FC Barcelona,31.500,0.50,0.50,...,0.133333,0.153846,0.127660,0.054348,0.130435,LWB,0.868852,1.0,0.0,23.493061
4,146530,Dani Alves,0.461538,Brazil,0.848485,0.807018,Juventus,12.500,0.50,0.50,...,0.044444,0.109890,0.085106,0.054348,0.065217,RWB,0.836066,0.0,1.0,22.807169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13591,248815,K. Berkoe,0.102564,England,0.378788,0.473684,Salford City,0.210,0.50,0.25,...,0.088889,0.065934,0.063830,0.076087,0.130435,LB,0.426230,1.0,0.0,20.515086
13592,261549,B. Ganesan,0.102564,India,0.303030,0.403509,Chennaiyin FC,0.110,0.50,0.25,...,0.144444,0.109890,0.127660,0.054348,0.054348,RB,0.352459,0.0,1.0,19.814053
13593,260767,Z. Bello,0.051282,Australia,0.333333,0.561404,Melbourne Victory,0.120,0.50,0.25,...,0.066667,0.087912,0.063830,0.076087,0.086957,RB,0.442623,0.0,1.0,21.857278
13594,252466,21 D. Bouah,0.076923,Italy,0.318182,0.508772,Roma,0.110,0.25,0.25,...,0.144444,0.043956,0.106383,0.130435,0.108696,RB,0.409836,0.0,1.0,23.620288
13595,260623,21 M. Wright,0.461538,England,0.287879,0.157895,Crawley Town,0.025,0.00,0.25,...,0.144444,0.087912,0.138298,0.076087,0.043478,LB,0.229508,1.0,0.0,25.564954

In [76]:
gk_df = F_std_df[(F_std_df["Best Position"] == "GK")]
gk_df  = gk_df.reset_index(drop = True)
gk_df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
0,230167,Mateus Tangil,0.333333,Brazil,0.590909,0.508772,Atlético Mineiro,0.625,0.50,0.0,...,0.722222,0.736264,0.659574,0.684783,0.771739,GK,0.557377,0.0,1.0,24.009113
1,230318,Nelsildo Reis,0.333333,Brazil,0.727273,0.666667,Internacional,4.600,0.50,0.0,...,0.833333,0.835165,0.808511,0.815217,0.793478,GK,0.704918,0.0,1.0,24.248069
2,167495,M. Neuer,0.384615,Germany,0.969697,0.947368,FC Bayern München,69.500,0.75,0.0,...,0.977778,0.978022,1.000000,0.978261,0.956522,GK,0.967213,0.0,1.0,24.709662
3,230171,Carlos Travisso,0.435897,Brazil,0.530303,0.438596,Botafogo,0.250,0.50,0.0,...,0.744444,0.461538,0.670213,0.684783,0.771739,GK,0.491803,0.0,1.0,23.012574
4,230322,Teixe Gaúcho,0.333333,Brazil,0.439394,0.333333,Ponte Preta,0.100,0.25,0.0,...,0.766667,0.593407,0.563830,0.434783,0.663043,GK,0.393443,0.0,1.0,23.238767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10885,251433,B. Voll,0.128205,Germany,0.454545,0.543860,F.C. Hansa Rostock,0.375,0.25,0.0,...,0.644444,0.648352,0.585106,0.586957,0.652174,GK,0.500000,0.0,1.0,22.353715
10886,240558,18 L. Clayton,0.051282,England,0.378788,0.561404,Cheltenham Town,0.100,0.25,0.0,...,0.600000,0.582418,0.542553,0.532609,0.630435,GK,0.467213,0.0,1.0,22.634676
10887,262846,�. Dobre,0.128205,Romania,0.378788,0.438596,FC Academica Clinceni,0.180,0.25,0.0,...,0.622222,0.560440,0.553191,0.510870,0.619565,GK,0.409836,0.0,1.0,22.850462
10888,241317,21 Xue Qinghao,0.102564,China PR,0.287879,0.385965,Shanghai Shenhua FC,0.100,0.25,0.0,...,0.533333,0.516484,0.468085,0.402174,0.554348,GK,0.336066,0.0,1.0,21.913580
10889,259646,A. Shaikh,0.076923,India,0.287879,0.508772,ATK Mohun Bagan FC,0.110,0.50,0.0,...,0.533333,0.439560,0.404255,0.478261,0.521739,GK,0.393443,0.0,1.0,21.389756

In [77]:
import pickle

In [78]:
# striker_weights_per_club = get_pos_weights(striker_df,ST_essential_ft)
# with open('./rec_extended_data/striker_weights_per_club.pkl', 'wb') as f:
#     pickle.dump(striker_weights_per_club, f)
# wing_weights_per_club = get_pos_weights(wingers_df,Wing_essential_ft)
# with open('./rec_extended_data/wing_weights_per_club.pkl', 'wb') as f:
#     pickle.dump(wing_weights_per_club, f)
# mid_weights_per_club = get_pos_weights(mids_df,Mid_essential_ft)
# with open('./rec_extended_data/mid_weights_per_club.pkl', 'wb') as f:
#     pickle.dump(mid_weights_per_club, f)
# cam_weights_per_club = get_pos_weights(cam_df,Cam_essential_ft)
# with open('./rec_extended_data/cam_weights_per_club.pkl', 'wb') as f:
#     pickle.dump(cam_weights_per_club, f)
# def_weights_per_club = get_pos_weights(centrebacks_df,Def_essential_ft)
# with open('./rec_extended_data/def_weights_per_club.pkl', 'wb') as f:
#     pickle.dump(def_weights_per_club, f)
# fullback_weights_per_club = get_pos_weights(fullbacks_df,Fullback_essential_ft)
# with open('./rec_extended_data/fullback_weights_per_club.pkl', 'wb') as f:
#     pickle.dump(fullback_weights_per_club, f)
# gk_weights_per_club = get_pos_weights(gk_df,Gk_essential_ft)
# with open('./rec_extended_data/gk_weights_per_club.pkl', 'wb') as f:
#     pickle.dump(gk_weights_per_club, f)

In [79]:
with open('./rec_extended_data/striker_weights_per_club.pkl', 'rb') as f:
    striker_weights_per_club = pickle.load(f)
with open('./rec_extended_data/wing_weights_per_club.pkl', 'rb') as f:
    wing_weights_per_club = pickle.load(f)
with open('./rec_extended_data/mid_weights_per_club.pkl', 'rb') as f:
    mid_weights_per_club = pickle.load(f)
with open('./rec_extended_data/cam_weights_per_club.pkl', 'rb') as f:
    cam_weights_per_club = pickle.load(f)
with open('./rec_extended_data/def_weights_per_club.pkl', 'rb') as f:
    def_weights_per_club = pickle.load(f)
with open('./rec_extended_data/fullback_weights_per_club.pkl', 'rb') as f:
    fullback_weights_per_club = pickle.load(f)
with open('./rec_extended_data/gk_weights_per_club.pkl', 'rb') as f:
    gk_weights_per_club = pickle.load(f)

In [80]:
def_weights_per_club["Manchester City"]

[0.018194460400936793,
 0.0594368703809399,
 0.12955076619515993,
 0.0,
 0.017439970311683515,
 0.014098389492373327,
 0.014152447948403,
 0.34553191118853094,
 0.21356399259180298,
 0.1880311914901696]

# Common features weights

In [81]:
#common_club_philosophy = get_pos_weights(F_std_df,common_features)

In [82]:
#common_club_philosophy

# Current players in a club weighted rating

Get all current players of a club -  use df_22 as it is the most current season.
Then according to the player's overall rating give them weights and come up with a weighted average for the club.

In [83]:

def get_cur_pos_philosophy(cur_season_df, club , pos_list,pos_essential_ft):# pos list will be ["LW","RW"] for WING
    club_df = cur_season_df[cur_season_df["Club"]==club]
    pos_df=club_df[club_df['Best Position'].isin(pos_list)]
    essential_df = pos_df[pos_essential_ft]
    #print(essential_df)
    cur_players = np.array(essential_df)
    denom=0
    num = np.zeros(shape = (cur_players.shape[1]))
    
    for i in range(cur_players.shape[0]):
        # print(pos_df.iloc[i])
        overall_rating = pos_df.iloc[i]["Ovr_pot"]
        #np.apply_along_axis(my_func, 0, overall_rating)
        
        # print("Overall rating: ", overall_rating)
        
        if(overall_rating >= 85):
            w = 20
        elif (overall_rating >= 80):
            w = 16
        elif(overall_rating >= 75):
            w = 8
        elif(overall_rating >= 70):
            w = 2
        else:
            w = 1
        denom+=w
        num+=w * cur_players[i]
        # print(num)
    
        
        
    if(denom != 0):
        return num/denom
    else: return np.zeros(shape = (cur_players.shape[1]))

In [84]:
# get_cur_pos_philosophy(df_17_std,"Manchester City", ["CB"],Def_essential_ft)

In [85]:
def get_combined_philosophy(cur_season_df, club):
    Def = get_cur_pos_philosophy(cur_season_df,club, ["CB"],Def_essential_ft)
    Gk = get_cur_pos_philosophy(cur_season_df,club, ["GK"],Gk_essential_ft)
    Fb = get_cur_pos_philosophy(cur_season_df,club, ["LB", "RB", "LWB", "RWB"],Fullback_essential_ft)
    Mid = get_cur_pos_philosophy(cur_season_df,club, ["RM", "CM", "CDM", "LM"],Mid_essential_ft)
    cam = get_cur_pos_philosophy(cur_season_df,club, ["CAM"],Cam_essential_ft)
    Wing = get_cur_pos_philosophy(cur_season_df,club, ["LW", "RW"],Wing_essential_ft)
    st = get_cur_pos_philosophy(cur_season_df,club, ["ST", "CF", "LF"],ST_essential_ft)
    return np.concatenate((st,Wing,Mid,cam,Def,Fb,Gk))

In [86]:
# club_phil_17 = {}
# for club in df_17["Club"].unique():
#     club_phil_17[club] = get_combined_philosophy(df_17_std, club)
# with open('./rec_extended_data/club_phil_17.pkl', 'wb') as f:
#     pickle.dump(club_phil_17, f)

# club_phil_18 = {}
# for club in df_18["Club"].unique():
#     club_phil_18[club] = get_combined_philosophy(df_18_std, club)
# with open('./rec_extended_data/club_phil_18.pkl', 'wb') as f:
#     pickle.dump(club_phil_18, f)

# club_phil_19 = {}
# for club in df_19["Club"].unique():
#     club_phil_19[club] = get_combined_philosophy(df_19_std, club)
# with open('./rec_extended_data/club_phil_19.pkl', 'wb') as f:
#     pickle.dump(club_phil_19, f)


# club_phil_20 = {}
# for club in df_20["Club"].unique():
#     club_phil_20[club] = get_combined_philosophy(df_20_std, club)
# with open('./rec_extended_data/club_phil_20.pkl', 'wb') as f:
#     pickle.dump(club_phil_20, f)


# club_phil_21 = {}
# for club in df_21["Club"].unique():
#     club_phil_21[club] = get_combined_philosophy(df_21_std, club)
# with open('./rec_extended_data/club_phil_21.pkl', 'wb') as f:
#     pickle.dump(club_phil_21, f)

# club_phil_22 = {}
# for club in df_22["Club"].unique():
#     club_phil_22[club] = get_combined_philosophy(df_22_std, club)
# with open('./rec_extended_data/club_phil_22.pkl', 'wb') as f:
#     pickle.dump(club_phil_22, f)

In [87]:
with open('./rec_extended_data/club_phil_17.pkl', 'rb') as f:
    club_phil_17 = pickle.load(f)
with open('./rec_extended_data/club_phil_18.pkl', 'rb') as f:
    club_phil_18 = pickle.load(f)
with open('./rec_extended_data/club_phil_19.pkl', 'rb') as f:
    club_phil_19 = pickle.load(f)
with open('./rec_extended_data/club_phil_20.pkl', 'rb') as f:
    club_phil_20 = pickle.load(f)
with open('./rec_extended_data/club_phil_21.pkl', 'rb') as f:
    club_phil_21 = pickle.load(f)
with open('./rec_extended_data/club_phil_22.pkl', 'rb') as f:
    club_phil_22 = pickle.load(f)

In [88]:
club_phil_17["Manchester City"]

array([0.82795699, 0.66666667, 0.67816092, 0.72759857, 0.77777778,
       0.79120879, 0.65277778, 0.80286738, 0.6959707 , 0.81944444,
       0.76966292, 0.79032258, 0.81609195, 0.88709677, 0.86813187,
       0.76388889, 0.76344086, 0.77472527, 0.84895833, 0.75789474,
       0.70804598, 0.75483871, 0.66363636, 0.72087912, 0.59166667,
       0.74408602, 0.69230769, 0.68125   , 0.68842105, 0.64329897,
       0.68539326, 0.72150538, 0.8091954 , 0.78172043, 0.78404255,
       0.80659341, 0.6625    , 0.71978022, 0.71875   , 0.79368421,
       0.78888889, 0.7100894 , 0.67045455, 0.6996337 , 0.70216049,
       0.79669031, 0.78245614, 0.75945017, 0.85103785, 0.82105263,
       0.78651685, 0.65517241, 0.72043011, 0.72727273, 0.78021978,
       0.66666667, 0.8       , 0.75257732, 0.84615385, 0.81052632,
       0.49652778, 0.65740741, 0.75438596, 0.50526316, 0.51202749,
       0.82222222, 0.80952381, 0.78723404, 0.7826087 , 0.80434783])

# Position similarity of a new player

similarity is basically the weighted average of the difference in new_player's attributes and current club players' attributes.

In [89]:


def club_pos_sim_(new_player,club,pos_list,pos_essential_features,pos_weights_per_club):

    new_player = np.array(new_player[pos_essential_features])
    
    #new_player.shape = [new_player.shape[1],]
    # print(new_player.shape)
    # print(new_player)
    
    club_cur  = get_cur_pos_philosophy(F_std_df,club,pos_list,pos_essential_features)
    # print(club_cur)
    weighted_dot = np.sum(pos_weights_per_club[club] * new_player * club_cur)
    # diffs = np.reciprocal(np.square(np.array(new_player - club_cur)))
    # diffs[diffs == inf] = 10
    # #print(diffs)
    # pos_sim = diffs.dot(pos_weights_per_club[club])
    mag_1 = np.sqrt(np.dot(pos_weights_per_club[club], np.square(new_player)))
    mag_2 = np.sqrt(np.dot(pos_weights_per_club[club], np.square(club_cur)))
    pos_sim = weighted_dot/(mag_1 * mag_2)

    return pos_sim

In [90]:
# list = []
# for iter, row in df_22_std.iterrows():
#     if(row["Best Position"] == "CB"):
#         list.append(club_pos_sim_(row, "Manchester City", ["CB"], Def_essential_ft, def_weights_per_club))
# list

In [91]:
# import matplotlib.pyplot as plt
# y = []
# for i in range(0, len(list)):
#     y.append(0)

# from sklearn.preprocessing import MinMaxScaler
# scaler  = MinMaxScaler()
# ar = np.array(list)
# ar.shape = (-1,1)
# l = scaler.fit_transform(ar).tolist()
# plt.scatter(l, y)
# plt.show

In [92]:
# new_player = df_22_std[df_22_std["ID"]==220806]#suarez

# pos_sim = club_pos_sim(new_player,"Manchester United", ["CB"],Def_essential_ft,def_weights_per_club)

In [93]:
# pos_sim

In [94]:
def club_pos_mag(new_player,pos_essential_features,pos_weights_per_club):

    new_player = np.array(new_player[pos_essential_features])

    #new_player.shape = [new_player.shape[1],1]
    mag_1 = np.sqrt(np.dot(pos_weights_per_club, np.square(new_player)))

    return mag_1

In [95]:
# new_player = df_22_std[df_22_std["ID"]==220806]#suarez
# pos_mag = club_pos_mag(new_player,"Manchester United",Def_essential_ft,def_weights_per_club)

In [96]:
# pos_mag

In [97]:
# n_p = np.array(new_player[Def_essential_ft])
# n_p.shape = [13,]
# np.sqrt(np.sum(def_weights_per_club["FC Barcelona"] * np.square(n_p)))

In [98]:
# def get_cur_philosophy(cur_season_df,  club ,common_features):# pos list will be ["LW","RW"] for WING
#     club_df = cur_season_df[cur_season_df["Club"]==club]
#     #pos_df=club_df[club_df['Best Position'].isin(pos_list)]
#     essential_df = club_df[common_features]

#     cur_players = np.array(essential_df)
#     denom=0
#     num = np.zeros(shape = (cur_players.shape[1]))
#     for i in range(cur_players.shape[0]):
#         # print(pos_df.iloc[i])
#         overall_rating = club_df.iloc[i]["Ovr_pot"]
#         #np.apply_along_axis(my_func, 0, overall_rating)
        
#         # print("Overall rating: ", overall_rating)
        
#         if(overall_rating >= 85):
#             w = 20
#         elif (overall_rating >= 80):
#             w = 16
#         elif(overall_rating >= 75):
#             w = 8
#         elif(overall_rating >= 70):
#             w = 2
#         else:
#             w = 1
#         denom+=w
#         num+=w * cur_players[i]
#         # print(num)
    
        
        

#     return num/denom

In [99]:
# get_cur_philosophy(F_std_df, "Manchester City", common_features)

## Similarity with common features/ common club philosophy

In [100]:
# from numpy import inf
# #new_player = df_22[df_22["ID"]==176580]#suarez
# def club_common_sim(new_player,club,common_features, common_club_philosophy):
   
#     new_player = np.array(new_player[common_features])
#     #new_player.shape = [new_player.shape[1],]
#     club_cur  =get_cur_philosophy(F_std_df,club,common_features)
#     #print(np.reciprocal((new_player - club_cur)))
#     diffs = np.reciprocal(np.absolute(np.array(new_player - club_cur)))
#     diffs[diffs == inf] = 1
#     #print(diffs)
#     club_sim = diffs.dot(common_club_philosophy[club])
#     club_sim/=sum(common_club_philosophy[club])

#     return (club_sim)

In [101]:
# common_club_philosophy["Manchester City"]

In [102]:
# new_player = df_22_std[df_22_std["ID"]==239818]

# club_sim = club_common_sim(new_player,"Manchester City",common_features, common_club_philosophy)
# club_sim

In [103]:
# df_22[df_22["ID"]==93155]

In [104]:
# get_cur_philosophy(F_all_df,"Manchester United",common_features)

# Recommendation based on similarity only

In [105]:
# def get_player_recs(df,club,pos_list, pos_essential_features,common_club_features,pos_weights_per_club,lambda1 = 0.685,lambda2 = 0.24, lambda3 = 0.075,k=50):
#     pos_df=df[df['Best Position'].isin(pos_list)]
#     essential_df = pos_df[pos_essential_features]
#     common_club_df = pos_df[common_club_features]
#     d={}
#     player_list = []
#     min_sim = 1
#     max_sim = 0
#     min_mag = 1
#     max_mag = 0
#     sum_sim = 0
#     sum_mag = 0
#     min_club = inf
#     max_club = -inf
#     for i in range(pos_df.shape[0]):
#         new_player = pos_df.iloc[i]
#         pos_sim = club_pos_sim(new_player,club,pos_list,pos_essential_features,pos_weights_per_club)
#         # if(min_sim > pos_sim and pos_sim > 0.8): min_sim = pos_sim
#         if(max_sim < pos_sim): max_sim = pos_sim
#         sum_sim += pos_sim
#         pos_mag = club_pos_mag(new_player,club,pos_essential_features,pos_weights_per_club)
#         # if(min_mag > pos_mag): min_mag = pos_mag
#         if(max_mag < pos_mag): max_mag = pos_mag
#         sum_mag += pos_mag
#         #print(pos_sim, pos_mag)
#         club_sim = club_common_sim(new_player,club,common_club_features, common_club_philosophy)
#         #print(club_sim)
#         if(min_club > club_sim): min_club = club_sim
#         if(max_club < club_sim): max_club = club_sim
#         #sim = lambda1*pos_sim + lambda2*pos_mag
#         d[str(new_player["ID"])] = [pos_sim, pos_mag, club_sim]
#         player_list.append(new_player["ID"])
#     mean_sim = sum_sim/pos_df.shape[0]
#     mean_mag = sum_mag/pos_df.shape[0]
#     dev_sum_sim = 0
#     dev_sum_mag = 0
#     d_final = {}
#     for id in player_list:
#         dev_sum_sim += (d[str(id)][0]- mean_sim)**2
#         dev_sum_mag += (d[str(id)][1]- mean_mag)**2
#     std_sim = math.sqrt(dev_sum_sim/(pos_df.shape[0]-1))
#     std_mag = math.sqrt(dev_sum_mag/(pos_df.shape[0]-1))
#     min_sim = mean_sim - std_sim
#     min_mag = mean_mag - std_mag
#     #print(min_sim, min_mag)
#     for id in player_list:
#         d[str(id)] = [(d[str(id)][0] - min_sim)/(max_sim - min_sim), (d[str(id)][1] - min_mag)/(max_mag - min_mag), (d[str(id)][2] - min_club)/(max_club - min_club)]
#         d_final[str(id)] = lambda1*d[str(id)][0] + lambda2*d[str(id)][1] + lambda3*d[str(id)][2]
#         #print(id, d[str(id)][0], d[str(id)][1])
#     player_list.sort(key = lambda x: d_final[str(x)],reverse = True)
#     new_list = [[df[df["ID"] == j]["Name"], j, d[str(j)]] for j in player_list[:]]
#     return new_list

In [106]:
# get_player_recs(df_22_std,"Manchester United",["CB"],Def_essential_ft,common_features,def_weights_per_club)

In [107]:
# get_player_recs(df_22_std,"Manchester City",["CB"],Def_essential_ft,common_features,def_weights_per_club)

In [108]:
# get_player_recs(df_22_std,"Liverpool",["CB"],Def_essential_ft,common_features,def_weights_per_club)

In [109]:
# get_player_recs(df_22_std,"FC Barcelona",["CB"],Def_essential_ft,common_features,def_weights_per_club)

In [110]:
# df_22[df_22["ID"]==  244749]

In [111]:
# (df_22[df_22["ID"] == 204311]["Ovr_pot"] >= 90).iloc[0]

# Player Improvement Data

In [112]:
def _17_improv_cal(row):
    id = row["ID"]
    if(id in df_18_std["ID"].unique()):
        return (float(df_18_std[df_18_std["ID"]==id]["Ovr_pot"]) - float(row["Ovr_pot"]))
    else:
        return -1000

In [113]:
def _18_improv_cal(row):
    id = row["ID"]
    if(id in df_19_std["ID"].unique()):
        return (float(df_19_std[df_19_std["ID"]==id]["Ovr_pot"]) - float(row["Ovr_pot"]))
    else:
        return -1000

In [114]:
def _19_improv_cal(row):
    id = row["ID"]
    if(id in df_20_std["ID"].unique()):
        return (float(df_20_std[df_20_std["ID"]==id]["Ovr_pot"]) - float(row["Ovr_pot"]))
    else:
        return -1000

In [115]:
def _20_improv_cal(row):
    id = row["ID"]
    if(id in df_21_std["ID"].unique()):
        return (float(df_21_std[df_21_std["ID"]==id]["Ovr_pot"]) - float(row["Ovr_pot"]))
    else:
        return -1000

In [116]:
def _21_improv_cal(row):
    id = row["ID"]
    if(id in df_22_std["ID"].unique()):
        return (float(df_22_std[df_22_std["ID"]==id]["Ovr_pot"]) - float(row["Ovr_pot"]))
    else:
        return -1000

In [117]:
df_17_std["improvement"] = df_17_std.apply(_17_improv_cal, axis = 1)

/var/folders/sq/1c_479xx58d7g62wy3fqmnl80000gn/T/ipykernel_8814/29584130.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_17_std["improvement"] = df_17_std.apply(_17_improv_cal, axis = 1)

In [118]:
df_18_std.assign(improvement=-1000)
df_18_std["improvement"] = df_18_std.apply(_18_improv_cal, axis = 1)

/var/folders/sq/1c_479xx58d7g62wy3fqmnl80000gn/T/ipykernel_8814/2009083908.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_18_std["improvement"] = df_18_std.apply(_18_improv_cal, axis = 1)

In [119]:
df_18_std.improvement

17560      -0.016393
17561      -0.016393
17562      -0.008197
17563      -0.024590
17564      -0.008197
            ...
35482   -1000.000000
35483   -1000.000000
35484   -1000.000000
35485       0.081967
35486   -1000.000000
Name: improvement, Length: 17927, dtype: float64

In [120]:
df_19_std["improvement"] = df_19_std.apply(_19_improv_cal, axis = 1)

/var/folders/sq/1c_479xx58d7g62wy3fqmnl80000gn/T/ipykernel_8814/3976406546.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_19_std["improvement"] = df_19_std.apply(_19_improv_cal, axis = 1)

In [121]:
df_20_std["improvement"] = df_20_std.apply(_20_improv_cal, axis = 1)

/var/folders/sq/1c_479xx58d7g62wy3fqmnl80000gn/T/ipykernel_8814/1293485384.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_20_std["improvement"] = df_20_std.apply(_20_improv_cal, axis = 1)

In [122]:
df_21_std["improvement"] = df_21_std.apply(_21_improv_cal, axis = 1)

/var/folders/sq/1c_479xx58d7g62wy3fqmnl80000gn/T/ipykernel_8814/1861040899.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_21_std["improvement"] = df_21_std.apply(_21_improv_cal, axis = 1)

In [123]:
df_18_std = df_18_std.reset_index(drop = True)
df_17_std = df_17_std.reset_index(drop = True)
df_19_std = df_19_std.reset_index(drop = True)
df_20_std = df_20_std.reset_index(drop = True)
df_21_std = df_21_std.reset_index(drop = True)
df_22_std = df_22_std.reset_index(drop = True)

In [124]:
from numpy import inf
from sklearn.preprocessing import normalize
def club_pos_sim(new_player,pos_weights_per_club, means, club_cur):
    #new_player = np.array(new_player[pos_essential_features])
    new_player.shape = [new_player.shape[0],1]
    new_player = normalize(new_player, axis = 0)
    new_player.shape = [new_player.shape[0],]
    means.shape = [means.shape[0],1]
    means = normalize(means, axis = 0)
    means.shape = [means.shape[0],]
    #print(new_player)
    
    # print(new_player.shape)
    # print(new_player)
    club_cur.shape = [club_cur.shape[0],1]
    club_cur = normalize(club_cur, axis = 0)
    club_cur.shape = [club_cur.shape[0],]
    # print(club_cur)
    weighted_dot = np.sum(pos_weights_per_club * (new_player-means) * (club_cur-means))
    # diffs = np.reciprocal(np.square(np.array(new_player - club_cur)))
    # diffs[diffs == inf] = 10
    # #print(diffs)
    # pos_sim = diffs.dot(pos_weights_per_club[club])
    mag_1 = np.sqrt(np.dot(pos_weights_per_club, np.square(new_player - means)))
    mag_2 = np.sqrt(np.dot(pos_weights_per_club, np.square(club_cur - means)))
    pos_sim = weighted_dot/(mag_1 * mag_2)

    return pos_sim

# Dataset(Def)

In [125]:
def create_pos_dataset(pos_list, pos_essential_features, pos_weights_per_club, slice_start):
    num = 8 * len(pos_essential_features) + 3
    np_dataset = np.empty((0,num))
    feature_list = ["improvement", "Age"] + pos_essential_features


    pos_df_17 = df_17_std[df_17_std["Best Position"].isin(pos_list)]
    pos_df_17 = pos_df_17.reset_index(drop = True)
    means_17 = np.mean(pos_df_17[pos_essential_features].to_numpy(),axis = 0)
    for index, row in pos_df_17.iterrows():
        #new_row = np.concatenate((np.array(row[feature_list].to_list() + def_weights_per_club[row["Club"]] + [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_17, club_phil_17[row["Club"]][20:33])]),club_phil_17[row["Club"]]))
        if(row["improvement"] != -1000):
            club = df_18_std[df_18_std["ID"] == row["ID"]]["Club"].values[0]
            if(club in club_phil_17):
                new_row = np.concatenate((np.array(row[feature_list].to_list()  + [club_pos_sim(np.array(row[pos_essential_features]), pos_weights_per_club[club], means_17, club_phil_17[club][slice_start:slice_start + len(pos_essential_features)])]),club_phil_17[club]))
                new_row.shape = (1,num)
                np_dataset = np.append(np_dataset, new_row, axis = 0)
    
    pos_df_18 = df_18_std[df_18_std["Best Position"].isin(pos_list)]
    pos_df_18 = pos_df_18.reset_index(drop = True)
    means_18 = np.mean(pos_df_18[pos_essential_features].to_numpy(),axis = 0)
    for index, row in pos_df_18.iterrows():
        #new_row = np.concatenate((np.array(row[feature_list].to_list() + def_weights_per_club[row["Club"]] + [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_17, club_phil_17[row["Club"]][20:33])]),club_phil_17[row["Club"]]))
        if(row["improvement"] != -1000):
            club = df_19_std[df_19_std["ID"] == row["ID"]]["Club"].values[0]
            if(club in club_phil_18):
                new_row = np.concatenate((np.array(row[feature_list].to_list()  + [club_pos_sim(np.array(row[pos_essential_features]), pos_weights_per_club[club], means_18, club_phil_18[club][slice_start:slice_start + len(pos_essential_features)])]),club_phil_18[club]))
                new_row.shape = (1,num)
                np_dataset = np.append(np_dataset, new_row, axis = 0)

    pos_df_19 = df_19_std[df_19_std["Best Position"].isin(pos_list)]
    pos_df_19 = pos_df_19.reset_index(drop = True)
    means_19 = np.mean(pos_df_19[pos_essential_features].to_numpy(),axis = 0)
    for index, row in pos_df_19.iterrows():
        #new_row = np.concatenate((np.array(row[feature_list].to_list() + def_weights_per_club[row["Club"]] + [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_17, club_phil_17[row["Club"]][20:33])]),club_phil_17[row["Club"]]))
        if(row["improvement"] != -1000):
            club = df_20_std[df_20_std["ID"] == row["ID"]]["Club"].values[0]
            if(club in club_phil_19):
                new_row = np.concatenate((np.array(row[feature_list].to_list()  + [club_pos_sim(np.array(row[pos_essential_features]), pos_weights_per_club[club], means_19, club_phil_19[club][slice_start:slice_start + len(pos_essential_features)])]),club_phil_19[club]))
                new_row.shape = (1,num)
                np_dataset = np.append(np_dataset, new_row, axis = 0)
        
    pos_df_20 = df_20_std[df_20_std["Best Position"].isin(pos_list)]
    pos_df_20 = pos_df_20.reset_index(drop = True)
    means_20 = np.mean(pos_df_20[pos_essential_features].to_numpy(),axis = 0)
    for index, row in pos_df_20.iterrows():
        #new_row = np.concatenate((np.array(row[feature_list].to_list() + def_weights_per_club[row["Club"]] + [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_17, club_phil_17[row["Club"]][20:33])]),club_phil_17[row["Club"]]))
        if(row["improvement"] != -1000):
            club = df_21_std[df_21_std["ID"] == row["ID"]]["Club"].values[0]
            if(club in club_phil_20):
                new_row = np.concatenate((np.array(row[feature_list].to_list()  + [club_pos_sim(np.array(row[pos_essential_features]), pos_weights_per_club[club], means_20, club_phil_20[club][slice_start:slice_start + len(pos_essential_features)])]),club_phil_20[club]))
                new_row.shape = (1,num)
                np_dataset = np.append(np_dataset, new_row, axis = 0)

    pos_df_21 = df_21_std[df_21_std["Best Position"].isin(pos_list)]
    pos_df_21 = pos_df_21.reset_index(drop = True)
    means_21 = np.mean(pos_df_21[pos_essential_features].to_numpy(),axis = 0)
    for index, row in pos_df_21.iterrows():
        #new_row = np.concatenate((np.array(row[feature_list].to_list() + def_weights_per_club[row["Club"]] + [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_17, club_phil_17[row["Club"]][21:33])]),club_phil_17[row["Club"]]))
        if(row["improvement"] != -1000):
            club = df_22_std[df_22_std["ID"] == row["ID"]]["Club"].values[0]
            if(club in club_phil_21):
                new_row = np.concatenate((np.array(row[feature_list].to_list()  + [club_pos_sim(np.array(row[pos_essential_features]), pos_weights_per_club[club], means_21, club_phil_21[club][slice_start:slice_start + len(pos_essential_features)])]),club_phil_21[club]))
                new_row.shape = (1,num)
                np_dataset = np.append(np_dataset, new_row, axis = 0)
    
    np_dataset = ((np_dataset[~np.isnan(np_dataset).any(axis=1), :]))
    return np_dataset

In [126]:
np_dataset = create_pos_dataset(["CB"], Def_essential_ft, def_weights_per_club, 40)

In [127]:
# def_df_17 = df_17_std[df_17_std["Best Position"].isin(["CB"])]
# def_df_17 = def_df_17.reset_index(drop = True)

In [128]:
# means_17 = np.mean(def_df_17[Def_essential_ft].to_numpy(),axis = 0)
# for index, row in def_df_17.iterrows():
#     feature_list = ["improvement", "Age"] + Def_essential_ft
#     #new_row = np.concatenate((np.array(row[feature_list].to_list() + def_weights_per_club[row["Club"]] + [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_17, club_phil_17[row["Club"]][20:33])]),club_phil_17[row["Club"]]))
#     new_row = np.concatenate((np.array(row[feature_list].to_list()  + [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_17, club_phil_17[row["Club"]][52:65])]),club_phil_17[row["Club"]]))
#     if(new_row[0] != -1000):
#         new_row.shape = (1,107)
#         np_dataset = np.append(np_dataset, new_row, axis = 0)

In [129]:
# def_df_18 = df_18_std[df_18_std["Best Position"].isin(["CB"])]
# def_df_18 = def_df_18.reset_index(drop = True)
# means_18 = np.mean(def_df_18[Def_essential_ft].to_numpy(),axis = 0)
# for index, row in def_df_18.iterrows():
#     feature_list = ["improvement", "Age"] + Def_essential_ft
#     new_row = np.concatenate((np.array(row[feature_list].to_list() + [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_18, club_phil_18[row["Club"]][52:65])]),club_phil_18[row["Club"]]))
#     if(new_row[0] != -1000):
#         new_row.shape = (1,107)
#         np_dataset = np.append(np_dataset, new_row, axis = 0)

In [130]:
# def_df_19 = df_19_std[df_19_std["Best Position"].isin(["CB"])]
# def_df_19 = def_df_19.reset_index(drop = True)
# means_19 = np.mean(def_df_19[Def_essential_ft].to_numpy(),axis = 0)
# for index, row in def_df_19.iterrows():
#     feature_list = ["improvement", "Age"] + Def_essential_ft
#     new_row = np.concatenate((np.array(row[feature_list].to_list()+ [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_19, club_phil_19[row["Club"]][20:33])]),club_phil_19[row["Club"]]))
#     if(new_row[0] != -1000):
#         new_row.shape = (1,107)
#         np_dataset = np.append(np_dataset, new_row, axis = 0)

In [131]:
# def_df_20 = df_20_std[df_20_std["Best Position"].isin(["CB"])]
# def_df_20 = def_df_20.reset_index(drop = True)
# means_20= np.mean(def_df_20[Def_essential_ft].to_numpy(),axis = 0)
# for index, row in def_df_20.iterrows():
#     feature_list = ["improvement", "Age"] + Def_essential_ft
#     new_row = np.concatenate((np.array(row[feature_list].to_list()+ [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_20, club_phil_20[row["Club"]][52:65])]),club_phil_20[row["Club"]]))
#     if(new_row[0] != -1000):
#         new_row.shape = (1,107)
#         np_dataset = np.append(np_dataset, new_row, axis = 0)

In [132]:
# def_df_21 = df_21_std[df_21_std["Best Position"].isin(["CB"])]
# def_df_21 = def_df_21.reset_index(drop = True)
# means_21= np.mean(def_df_21[Def_essential_ft].to_numpy(),axis = 0)
# for index, row in def_df_21.iterrows():
#     feature_list = ["improvement", "Age"] + Def_essential_ft
#     new_row = np.concatenate((np.array(row[feature_list].to_list()+ [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_21, club_phil_21[row["Club"]][52:65])]),club_phil_21[row["Club"]]))
#     if(new_row[0] != -1000):
#         new_row.shape = (1,107)
#         np_dataset = np.append(np_dataset, new_row, axis = 0)

In [133]:
# np_dataset = ((np_dataset[~np.isnan(np_dataset).any(axis=1), :]))

In [134]:
# np.savetxt('values.csv', np_dataset[:,28:29], delimiter=",")

In [135]:
np_dataset.shape

(11132, 83)

In [136]:
np.save("./rec_extended_data/datasets/def.npy", np_dataset)

In [137]:
def create_pred_dataset(pos_list, club, pos_essential_features, pos_weights_per_club, slice_start):
    num = 8 * len(pos_essential_features) + 3
    np_dataset = np.empty((0,num))
    feature_list = ["Age", "Age"] + pos_essential_features

    pos_df_22 = df_22_std[df_22_std["Best Position"].isin(pos_list)]
    pos_df_22 = pos_df_22.reset_index(drop = True)
    means_22 = np.mean(pos_df_22[pos_essential_features].to_numpy(),axis = 0)
    for index, row in pos_df_22.iterrows():
        #new_row = np.concatenate((np.array(row[feature_list].to_list() + def_weights_per_club[row["Club"]] + [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club[row["Club"]], means_17, club_phil_17[row["Club"]][21:33])]),club_phil_17[row["Club"]]))
        new_row = np.concatenate((np.array(row[feature_list].to_list()  + [club_pos_sim(np.array(row[pos_essential_features]), pos_weights_per_club[club], means_22, club_phil_22[club][slice_start:slice_start + len(pos_essential_features)])]),club_phil_22[club]))
        new_row.shape = (1,num)
        np_dataset = np.append(np_dataset, new_row, axis = 0)
    return np_dataset

In [138]:
pred_def = create_pred_dataset(["CB"], "Manchester United", Def_essential_ft, def_weights_per_club, 40)

In [139]:
# def_df_22 = df_22_std[df_22_std["Best Position"].isin(["CB"])]
# def_df_22 = def_df_22.reset_index(drop = True)
# means_22= np.mean(def_df_22[Def_essential_ft].to_numpy(),axis = 0)
# for index, row in def_df_22.iterrows():
#     feature_list = ["Age", "Age"] + Def_essential_ft
#     new_row = np.concatenate((np.array(row[feature_list].to_list()+ [club_pos_sim(np.array(row[Def_essential_ft]), def_weights_per_club["Manchester United"], means_22, club_phil_22["Manchester United"][52:65])]),club_phil_22["Manchester United"]))
#     if(new_row[0] != -1000):
#         new_row.shape = (1,107)
#         pred_def = np.append(pred_def, new_row, axis = 0)

In [140]:
np.save("./rec_extended_data/datasets/preds/utd_def.npy", pred_def)

In [141]:
city_preds_def = np.load("./rec_extended_data/datasets/res/pred_city.npy")

In [142]:
city_preds_def.shape

(3214,)

In [143]:
utd_preds_def = np.load("./rec_extended_data/datasets/res/pred_utd.npy")

In [144]:
def get_player_recs(df,club, preds, pos_list, pos_essential_features,pos_weights_per_club,lambda1 = 0.36,lambda2 = 0.64, age_min = 21, age_max = 29, val = 60):
    pos_df=df[df['Best Position'].isin(pos_list)]
    essential_df = pos_df[pos_essential_features]
    # common_club_df = pos_df[common_club_features]
    d={}
    player_list = []
    min_imp = inf
    max_imp = -inf
    min_mag = inf
    max_mag = -inf
    #sum_sim = 0
    #sum_mag = 0
    # min_club = inf
    # max_club = -inf
    # pos_np = essential_df.to_numpy()
    # pos_np = normalize(pos_np)
    # means = np.mean(pos_np, axis = 0)
    # club_cur  = get_cur_pos_philosophy(F_std_df,club,pos_list,pos_essential_features)
    for i in range(pos_df.shape[0]):
        new_player = pos_df.iloc[i]
        pos_imp = preds[i]
        if(min_imp > pos_imp): min_imp = pos_imp
        if(max_imp < pos_imp): max_imp = pos_imp
        #sum_sim += pos_sim
        pos_mag = club_pos_mag(new_player,pos_essential_features,pos_weights_per_club[club])
        if(min_mag > pos_mag): min_mag = pos_mag
        if(max_mag < pos_mag): max_mag = pos_mag
        #sum_mag += pos_mag
        #print(pos_sim, pos_mag)
        #club_sim = club_common_sim(new_player,club,common_club_features, common_club_philosophy)
        #print(club_sim)
        # if(min_club > club_sim): min_club = club_sim
        # if(max_club < club_sim): max_club = club_sim
        #sim = lambda1*pos_sim + lambda2*pos_mag
        d[str(new_player["ID"])] = [pos_imp, pos_mag]
        player_list.append(new_player["ID"])
    # mean_sim = sum_sim/pos_df.shape[0]
    # mean_mag = sum_mag/pos_df.shape[0]
    # dev_sum_sim = 0
    # dev_sum_mag = 0
    d_final = {}
    # for id in player_list:
    #     dev_sum_sim += (d[str(id)][0]- mean_sim)**2
    #     dev_sum_mag += (d[str(id)][1]- mean_mag)**2
    # std_sim = math.sqrt(dev_sum_sim/(pos_df.shape[0]-1))
    # std_mag = math.sqrt(dev_sum_mag/(pos_df.shape[0]-1))
    # min_sim = mean_sim - std_sim
    # min_mag = mean_mag - std_mag
    #print(min_sim, min_mag)
    for id in player_list:
        neg = (d[str(id)][0] < 0)
        d[str(id)] = [(d[str(id)][0] - min_imp)/(max_imp - min_imp), (d[str(id)][1] - min_mag)/(max_mag - min_mag)]
        d_final[str(id)] = lambda1*d[str(id)][0] + lambda2*d[str(id)][1]
        if(neg):
            d_final[str(id)] = -100
        #print(id, d[str(id)][0], d[str(id)][1])
    player_list.sort(key = lambda x: d_final[str(x)],reverse = True)
    new_list = [[df[df["ID"] == j]["Name"],j, d[str(j)]] for j in player_list[:] if ((float(df_22[df_22["ID"] == j]["Age"]) >= age_min) and (float(df_22[df_22["ID"] == j]["Age"]) <= age_max) and (float(df[df["ID"] == j]["Value"]) <= val) and ((df[df["ID"] == j]["Club"].values[0] != club)))]
    return new_list

In [145]:
get_player_recs(df_22_std, "Manchester City", city_preds_def, ["CB"], Def_essential_ft, def_weights_per_club)

[[260    Melvin Parrela
  Name: Name, dtype: object,
  230251,
  [0.13365203, 0.8131611145576949]],
 [2921    E. Ndicka
  Name: Name, dtype: object,
  236403,
  [0.1503894, 0.7933783022867561]],
 [108    W. McKennie
  Name: Name, dtype: object,
  238744,
  [0.14652875, 0.7918698400921919]],
 [6698    M. Lacroix
  Name: Name, dtype: object,
  244067,
  [0.1503894, 0.7879596197497262]],
 [6893    S. Botman
  Name: Name, dtype: object,
  251809,
  [0.13250393, 0.7847759576196375]],
 [7930    A. Ahmedhodžić
  Name: Name, dtype: object,
  236524,
  [0.22306746, 0.7308330752407856]],
 [7781    O. Kabak
  Name: Name, dtype: object,
  239890,
  [0.1749507, 0.750266114800034]],
 [5755    Z. Vanheusden
  Name: Name, dtype: object,
  241103,
  [0.17682274, 0.7491684928128304]],
 [3735    M. Bešić
  Name: Name, dtype: object,
  200765,
  [0.17128369, 0.751883145468019]],
 [9239    21 A. Wisdom
  Name: Name, dtype: object,
  201908,
  [0.33821517, 0.6555144968990924]],
 [4484    Antônio Chiamuloira
  Name: Name, dtype: object,
  230212,
  [0.1503894, 0.7589457535416102]],
 [9069    I. Diveev
  Name: Name, dtype: object,
  245703,
  [0.16692829, 0.7475156417588276]],
 [4855    P. Hatzidiakos
  Name: Name, dtype: object,
  229150,
  [0.310007, 0.6659174474477016]],
 [2765    M. Sarr
  Name: Name, dtype: object,
  235454,
  [0.17226511, 0.7389771400078295]],
 [11768    R. Mina
  Name: Name, dtype: object,
  254173,
  [0.63186127, 0.4793372065950318]],
 [4923    Bruno Fuchs
  Name: Name, dtype: object,
  258370,
  [0.2116166, 0.7137770184232711]],
 [6959    P. Sandler
  Name: Name, dtype: object,
  234679,
  [0.2267035, 0.702039578954722]],
 [5245    Diego Llorente
  Name: Name, dtype: object,
  212602,
  [0.15486711, 0.739703438106363]],
 [5428    J. Todibo
  Name: Name, dtype: object,
  245388,
  [0.13643989, 0.750034426575661]],
 [7507    Rafael Cachoira
  Name: Name, dtype: object,
  230528,
  [0.17420754, 0.7283718893896785]],
 [2639    L. Krejčí
  Name: Name, dtype: object,
  252064,
  [0.22306746, 0.7000342683572011]],
 [7580    Osvaldão Murilo
  Name: Name, dtype: object,
  230215,
  [0.22153202, 0.7004422322677839]],
 [8423    S. Marković
  Name: Name, dtype: object,
  252551,
  [0.2564685, 0.6802185043147658]],
 [6298    Tomás Podstawski
  Name: Name, dtype: object,
  216449,
  [0.32882613, 0.6365199689146769]],
 [4143    Y. Ndayishimiye
  Name: Name, dtype: object,
  255533,
  [0.2824524, 0.6625111342429127]],
 [1128    20 S. Wuytens
  Name: Name, dtype: object,
  188416,
  [0.14614655, 0.7378606821064461]],
 [8395    P. Struijk
  Name: Name, dtype: object,
  239360,
  [0.17380258, 0.7218168915992499]],
 [6993    M. Lemos
  Name: Name, dtype: object,
  229270,
  [0.3288653, 0.6321030453681996]],
 [4924    C. Montes
  Name: Name, dtype: object,
  229980,
  [0.12547247, 0.7438923465265382]],
 [6662    J. Rodríguez
  Name: Name, dtype: object,
  244950,
  [0.17128369, 0.7171959064410345]],
 [5573    20 Renato Neto
  Name: Name, dtype: object,
  199663,
  [0.28396383, 0.653536453234227]],
 [6868    A. Frías
  Name: Name, dtype: object,
  251886,
  [0.15833789, 0.7241311501190522]],
 [4047    S. Denswil
  Name: Name, dtype: object,
  205756,
  [0.15670455, 0.7250268511689917]],
 [4280    19 M. Kosanović
  Name: Name, dtype: object,
  200073,
  [0.14614655, 0.7304850678570529]],
 [13224    19 C. Torres
  Name: Name, dtype: object,
  222647,
  [0.6317014, 0.45705890446353403]],
 [5540    S. Bornauw
  Name: Name, dtype: object,
  242663,
  [0.14652875, 0.7283678530880541]],
 [4228    21 J. Rodwell
  Name: Name, dtype: object,
  183465,
  [0.32230267, 0.6294099973097836]],
 [5109    Nolaskoain
  Name: Name, dtype: object,
  241489,
  [0.25250462, 0.6681411738055884]],
 [3362    Ailton Valpaços
  Name: Name, dtype: object,
  230222,
  [0.14962207, 0.7259741015319362]],
 [8784    J. Souttar
  Name: Name, dtype: object,
  212516,
  [0.29252416, 0.6453981059277746]],
 [6620    M. Simakan
  Name: Name, dtype: object,
  243854,
  [0.14854673, 0.7260451807550536]],
 [1973    P. Schuurs
  Name: Name, dtype: object,
  241854,
  [0.1676961, 0.7152674870020632]],
 [9405    Davi Parrela
  Name: Name, dtype: object,
  230388,
  [0.17535566, 0.7082665880835128]],
 [11760    D. Maresic
  Name: Name, dtype: object,
  235673,
  [0.2038327, 0.6904454496916392]],
 [5371    20 B. Sarr
  Name: Name, dtype: object,
  213537,
  [0.27716294, 0.6473821290114196]],
 [2239    D. Martínez
  Name: Name, dtype: object,
  241569,
  [0.12547247, 0.7322752725726464]],
 [3745    J. Teze
  Name: Name, dtype: object,
  245211,
  [0.17682274, 0.7030392015285721]],
 [7140    I. Drešević
  Name: Name, dtype: object,
  235519,
  [0.30256554, 0.6312713220485016]],
 [3852    A. Barboza
  Name: Name, dtype: object,
  229749,
  [0.17128369, 0.7043523720016756]],
 [5614    T. Kongolo
  Name: Name, dtype: object,
  203485,
  [0.2232033, 0.6748380626432895]],
 [4957    Mingueza
  Name: Name, dtype: object,
  259694,
  [0.14652875, 0.7152432317334577]],
 [11319    L. Badé
  Name: Name, dtype: object,
  255106,
  [0.1732911, 0.7000226524068665]],
 [5165    V. Nelsson
  Name: Name, dtype: object,
  235658,
  [0.21795395, 0.6747315463907411]],
 [9831    S. Caulker
  Name: Name, dtype: object,
  193504,
  [0.16504896, 0.7027625817279558]],
 [6201    Tuta
  Name: Name, dtype: object,
  247182,
  [0.18292566, 0.6917579115895661]],
 [5451    21 A. Wakaso
  Name: Name, dtype: object,
  200773,
  [0.29606357, 0.6280624885586981]],
 [7855    S. Nsoki
  Name: Name, dtype: object,
  241941,
  [0.28148407, 0.6359218413628184]],
 [10941    Alexandre Frandeira
  Name: Name, dtype: object,
  230390,
  [0.22843972, 0.6645697264435447]],
 [14208    P. Bochniewicz
  Name: Name, dtype: object,
  220230,
  [0.24264571, 0.6562625939417314]],
 [8258    J. Duverne
  Name: Name, dtype: object,
  229705,
  [0.2232033, 0.6665398191263768]],
 [9441    M. Trapp
  Name: Name, dtype: object,
  200475,
  [0.29349247, 0.6269578938601]],
 [4065    Kelivelson
  Name: Name, dtype: object,
  230452,
  [0.16017532, 0.7016756975953529]],
 [12185    A. Mawson
  Name: Name, dtype: object,
  208534,
  [0.24264571, 0.6551193073970009]],
 [3219    R. Rojas
  Name: Name, dtype: object,
  246914,
  [0.20191336, 0.6778443657451638]],
 [4277    B. Rovira
  Name: Name, dtype: object,
  225812,
  [0.24361405, 0.654287903938989]],
 [7324    21 D. Lischka
  Name: Name, dtype: object,
  251181,
  [0.23621938, 0.6582413090774989]],
 [5375    J. Rassoul
  Name: Name, dtype: object,
  229064,
  [0.2695603, 0.6391792323624629]],
 [8663    D. Doekhi
  Name: Name, dtype: object,
  232658,
  [0.2269272, 0.6622452433330958]],
 [12117    S. van Beek
  Name: Name, dtype: object,
  213000,
  [0.2232033, 0.663845579623313]],
 [5995    Tiago Djaló
  Name: Name, dtype: object,
  252339,
  [0.17380258, 0.6892909855281897]],
 [13066    N. Pérez
  Name: Name, dtype: object,
  244206,
  [0.17380258, 0.6867097432216333]],
 [9722    C. Cuesta
  Name: Name, dtype: object,
  233841,
  [0.22306746, 0.6581789197441115]],
 [8481    B. Tuiloma
  Name: Name, dtype: object,
  220886,
  [0.30943993, 0.6089765406115981]],
 [7139    A. Pelmard
  Name: Name, dtype: object,
  247412,
  [0.25564715, 0.6383891550786914]],
 [4196    M. Wöber
  Name: Name, dtype: object,
  231838,
  [0.14295767, 0.7014176065005328]],
 [6136    F. Medina
  Name: Name, dtype: object,
  236804,
  [0.14652875, 0.699116115969368]],
 [6936    21 B. Kuscevic
  Name: Name, dtype: object,
  225236,
  [0.18772441, 0.6759204483497988]],
 [10843    N. Maraš
  Name: Name, dtype: object,
  241070,
  [0.22727868, 0.6535600600013372]],
 [6912    N. Bitton
  Name: Name, dtype: object,
  206317,
  [0.17912798, 0.6806251564883636]],
 [5449    Saberto Botelho
  Name: Name, dtype: object,
  230531,
  [0.1939831, 0.6720115731526355]],
 [12121    L. Kilian
  Name: Name, dtype: object,
  248878,
  [0.26361924, 0.6326376871212104]],
 [9747    Fabiano Sonta
  Name: Name, dtype: object,
  230218,
  [0.15486711, 0.6931435952944336]],
 [6535    V. Vevatne
  Name: Name, dtype: object,
  214650,
  [0.32962224, 0.5947911526872061]],
 [6471    M. Heyer
  Name: Name, dtype: object,
  238593,
  [0.2269272, 0.6521611638071197]],
 [13039    J. Whatmough
  Name: Name, dtype: object,
  211166,
  [0.3288653, 0.5947118225698499]],
 [3393    Teixe Gaúcho
  Name: Name, dtype: object,
  230322,
  [0.23048255, 0.649157138068538]],
 [8733    Juli Freitinho
  Name: Name, dtype: object,
  230224,
  [0.19802208, 0.6673913422630919]],
 [11269    S. Walukiewicz
  Name: Name, dtype: object,
  243497,
  [0.1930599, 0.6700490667646206]],
 [4097    J. Bijol
  Name: Name, dtype: object,
  244238,
  [0.2926543, 0.6138577040971239]],
 [9910    L. Štetina
  Name: Name, dtype: object,
  240034,
  [0.17801888, 0.6781319060790437]],
 [9204    J. Gnagnon
  Name: Name, dtype: object,
  231361,
  [0.12547247, 0.7072520072779265]],
 [10879    21 G. Conti
  Name: Name, dtype: object,
  221219,
  [0.17128369, 0.6814417216885369]],
 [9476    Pablo Iñiguez
  Name: Name, dtype: object,
  206546,
  [0.3355404, 0.5883030588613476]],
 [8727    21 M. Zaldivia
  Name: Name, dtype: object,
  215053,
  [0.15762302, 0.6882181199532621]],
 [13973    J. Elliott
  Name: Name, dtype: object,
  238008,
  [0.17475447, 0.6785789013246785]],
 [10411    W. Faes
  Name: Name, dtype: object,
  235036,
  [0.12797357, 0.7043405789449841]],
 [8676    17 A. Tamata
  Name: Name, dtype: object,
  202153,
  [0.328209, 0.5916299005682143]],
 [7052    A. Obispo
  Name: Name, dtype: object,
  241171,
  [0.29526776, 0.6101500626618749]],
 [11813    Clemente
  Name: Name, dtype: object,
  244394,
  [0.2868328, 0.6147902627730959]],
 [12077    S. Agouzoul
  Name: Name, dtype: object,
  251751,
  [0.32589832, 0.5927481223738699]],
 [9601    T. Deng
  Name: Name, dtype: object,
  228310,
  [0.3933906, 0.5547375398126021]],
 [6810    Jorge Sáenz
  Name: Name, dtype: object,
  225106,
  [0.23552011, 0.6429061340259249]],
 [5381    20 Marc Muniesa
  Name: Name, dtype: object,
  192766,
  [0.15486711, 0.6881589583367088]],
 [11400    J. Lawrence
  Name: Name, dtype: object,
  245768,
  [0.2269272, 0.6472194004623018]],
 [12072    H. Marcelin
  Name: Name, dtype: object,
  242603,
  [0.2584364, 0.6294157779220779]],
 [5786    21 L. Spendlhofer
  Name: Name, dtype: object,
  208247,
  [0.33957192, 0.5836431581133955]],
 [5986    C. Jullien
  Name: Name, dtype: object,
  208615,
  [0.1271093, 0.7029460473781404]],
 [11183    C. Starfelt
  Name: Name, dtype: object,
  220821,
  [0.23552011, 0.6416773442565809]],
 [8000    A. Ndom
  Name: Name, dtype: object,
  231109,
  [0.39600286, 0.5513349851446724]],
 [3494    K. Piątkowski
  Name: Name, dtype: object,
  252018,
  [0.22843972, 0.6455511607692126]],
 [9162    M. Clarke
  Name: Name, dtype: object,
  221600,
  [0.17271163, 0.6768852368502649]],
 [3871    Patrick William
  Name: Name, dtype: object,
  252150,
  [0.2269272, 0.6462614684134711]],
 [6882    J. Bruma
  Name: Name, dtype: object,
  195363,
  [0.16924085, 0.6783191442342293]],
 [9775    J. Elvedi
  Name: Name, dtype: object,
  256705,
  [0.29252416, 0.6084553726892824]],
 [9286    F. Benković
  Name: Name, dtype: object,
  244269,
  [0.1626436, 0.6809078577259857]],
 [8320    Alson Botelho
  Name: Name, dtype: object,
  230253,
  [0.2026326, 0.658118362638745]],
 [10360    F. Garcés
  Name: Name, dtype: object,
  241031,
  [0.22183545, 0.6471310012915877]],
 [8847    Diego González
  Name: Name, dtype: object,
  227106,
  [0.25859892, 0.6260597317151401]],
 [10554    20 M. Capuano
  Name: Name, dtype: object,
  201529,
  [0.19457954, 0.6618365489978123]],
 [1052    19 D. Williams
  Name: Name, dtype: object,
  198194,
  [0.17598633, 0.6722833714942357]],
 [13094    21 P. Gouano
  Name: Name, dtype: object,
  204886,
  [0.2624792, 0.6234629649679809]],
 [4570    D. Hovorka
  Name: Name, dtype: object,
  240033,
  [0.124244064, 0.7011207253522983]],
 [12989    S. Fortes
  Name: Name, dtype: object,
  219582,
  [0.29252416, 0.6060535518270475]],
 [10161    H. Delcroix
  Name: Name, dtype: object,
  237440,
  [0.16313848, 0.6786274767468539]],
 [7723    L. Balerdi
  Name: Name, dtype: object,
  242835,
  [0.14836618, 0.6857684873779331]],
 [9348    A. Trusty
  Name: Name, dtype: object,
  235755,
  [0.32787707, 0.5847132493834243]],
 [8681    J. Rasmussen
  Name: Name, dtype: object,
  234827,
  [0.16304055, 0.677366007174289]],
 [8112    Pol García
  Name: Name, dtype: object,
  211323,
  [0.2269272, 0.6412599503891749]],
 [6739    T. Chalobah
  Name: Name, dtype: object,
  230918,
  [0.183563, 0.6656013649997325]],
 [11621    S. Welsh
  Name: Name, dtype: object,
  255573,
  [0.27997193, 0.6112574092614912]],
 [10607    K. Djidji
  Name: Name, dtype: object,
  203884,
  [0.15762302, 0.6798027012153693]],
 [2052    D. Kohr
  Name: Name, dtype: object,
  212212,
  [0.12670437, 0.6971642877382047]],
 [10964    M. McKenzie
  Name: Name, dtype: object,
  242195,
  [0.16885671, 0.6731636794686358]],
 [5162    G. Michailidis
  Name: Name, dtype: object,
  253136,
  [0.24429868, 0.6303917550645243]],
 [5059    T. Kolodziejczak
  Name: Name, dtype: object,
  190034,
  [0.15956978, 0.6773337736306336]],
 [2631    Gregore
  Name: Name, dtype: object,
  251410,
  [0.13365175, 0.6917292233790575]],
 [8287    G. Shoji
  Name: Name, dtype: object,
  232869,
  [0.1614072, 0.675682022507427]],
 [10872    F. Gattoni
  Name: Name, dtype: object,
  241930,
  [0.2723574, 0.6132476092504285]],
 [8934    I. Nedelcearu
  Name: Name, dtype: object,
  242614,
  [0.17271163, 0.6687957508999075]],
 [9463    L. Moore
  Name: Name, dtype: object,
  200758,
  [0.27716294, 0.6099228781641811]],
 [14605    A. Sylla
  Name: Name, dtype: object,
  256743,
  [0.65865564, 0.395193714039648]],
 [10198    F. Kunze
  Name: Name, dtype: object,
  251429,
  [0.18772441, 0.6595094029081799]],
 [8561    K. Adams Nuhu
  Name: Name, dtype: object,
  225673,
  [0.18521117, 0.6608900335113944]],
 [8544    S. Beukema
  Name: Name, dtype: object,
  262394,
  [0.25250462, 0.6230067794600419]],
 [10035    S. Findlay
  Name: Name, dtype: object,
  227945,
  [0.3449439, 0.5710032920787698]],
 [1736    M. Tisserand
  Name: Name, dtype: object,
  216247,
  [0.1614072, 0.6742283004564954]],
 [12564    T. Watanabe
  Name: Name, dtype: object,
  246826,
  [0.3466775, 0.5696980445764132]],
 [5126    A. Long
  Name: Name, dtype: object,
  222123,
  [0.1332468, 0.6895834384276345]],
 [7212    Vanderleiton
  Name: Name, dtype: object,
  230407,
  [0.18359782, 0.6611110196178156]],
 [12062    E. Segura
  Name: Name, dtype: object,
  237245,
  [0.22058986, 0.6402645087679842]],
 [11491    N. Röseler
  Name: Name, dtype: object,
  205045,
  [0.25712118, 0.619387247347855]],
 [4254    J. Fulton
  Name: Name, dtype: object,
  221890,
  [0.12828638, 0.6909702659810747]],
 [14930    A. Cissoko
  Name: Name, dtype: object,
  262781,
  [0.6657085, 0.3886562891463358]],
 [10247    I. Cristea
  Name: Name, dtype: object,
  248021,
  [0.1986549, 0.6509623427245602]],
 [8886    Vivian
  Name: Name, dtype: object,
  248550,
  [0.21979262, 0.638960482507753]],
 [4535    M. de los Santos
  Name: Name, dtype: object,
  239645,
  [0.17331623, 0.6648284587067242]],
 [12897    R. Jansson
  Name: Name, dtype: object,
  203137,
  [0.23551217, 0.6297099422701025]],
 [8092    21 J. Flanagan
  Name: Name, dtype: object,
  201999,
  [0.27798447, 0.6056926210656424]],
 [5603    20 U. Agbo
  Name: Name, dtype: object,
  226289,
  [0.25478303, 0.6185239565762566]],
 [5911    M. Niakhaté
  Name: Name, dtype: object,
  225859,
  [0.13017514, 0.6883920071911854]],
 [12361    S. Babić
  Name: Name, dtype: object,
  235589,
  [0.27046826, 0.6093999218751603]],
 [7733    19 C. M'Bengue
  Name: Name, dtype: object,
  183395,
  [0.27119857, 0.608804071468027]],
 [2343    K. Amian
  Name: Name, dtype: object,
  231235,
  [0.1488998, 0.6773867464059584]],
 [12188    D. Bain
  Name: Name, dtype: object,
  208019,
  [0.2564294, 0.616895226325941]],
 [6569    Marlon
  Name: Name, dtype: object,
  215703,
  [0.16099772, 0.6702749949985375]],
 [6579    G. Kalulu
  Name: Name, dtype: object,
  238391,
  [0.27672198, 0.6049292603459461]],
 [7549    W. Zimmerman
  Name: Name, dtype: object,
  212591,
  [0.15670455, 0.6723446156695481]],
 [11533    A. Callens
  Name: Name, dtype: object,
  211522,
  [0.1614072, 0.6696916770281475]],
 [9996    J. Tverskov
  Name: Name, dtype: object,
  224067,
  [0.24665722, 0.6217379994119407]],
 [908    19 T. Doumbia
  Name: Name, dtype: object,
  192767,
  [0.15670455, 0.672010378636862]],
 [4257    H. Choudhury
  Name: Name, dtype: object,
  228332,
  [0.1350912, 0.6839684481096637]],
 [12805    E. Bergström
  Name: Name, dtype: object,
  202060,
  [0.2867105, 0.598488689641647]],
 [7980    M. Lode
  Name: Name, dtype: object,
  242160,
  [0.22058986, 0.6352147356397969]],
 [11120    Pombaxinho
  Name: Name, dtype: object,
  230383,
  [0.16327506, 0.6672689804273225]],
 [12390    Montero
  Name: Name, dtype: object,
  244938,
  [0.20916954, 0.6414057443804406]],
 [12898    M. Miazga
  Name: Name, dtype: object,
  215565,
  [0.15833789, 0.6699961567630418]],
 [12895    A. Shabanov
  Name: Name, dtype: object,
  244381,
  [0.22058986, 0.6348184085110252]],
 [7967    19 Maurício
  Name: Name, dtype: object,
  187324,
  [0.19362524, 0.6497620354857188]],
 [11043    C. González
  Name: Name, dtype: object,
  236020,
  [0.29222152, 0.5942652771096171]],
 [11108    A. Theate
  Name: Name, dtype: object,
  257278,
  [0.27997193, 0.6011497295320911]],
 [6999    T. Kalas
  Name: Name, dtype: object,
  201122,
  [0.14859362, 0.6749869084535279]],
 [9742    M. Rose
  Name: Name, dtype: object,
  212487,
  [0.24264571, 0.6220304717954921]],
 [4942    J. Tanganga
  Name: Name, dtype: object,
  236600,
  [0.14652875, 0.6760229852209474]],
 [6104    V. Lekhal
  Name: Name, dtype: object,
  213841,
  [0.27223507, 0.6047584856924911]],
 [8926    J. Beyer
  Name: Name, dtype: object,
  242660,
  [0.22689174, 0.6301912882270161]],
 [9039    21 F. Dagerstål
  Name: Name, dtype: object,
  224838,
  [0.2269272, 0.6299696111042448]],
 [1986    P. Díaz
  Name: Name, dtype: object,
  214436,
  [0.15956978, 0.6677329271766639]],
 [13792    C. Zimmermann
  Name: Name, dtype: object,
  239322,
  [0.1546617, 0.6703482306333973]],
 [6218    L. Valenti
  Name: Name, dtype: object,
  246164,
  [0.23621938, 0.6239275117762775]],
 [6355    T. Tomiyasu
  Name: Name, dtype: object,
  232938,
  [0.15846977, 0.667611099362626]],
 [11771    J. Thorniley
  Name: Name, dtype: object,
  229349,
  [0.3446674, 0.5628066809073472]],
 [13707    M. Pineda
  Name: Name, dtype: object,
  255273,
  [0.34929347, 0.5601671487091072]],
 [14265    R. Tongyik
  Name: Name, dtype: object,
  231678,
  [0.4230258, 0.5184953299216244]],
 [13227    N. Ferraresi
  Name: Name, dtype: object,
  246388,
  [0.2151415, 0.6353036328079674]],
 [7329    O. Solet
  Name: Name, dtype: object,
  242238,
  [0.21487527, 0.635358873750423]],
 [9084    T. St. Jago
  Name: Name, dtype: object,
  253376,
  [0.21487527, 0.6353041443501793]],
 [2712    T. Fosu-Mensah
  Name: Name, dtype: object,
  232270,
  [0.14699665, 0.6734300463951067]],
 [4303    R. Bauer
  Name: Name, dtype: object,
  223765,
  [0.17128369, 0.6597641663594157]],
 [10372    C. Richards
  Name: Name, dtype: object,
  250954,
  [0.22265741, 0.630308132974074]],
 [7040    A. Toșca
  Name: Name, dtype: object,
  233512,
  [0.2407109, 0.6199630072227288]],
 [12223    F. Romagna
  Name: Name, dtype: object,
  226108,
  [0.2269272, 0.627688464549746]],
 [14346    David Carmo
  Name: Name, dtype: object,
  251616,
  [0.15153752, 0.6700683275699952]],
 [6806    L. Kelly
  Name: Name, dtype: object,
  231512,
  [0.25286028, 0.6128524389539766]],
 [11776    D. Popov
  Name: Name, dtype: object,
  245132,
  [0.21554644, 0.6337936159440607]],
 [11107    L. Lacroix
  Name: Name, dtype: object,
  199895,
  [0.24332266, 0.6180796724227464]],
 [12745    Alex Nascimento

In [148]:
get_player_recs(df_22_std, "Manchester United", utd_preds_def, ["CB"], Def_essential_ft, def_weights_per_club)

[[2198    J. Koundé
  Name: Name, dtype: object,
  241486,
  [0.14734623, 0.8456802845616925]],
 [2197    E. Tapsoba
  Name: Name, dtype: object,
  247263,
  [0.14734623, 0.8372789891561496]],
 [1905    Diego Carlos
  Name: Name, dtype: object,
  219693,
  [0.14566725, 0.8332290490371683]],
 [5245    Diego Llorente
  Name: Name, dtype: object,
  212602,
  [0.21598636, 0.7849271418335361]],
 [4872    A. Bastoni
  Name: Name, dtype: object,
  237383,
  [0.14734623, 0.8221312616632763]],
 [2639    L. Krejčí
  Name: Name, dtype: object,
  252064,
  [0.24949127, 0.7516968016188591]],
 [4484    Antônio Chiamuloira
  Name: Name, dtype: object,
  230212,
  [0.171362, 0.7919923925741783]],
 [260    Melvin Parrela
  Name: Name, dtype: object,
  230251,
  [0.14753595, 0.7971189177883102]],
 [108    W. McKennie
  Name: Name, dtype: object,
  238744,
  [0.18753427, 0.7723227551545985]],
 [6019    Lucas Veríssimo
  Name: Name, dtype: object,
  235688,
  [0.14566725, 0.7927007759471565]],
 [3617    T. Mings
  Name: Name, dtype: object,
  212419,
  [0.14566725, 0.7906111778459525]],
 [578    R. Bensebaini
  Name: Name, dtype: object,
  224196,
  [0.14566725, 0.787605591032129]],
 [10893    Y. Gómez Andrade
  Name: Name, dtype: object,
  224396,
  [0.19337907, 0.760527448015771]],
 [1951    E. Álvarez
  Name: Name, dtype: object,
  235844,
  [0.1524964, 0.7775594166559227]],
 [253    T. Holeš
  Name: Name, dtype: object,
  251116,
  [0.14566725, 0.7786308741930253]],
 [3852    A. Barboza
  Name: Name, dtype: object,
  229749,
  [0.22134042, 0.7344032652254256]],
 [5774    L. Dunk
  Name: Name, dtype: object,
  199915,
  [0.14566725, 0.7762279171157817]],
 [1986    P. Díaz
  Name: Name, dtype: object,
  214436,
  [0.22149009, 0.7335694077618332]],
 [6755    D. Ćaleta-Car
  Name: Name, dtype: object,
  225263,
  [0.14566725, 0.775772096072569]],
 [2386    A. Diallo
  Name: Name, dtype: object,
  225711,
  [0.14566725, 0.7748677476894841]],
 [7172    Luiz Felipe
  Name: Name, dtype: object,
  236355,
  [0.1670937, 0.7611410564261]],
 [6893    S. Botman
  Name: Name, dtype: object,
  251809,
  [0.14619227, 0.7722248998077773]],
 [9941    D. Zagadou
  Name: Name, dtype: object,
  238476,
  [0.14734623, 0.7685715953684034]],
 [6698    M. Lacroix
  Name: Name, dtype: object,
  244067,
  [0.171362, 0.7547048972847953]],
 [7822    I. Konaté
  Name: Name, dtype: object,
  237678,
  [0.14734623, 0.7672432805809275]],
 [3961    S. Mustafi
  Name: Name, dtype: object,
  192227,
  [0.23741278, 0.7165266451111049]],
 [6916    David García
  Name: Name, dtype: object,
  225341,
  [0.15117098, 0.7646555770874703]],
 [9226    Ferro
  Name: Name, dtype: object,
  242236,
  [0.14566725, 0.7672499333728127]],
 [7796    R. Araujo
  Name: Name, dtype: object,
  253163,
  [0.14734623, 0.7621140442280476]],
 [5540    S. Bornauw
  Name: Name, dtype: object,
  242663,
  [0.18753427, 0.738809344067171]],
 [5069    S. Gigot
  Name: Name, dtype: object,
  219581,
  [0.15117098, 0.7546575519800632]],
 [5320    F. Calvo
  Name: Name, dtype: object,
  213064,
  [0.32638583, 0.6559768083887934]],
 [5831    J. Andersen
  Name: Name, dtype: object,
  224221,
  [0.14566725, 0.7537393550242791]],
 [7467    Vallejo
  Name: Name, dtype: object,
  225161,
  [0.17147872, 0.7390073557485426]],
 [8682    D. Rugani
  Name: Name, dtype: object,
  211320,
  [0.1753815, 0.736336071363106]],
 [6988    S. Memišević
  Name: Name, dtype: object,
  235544,
  [0.32399502, 0.6526402614682975]],
 [3901    E. Konsa
  Name: Name, dtype: object,
  227678,
  [0.14699265, 0.7494123937918196]],
 [14684    16 J. M'voto
  Name: Name, dtype: object,
  184268,
  [0.84341663, 0.35645524573675114]],
 [2215    Andrei Girotto
  Name: Name, dtype: object,
  226515,
  [0.15117098, 0.745620160391256]],
 [2460    L. Tousart
  Name: Name, dtype: object,
  227234,
  [0.15117098, 0.7449922068242019]],
 [11657    G. Maripán
  Name: Name, dtype: object,
  219145,
  [0.14566725, 0.7475690535790442]],
 [815    F. Schär
  Name: Name, dtype: object,
  210047,
  [0.16320278, 0.7375360495287626]],
 [5371    20 B. Sarr
  Name: Name, dtype: object,
  213537,
  [0.35173213, 0.6298701469127282]],
 [2921    E. Ndicka
  Name: Name, dtype: object,
  236403,
  [0.171362, 0.7312670838384834]],
 [9463    L. Moore
  Name: Name, dtype: object,
  200758,
  [0.35173213, 0.6296347140039189]],
 [9405    Davi Parrela
  Name: Name, dtype: object,
  230388,
  [0.18436961, 0.7227837112060469]],
 [12847    Tobias Figueiredo
  Name: Name, dtype: object,
  212231,
  [0.34771508, 0.6308727508482237]],
 [7507    Rafael Cachoira
  Name: Name, dtype: object,
  230528,
  [0.18302591, 0.723479318461672]],
 [4257    H. Choudhury
  Name: Name, dtype: object,
  228332,
  [0.18535833, 0.7221171309835535]],
 [13094    21 P. Gouano
  Name: Name, dtype: object,
  204886,
  [0.33589563, 0.6371300199742259]],
 [10629    21 F. Balbuena
  Name: Name, dtype: object,
  228229,
  [0.14566725, 0.7439988012055573]],
 [9722    C. Cuesta
  Name: Name, dtype: object,
  233841,
  [0.24949127, 0.6850471343428132]],
 [8092    21 J. Flanagan
  Name: Name, dtype: object,
  201999,
  [0.34905466, 0.628626678876489]],
 [2246    J. Gouweleeuw
  Name: Name, dtype: object,
  202201,
  [0.14566725, 0.7425503069369507]],
 [5986    C. Jullien
  Name: Name, dtype: object,
  208615,
  [0.18350878, 0.7206732185275985]],
 [8660    I. Diop
  Name: Name, dtype: object,
  231633,
  [0.14566725, 0.7411855368117544]],
 [11680    J. Bednarek
  Name: Name, dtype: object,
  220570,
  [0.1670937, 0.7287007620711174]],
 [7549    W. Zimmerman
  Name: Name, dtype: object,
  212591,
  [0.21813676, 0.6985905214795987]],
 [4855    P. Hatzidiakos
  Name: Name, dtype: object,
  229150,
  [0.34704405, 0.62503801992207]],
 [1357    L. Martínez Quarta
  Name: Name, dtype: object,
  228708,
  [0.14781767, 0.7370954623267022]],
 [10269    J. Lascelles
  Name: Name, dtype: object,
  203487,
  [0.14566725, 0.7380750356455021]],
 [7009    R. Koch
  Name: Name, dtype: object,
  236532,
  [0.16320278, 0.727407072080863]],
 [7781    O. Kabak
  Name: Name, dtype: object,
  239890,
  [0.18389569, 0.7155431902118043]],
 [4771    R. Yates
  Name: Name, dtype: object,
  235642,
  [0.36765486, 0.6121317597572089]],
 [12377    M. Andersen
  Name: Name, dtype: object,
  228419,
  [0.26847845, 0.6678098637601607]],
 [7930    A. Ahmedhodžić
  Name: Name, dtype: object,
  236524,
  [0.24949127, 0.6784890546712615]],
 [2052    D. Kohr
  Name: Name, dtype: object,
  212212,
  [0.18303487, 0.715585876216813]],
 [10760    Pablo Marí
  Name: Name, dtype: object,
  206654,
  [0.14566725, 0.7365107149163532]],
 [6868    A. Frías
  Name: Name, dtype: object,
  251886,
  [0.21598636, 0.6966085621445378]],
 [571    S. Sturaro
  Name: Name, dtype: object,
  202135,
  [0.14566725, 0.7358126190942287]],
 [8938    Ibañez
  Name: Name, dtype: object,
  247257,
  [0.17634429, 0.7185500018140938]],
 [11175    A. Al Amri
  Name: Name, dtype: object,
  241197,
  [0.31222323, 0.6418677727909556]],
 [7034    J. O'Connell
  Name: Name, dtype: object,
  212300,
  [0.15117098, 0.732298102137154]],
 [11142    R. Le Normand
  Name: Name, dtype: object,
  233486,
  [0.20708439, 0.700003467421279]],
 [6488    Marcão
  Name: Name, dtype: object,
  234426,
  [0.14566725, 0.7340926328589993]],
 [10888    16 Felipe Santana
  Name: Name, dtype: object,
  176957,
  [0.30449104, 0.644530068224724]],
 [4293    C. Goldson
  Name: Name, dtype: object,
  199580,
  [0.14566725, 0.7333878115679621]],
 [8754    Raillo
  Name: Name, dtype: object,
  228805,
  [0.18350878, 0.7118714459087838]],
 [7072    K. Rekik
  Name: Name, dtype: object,
  205193,
  [0.17362915, 0.7171635981180206]],
 [13224    19 C. Torres
  Name: Name, dtype: object,
  222647,
  [0.87218523, 0.32409788859780836]],
 [13066    N. Pérez
  Name: Name, dtype: object,
  244206,
  [0.182552, 0.7118712310000539]],
 [4942    J. Tanganga
  Name: Name, dtype: object,
  236600,
  [0.18753427, 0.7083715809927786]],
 [1052    19 D. Williams
  Name: Name, dtype: object,
  198194,
  [0.22684415, 0.6862196566548414]],
 [735    I. Sangaré
  Name: Name, dtype: object,
  235173,
  [0.14699265, 0.730303552690965]],
 [2239    D. Martínez
  Name: Name, dtype: object,
  241569,
  [0.17753114, 0.7126488287156946]],
 [2143    G. Trauner
  Name: Name, dtype: object,
  199813,
  [0.15332142, 0.7261064314653701]],
 [10734    R. Knoche
  Name: Name, dtype: object,
  203030,
  [0.14566725, 0.7302749786108256]],
 [7268    R. Khedira
  Name: Name, dtype: object,
  211999,
  [0.15117098, 0.7267859624235352]],
 [9347    A. Gogić
  Name: Name, dtype: object,
  216526,
  [0.36277032, 0.6076335856230304]],
 [6318    16 Breno
  Name: Name, dtype: object,
  180955,
  [0.27435, 0.6569011696015635]],
 [5902    S. Deli
  Name: Name, dtype: object,
  228236,
  [0.14566725, 0.7289041093773082]],
 [367    M. Halstenberg
  Name: Name, dtype: object,
  210665,
  [0.14566725, 0.7283930020028844]],
 [10521    E. Cabaco
  Name: Name, dtype: object,
  236331,
  [0.18303487, 0.7069922080960594]],
 [4065    Kelivelson
  Name: Name, dtype: object,
  230452,
  [0.21813676, 0.6871899901557031]],
 [9747    Fabiano Sonta
  Name: Name, dtype: object,
  230218,
  [0.21598636, 0.6883976177431487]],
 [2733    Rúben Vezo
  Name: Name, dtype: object,
  215399,
  [0.14566725, 0.7274959566666367]],
 [10809    M. Kumbulla
  Name: Name, dtype: object,
  245426,
  [0.182552, 0.7065637693542491]],
 [3595    B. Godfrey
  Name: Name, dtype: object,
  225793,
  [0.1524964, 0.7232879264088667]],
 [3424    Fali
  Name: Name, dtype: object,
  229628,
  [0.17071119, 0.7127791005981983]],
 [2581    16 Rodrigo Caio
  Name: Name, dtype: object,
  203324,
  [0.2764397, 0.653114019474205]],
 [8528    D. Henry
  Name: Name, dtype: object,
  201208,
  [0.3689944, 0.6008531043302753]],
 [6345    Bustinza
  Name: Name, dtype: object,
  224869,
  [0.15117098, 0.7233181955852892]],
 [4570    D. Hovorka
  Name: Name, dtype: object,
  240033,
  [0.18015549, 0.7066418204349912]],
 [8681    J. Rasmussen
  Name: Name, dtype: object,
  234827,
  [0.22149009, 0.6829791877367082]],
 [1283    K. Ayhan
  Name: Name, dtype: object,
  207790,
  [0.14566725, 0.725551467565143]],
 [2002    G. Dzhikiya
  Name: Name, dtype: object,
  229773,
  [0.14566725, 0.7254711424487963]],
 [2556    D. Amartey
  Name: Name, dtype: object,
  212883,
  [0.15117098, 0.7217400365159056]],
 [2024    C. Paterson
  Name: Name, dtype: object,
  210724,
  [0.34646878, 0.6114537247594922]],
 [11776    D. Popov
  Name: Name, dtype: object,
  245132,
  [0.23264225, 0.6752901385170537]],
 [4957    Mingueza
  Name: Name, dtype: object,
  259694,
  [0.18753427, 0.700344727162958]],
 [10129    P. Cissé
  Name: Name, dtype: object,
  228386,
  [0.17244774, 0.7083778433168233]],
 [6186    M. Nastasić
  Name: Name, dtype: object,
  205362,
  [0.17753114, 0.7054794535945303]],
 [7920    J. Okore
  Name: Name, dtype: object,
  204163,
  [0.37608588, 0.5933408748388795]],
 [4971    I. Šunjić
  Name: Name, dtype: object,
  244271,
  [0.24276684, 0.6682399560798717]],
 [5911    M. Niakhaté
  Name: Name, dtype: object,
  225859,
  [0.18303487, 0.7015961199758897]],
 [3571    O. Alderete
  Name: Name, dtype: object,
  240359,
  [0.1670937, 0.7105204231231791]],
 [7474    21 E. Mangala
  Name: Name, dtype: object,
  190531,
  [0.17595665, 0.7054909298153274]],
 [5591    Joaquín
  Name: Name, dtype: object,
  232132,
  [0.14566725, 0.7223052426467557]],
 [10752    S. Duffy
  Name: Name, dtype: object,
  192622,
  [0.24015716, 0.6690705559244343]],
 [11799    N. Maksimović
  Name: Name, dtype: object,
  215466,
  [0.14566725, 0.7214209701910141]],
 [5447    M. Kempf
  Name: Name, dtype: object,
  210719,
  [0.15117098, 0.7182654238719927]],
 [12441    K. Triantafyllopoulos
  Name: Name, dtype: object,
  209667,
  [0.36395285, 0.598373387510438]],
 [1712    L. Romo
  Name: Name, dtype: object,
  243015,
  [0.15117098, 0.7177957830627809]],
 [4481    E. Balanta
  Name: Name, dtype: object,
  213899,
  [0.17753114, 0.7024997266787302]],
 [5449    Saberto Botelho
  Name: Name, dtype: object,
  230531,
  [0.212183, 0.6828369277331174]],
 [2960    N. Stark
  Name: Name, dtype: object,
  212977,
  [0.15117098, 0.7167532775156116]],
 [6026    Sergi Gómez
  Name: Name, dtype: object,
  199577,
  [0.15117098, 0.7163661546826235]],
 [5762    N. Aguerd
  Name: Name, dtype: object,
  244749,
  [0.15117098, 0.7161817658491686]],
 [9030    B. White
  Name: Name, dtype: object,
  231936,
  [0.14699265, 0.7179479146627066]],
 [7280    21 Bastos
  Name: Name, dtype: object,
  216655,
  [0.15117098, 0.7155128788881091]],
 [9284    L. Cooper
  Name: Name, dtype: object,
  189456,
  [0.15117098, 0.7155036951571414]],
 [6513    M. Loum
  Name: Name, dtype: object,
  245021,
  [0.21813676, 0.6777902702752543]],
 [11608    A. Disasi
  Name: Name, dtype: object,
  229942,
  [0.14699265, 0.7177650264617892]],
 [7414    N. Milenković
  Name: Name, dtype: object,
  238095,
  [0.14699265, 0.7176384478095229]],
 [12254    Y. Osorio
  Name: Name, dtype: object,
  237297,
  [0.17147872, 0.7037549374017168]],
 [3735    M. Bešić
  Name: Name, dtype: object,
  200765,
  [0.22134042, 0.675586660235252]],
 [3731    T. Kehrer
  Name: Name, dtype: object,
  226229,
  [0.15117098, 0.7146157405959583]],
 [3003    Juli Piresinho
  Name: Name, dtype: object,
  230198,
  [0.18302591, 0.6964136178885139]],
 [7848    R. Krauße
  Name: Name, dtype: object,
  232406,
  [0.35126513, 0.6017579004791521]],
 [4074    Dória
  Name: Name, dtype: object,
  209329,
  [0.14614119, 0.7166886002078879]],
 [7800    16 Pedro Geromel
  Name: Name, dtype: object,
  170802,
  [0.17752433, 0.6989825770409033]],
 [9177    A. Szalai
  Name: Name, dtype: object,
  253170,
  [0.23689818, 0.6650131219945382]],
 [1423    D. Hancko
  Name: Name, dtype: object,
  247103,
  [0.18751183, 0.6927059685095378]],
 [11431    R. Porteous
  Name: Name, dtype: object,
  240439,
  [0.34309986, 0.6049871562708765]],
 [11161    R. van Drongelen
  Name: Name, dtype: object,
  233097,
  [0.3646395, 0.592838162158819]],
 [6662    J. Rodríguez
  Name: Name, dtype: object,
  244950,
  [0.22134042, 0.6730062990035149]],
 [1973    P. Schuurs
  Name: Name, dtype: object,
  241854,
  [0.23168702, 0.6669061066147426]],
 [8733    Juli Freitinho
  Name: Name, dtype: object,
  230224,
  [0.21691002, 0.674688337832308]],
 [6778    J. Egan
  Name: Name, dtype: object,
  204936,
  [0.15117098, 0.7114921002100921]],
 [4462    E. Brítez
  Name: Name, dtype: object,
  215010,
  [0.24037601, 0.6612637982761949]],
 [10985    O. Colley
  Name: Name, dtype: object,
  226536,
  [0.15102132, 0.7112307249653871]],
 [10084    M. Salisu
  Name: Name, dtype: object,
  244915,
  [0.19226699, 0.6880226917119671]],
 [11363    G. Corujo
  Name: Name, dtype: object,
  253289,
  [0.27248868, 0.6428131112166334]],
 [12310    Pedro Henrique
  Name: Name, dtype: object,
  219258,
  [0.14566725, 0.7136754115149999]],
 [10121    G. Ortíz
  Name: Name, dtype: object,
  215070,
  [0.2395632, 0.6606347132281641]],
 [6882    J. Bruma
  Name: Name, dtype: object,
  195363,
  [0.21894959, 0.6719719643274529]],
 [4924    C. Montes
  Name: Name, dtype: object,
  229980,
  [0.17753114, 0.6949902947407833]],
 [6136    F. Medina
  Name: Name, dtype: object,
  236804,
  [0.18753427, 0.6891772572309556]],
 [6093    P. Ciss
  Name: Name, dtype: object,
  250858,
  [0.30028564, 0.6252266300874895]],
 [10792    21 V. Cabrera
  Name: Name, dtype: object,
  221619,
  [0.37050197, 0.5856759057243481]],
 [11688    C. Salcedo
  Name: Name, dtype: object,
  212888,
  [0.23717237, 0.6606353581032726]],
 [8144    Edgar
  Name: Name, dtype: object,
  247500,
  [0.18303487, 0.6910715899081105]],
 [5381    20 Marc Muniesa
  Name: Name, dtype: object,
  192766,
  [0.21598636, 0.671758023492874]],
 [9229    A. Soumaoro
  Name: Name, dtype: object,
  200353,
  [0.17410307, 0.6948225298241525]],
 [4047    S. Denswil
  Name: Name, dtype: object,
  205756,
  [0.21813676, 0.6698907106759625]],
 [7246    A. Briançon
  Name: Name, dtype: object,
  223138,
  [0.22124968, 0.6676148840806141]],
 [9085    Fábio Cardoso
  Name: Name, dtype: object,
  213917,
  [0.15332142, 0.7055433111826274]],
 [3096    Calero
  Name: Name, dtype: object,
  240289,
  [0.14566725, 0.7098191484843153]],
 [13038    F. Sierralta
  Name: Name, dtype: object,
  228681,
  [0.33110178, 0.605365913962372]],
 [9142    A. Webster
  Name: Name, dtype: object,
  207616,
  [0.1753815, 0.6927982744315985]],
 [6620    M. Simakan
  Name: Name, dtype: object,
  243854,
  [0.17039678, 0.6953147362028704]],
 [3219    R. Rojas
  Name: Name, dtype: object,
  246914,
  [0.2645764, 0.6416872297896309]],
 [5448    W. Hoedt
  Name: Name, dtype: object,
  216774,
  [0.15117098, 0.7054571411350491]],
 [9466    Paulo Oliveira
  Name: Name, dtype: object,
  210679,
  [0.20083717, 0.6773233748971862]],
 [4535    M. de los Santos
  Name: Name, dtype: object,
  239645,
  [0.22028916, 0.6663698666379684]],
 [4177    21 W. Cartagena
  Name: Name, dtype: object,
  221664,
  [0.3432536, 0.5971797873918712]],
 [7314    21 U. Spajić
  Name: Name, dtype: object,
  215892,
  [0.17913286, 0.6893109740058135]],
 [4754    A. Tuanzebe
  Name: Name, dtype: object,
  231485,
  [0.17280412, 0.6923593974144892]],
 [2295    F. Guilbert
  Name: Name, dtype: object,
  227222,
  [0.14566725, 0.7076125759615585]],
 [13491    A. Mora
  Name: Name, dtype: object,
  242427,
  [0.3954097, 0.5665061133920386]],
 [6691    L. Abram
  Name: Name, dtype: object,
  234178,
  [0.15117098, 0.7038713393391893]],
 [3733    Cris Laranjeiros
  Name: Name, dtype: object,
  230295,
  [0.14781767, 0.7056860256791606]],
 [2990    San Emeterio
  Name: Name, dtype: object,
  223654,
  [0.17147872, 0.6923257700750896]],
 [1128    20 S. Wuytens
  Name: Name, dtype: object,
  188416,
  [0.22929628, 0.6596080163475658]],
 [5428    J. Todibo
  Name: Name, dtype: object,
  245388,
  [0.16552533, 0.6954760845261695]],
 [7681    A. Seck
  Name: Name, dtype: object,
  217620,
  [0.22579287, 0.6613524800342316]],
 [8630    21 F. Meza
  Name: Name, dtype: object,
  214136,
  [0.18972707, 0.6815618887533105]],
 [9985    19 S. Lowry
  Name: Name, dtype: object,
  183524,
  [0.353197, 0.5894618325680925]],
 [6618    19 K. Mbodji
  Name: Name, dtype: object,
  198584,
  [0.17410307, 0.6900994017176321]],
 [8395    P. Struijk
  Name: Name, dtype: object,
  239360,
  [0.182552, 0.6851883845664628]],
 [12814    21 E. Amor
  Name: Name, dtype: object,
  226170,
  [0.278083, 0.6312774213193835]],
 [2500    A. Scholz
  Name: Name, dtype: object,
  212253,
  [0.14566725, 0.7057322419398356]],
 [10040    21 L. Landre
  Name: Name, dtype: object,
  202002,
  [0.2236405, 0.6610669164162222]],
 [3382    A. Djiku
  Name: Name, dtype: object,
  212219,
  [0.14566725, 0.7047569658415668]],
 [2039    André Ramalho
  Name: Name, dtype: object,
  210007,
  [0.18478866, 0.6826464904540333]],
 [9845    J. Komar
  Name: Name, dtype: object,
  222428,
  [0.18303487, 0.6835006089547178]],
 [3816    J. Escobar
  Name: Name, dtype: object,
  247881,
  [0.19337907, 0.67753137060232]],
 [8637    Murilo
  Name: Name, dtype: object,
  240115,
  [0.15117098, 0.7011842267769404]],
 [9839    D. Burn
  Name: Name, dtype: object,
  198032,
  [0.15117098, 0.7007756132935046]],
 [9273    K. Günter
  Name: Name, dtype: object,
  204451,
  [0.20708439, 0.6693118357239922]],
 [8812    A. Esiti
  Name: Name, dtype: object,
  220921,
  [0.22124968, 0.6612470489907295]],
 [3641    M. Martínez
  Name: Name, dtype: object,
  226798,
  [0.2395632, 0.6509409042255495]],
 [10072    B. Kouyaté
  Name: Name, dtype: object,
  247019,
  [0.29328525, 0.6204857186826468]],
 [4196    M. Wöber
  Name: Name, dtype: object,
  231838,
  [0.18413584, 0.6813937636045831]],
 [12205    Rodrigo Becão
  Name: Name, dtype: object,
  238621,
  [0.15117098, 0.6998382067548274]],
 [8167    A. Briseño
  Name: Name, dtype: object,
  192114,

In [156]:
# player_list = []
# for index, row in def_df_22.iterrows():
#     player_list.append(row["ID"])

In [157]:
# len(player_list)

3214

In [158]:
# dict = {}
# for i in range(city_preds_def.shape[0]):
#     dict[str(player_list[i])] = city_preds_def[i]
# player_list.sort(key = lambda x: dict[str(x)],reverse = True)
# new_list = [[df_22_std[df_22_std["ID"] == j]["Name"], j, dict[str(j)]] for j in player_list[:] if ((float(df_22[df_22["ID"] == j]["Ovr_pot"]) > 80) and (float(df_22[df_22["ID"] == j]["Age"]) < 30))]

In [159]:
# new_list

[[2834    J. Timber
  Name: Name, dtype: object,
  251805,
  0.40406594],
 [5795    W. Fofana
  Name: Name, dtype: object,
  248695,
  0.13236202],
 [6698    M. Lacroix
  Name: Name, dtype: object,
  244067,
  0.13059796],
 [7781    O. Kabak
  Name: Name, dtype: object,
  239890,
  0.12352434],
 [6893    S. Botman
  Name: Name, dtype: object,
  251809,
  0.11968967],
 [5033    Eric García
  Name: Name, dtype: object,
  245037,
  0.11088783],
 [2921    E. Ndicka
  Name: Name, dtype: object,
  236403,
  0.108773224],
 [8669    Gonçalo Inácio
  Name: Name, dtype: object,
  257179,
  0.08984569],
 [1349    J. Gvardiol
  Name: Name, dtype: object,
  251517,
  0.06378641],
 [1210    M. de Ligt
  Name: Name, dtype: object,
  235243,
  0.037637062],
 [8938    Ibañez
  Name: Name, dtype: object,
  247257,
  -0.03089336],
 [4872    A. Bastoni
  Name: Name, dtype: object,
  237383,
  -0.06451411],
 [7796    R. Araujo
  Name: Name, dtype: object,
  253163,
  -0.06571251],
 [2197    E. Tapsoba
  Name: Name, dtype: object,
  247263,
  -0.06940699],
 [2198    J. Koundé
  Name: Name, dtype: object,
  241486,
  -0.07241833],
 [7822    I. Konaté
  Name: Name, dtype: object,
  237678,
  -0.07258034],
 [9941    D. Zagadou
  Name: Name, dtype: object,
  238476,
  -0.10468852],
 [3667    D. Upamecano
  Name: Name, dtype: object,
  229558,
  -0.13822684],
 [11142    R. Le Normand
  Name: Name, dtype: object,
  233486,
  -0.17297281],
 [611    D. Zakaria
  Name: Name, dtype: object,
  229261,
  -0.1847592],
 [11727    Unai Núñez
  Name: Name, dtype: object,
  240900,
  -0.20260642],
 [8749    W. Orban
  Name: Name, dtype: object,
  204638,
  -0.21643934],
 [4373    N. Elvedi
  Name: Name, dtype: object,
  221491,
  -0.21814257],
 [5420    F. Tomori
  Name: Name, dtype: object,
  232756,
  -0.22054712],
 [9030    B. White
  Name: Name, dtype: object,
  231936,
  -0.22391881],
 [735    I. Sangaré
  Name: Name, dtype: object,
  235173,
  -0.22942227],
 [13    D. Alaba
  Name: Name, dtype: object,
  197445,
  -0.23414524],
 [1346    A. Mandi
  Name: Name, dtype: object,
  201143,
  -0.23534857],
 [5677    M. Senesi
  Name: Name, dtype: object,
  236506,
  -0.23792113],
 [270    R. Tapia
  Name: Name, dtype: object,
  220673,
  -0.23825096],
 [7019    A. Christensen
  Name: Name, dtype: object,
  213661,
  -0.23847419],
 [2546    C. Lenglet
  Name: Name, dtype: object,
  220440,
  -0.23955452],
 [3901    E. Konsa
  Name: Name, dtype: object,
  227678,
  -0.2400866],
 [6755    D. Ćaleta-Car
  Name: Name, dtype: object,
  225263,
  -0.24167556],
 [1453    J. Stones
  Name: Name, dtype: object,
  203574,
  -0.24215926],
 [3981    M. Keane
  Name: Name, dtype: object,
  207599,
  -0.24232139],
 [7009    R. Koch
  Name: Name, dtype: object,
  236532,
  -0.24257912],
 [1756    M. Akanji
  Name: Name, dtype: object,
  229237,
  -0.2432823],
 [1419    M. Ginter
  Name: Name, dtype: object,
  207862,
  -0.24552296],
 [3239    S. de Vrij
  Name: Name, dtype: object,
  198176,
  -0.24726644],
 [2403    J. Denayer
  Name: Name, dtype: object,
  220182,
  -0.24831209],
 [1897    R. Varane
  Name: Name, dtype: object,
  201535,
  -0.24913208],
 [3595    B. Godfrey
  Name: Name, dtype: object,
  225793,
  -0.28076136],
 [972    N. Mukiele
  Name: Name, dtype: object,
  226166,
  -0.29368138],
 [8698    N. Süle
  Name: Name, dtype: object,
  212190,
  -0.294762],
 [7172    Luiz Felipe
  Name: Name, dtype: object,
  236355,
  -0.29883146],
 [7614    Gabriel
  Name: Name, dtype: object,
  232580,
  -0.30067617],
 [3797    C. Romero
  Name: Name, dtype: object,
  232488,
  -0.301385],
 [755    Éder Militão
  Name: Name, dtype: object,
  240130,
  -0.3037327],
 [4059    C. Mbemba
  Name: Name, dtype: object,
  210897,
  -0.32620153],
 [6019    Lucas Veríssimo
  Name: Name, dtype: object,
  235688,
  -0.33227044],
 [1199    A. Laporte
  Name: Name, dtype: object,
  212218,
  -0.33612755],
 [4639    J. Gomez
  Name: Name, dtype: object,
  225100,
  -0.33727863],
 [578    R. Bensebaini
  Name: Name, dtype: object,
  224196,
  -0.34174204],
 [371    Marquinhos
  Name: Name, dtype: object,
  207865,
  -0.34254766],
 [241    V. van Dijk
  Name: Name, dtype: object,
  203376,
  -0.34386024],
 [3819    C. Söyüncü
  Name: Name, dtype: object,
  232119,
  -0.3439151],
 [2357    K. Zouma
  Name: Name, dtype: object,
  204311,
  -0.34495854],
 [2332    Yeray
  Name: Name, dtype: object,
  227950,
  -0.34511364],
 [5053    J. Giménez
  Name: Name, dtype: object,
  216460,
  -0.34535018],
 [4089    M. Škriniar
  Name: Name, dtype: object,
  232363,
  -0.34635967],
 [853    Mario Hermoso
  Name: Name, dtype: object,
  229668,
  -0.34642363],
 [899    Juiano Mestres
  Name: Name, dtype: object,
  230225,
  -0.34777966],
 [5975    A. Romagnoli
  Name: Name, dtype: object,
  210413,
  -0.3485529],
 [1591    H. Maguire
  Name: Name, dtype: object,
  203263,
  -0.34907898],
 [617    Palhinha
  Name: Name, dtype: object,
  229391,
  -0.34918967],
 [3091    J. Matip
  Name: Name, dtype: object,
  197061,
  -0.3495148],
 [1574    P. Kimpembe
  Name: Name, dtype: object,
  225850,
  -0.35089332],
 [2754    Rúben Dias
  Name: Name, dtype: object,
  239818,
  -0.35089332],
 [3121    J. Tarkowski
  Name: Name, dtype: object,
  202695,
  -0.3519778],
 [49    T. Delaney
  Name: Name, dtype: object,
  193283,
  -0.35615227],
 [218    W. Ndidi
  Name: Name, dtype: object,
  226790,
  -0.35708043],
 [1905    Diego Carlos
  Name: Name, dtype: object,
  219693,
  -0.35867715],
 [852    L. Hernández
  Name: Name, dtype: object,
  220814,
  -0.360175],
 [2451    A. Rüdiger
  Name: Name, dtype: object,
  205452,
  -0.36070773],
 [3911    D. Djené
  Name: Name, dtype: object,
  217940,
  -0.36285162],
 [7167    G. Mancini
  Name: Name, dtype: object,
  229582,
  -0.3636882],
 [2783    Josué Chiamulera
  Name: Name, dtype: object,
  230375,
  -0.3648822]]

In [151]:
df_22[df_22["ID"]==  245703]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Weak Foot,Skill Moves,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Ovr_pot,Preferred Foot_Left,Preferred Foot_Right,Bmi
96711,245703,I. Diveev,21,Russia,73,82,PFC CSKA Moscow,6.5,3.0,2.0,...,14.0,14.0,9.0,11.0,6.0,CB,77.5,0,1,22.819405

In [161]:
# utd_preds_def = np.load("./preds/pred_utd.npy")

In [162]:
# player_list = []
# for index, row in def_df_22.iterrows():
#     player_list.append(row["ID"])

In [163]:
# dict = {}
# for i in range(utd_preds_def.shape[0]):
#     dict[str(player_list[i])] = utd_preds_def[i]
# player_list.sort(key = lambda x: dict[str(x)],reverse = True)
# new_list = [[df_22_std[df_22_std["ID"] == j]["Name"], j, dict[str(j)]] for j in player_list[:] if ((float(df_22[df_22["ID"] == j]["Ovr_pot"]) > 80) and (float(df_22[df_22["ID"] == j]["Age"]) < 30))]

In [164]:
# new_list

[[2834    J. Timber
  Name: Name, dtype: object,
  251805,
  0.24162556],
 [5795    W. Fofana
  Name: Name, dtype: object,
  248695,
  0.22762406],
 [5033    Eric García
  Name: Name, dtype: object,
  245037,
  0.21594946],
 [8669    Gonçalo Inácio
  Name: Name, dtype: object,
  257179,
  0.21016243],
 [1349    J. Gvardiol
  Name: Name, dtype: object,
  251517,
  0.17622307],
 [6698    M. Lacroix
  Name: Name, dtype: object,
  244067,
  0.14767924],
 [7781    O. Kabak
  Name: Name, dtype: object,
  239890,
  0.14372748],
 [6893    S. Botman
  Name: Name, dtype: object,
  251809,
  0.1411571],
 [2921    E. Ndicka
  Name: Name, dtype: object,
  236403,
  0.123754345],
 [1210    M. de Ligt
  Name: Name, dtype: object,
  235243,
  0.094780535],
 [8938    Ibañez
  Name: Name, dtype: object,
  247257,
  0.02757963],
 [2197    E. Tapsoba
  Name: Name, dtype: object,
  247263,
  -0.06437465],
 [4872    A. Bastoni
  Name: Name, dtype: object,
  237383,
  -0.0661514],
 [7796    R. Araujo
  Name: Name, dtype: object,
  253163,
  -0.067169674],
 [2198    J. Koundé
  Name: Name, dtype: object,
  241486,
  -0.07066804],
 [7822    I. Konaté
  Name: Name, dtype: object,
  237678,
  -0.07356782],
 [3667    D. Upamecano
  Name: Name, dtype: object,
  229558,
  -0.11792977],
 [9941    D. Zagadou
  Name: Name, dtype: object,
  238476,
  -0.12182515],
 [11142    R. Le Normand
  Name: Name, dtype: object,
  233486,
  -0.1336385],
 [11727    Unai Núñez
  Name: Name, dtype: object,
  240900,
  -0.18423387],
 [7172    Luiz Felipe
  Name: Name, dtype: object,
  236355,
  -0.19130899],
 [4373    N. Elvedi
  Name: Name, dtype: object,
  221491,
  -0.20599082],
 [5420    F. Tomori
  Name: Name, dtype: object,
  232756,
  -0.20629705],
 [9030    B. White
  Name: Name, dtype: object,
  231936,
  -0.20707078],
 [735    I. Sangaré
  Name: Name, dtype: object,
  235173,
  -0.21278362],
 [3901    E. Konsa
  Name: Name, dtype: object,
  227678,
  -0.21387604],
 [7019    A. Christensen
  Name: Name, dtype: object,
  213661,
  -0.21537033],
 [7009    R. Koch
  Name: Name, dtype: object,
  236532,
  -0.21577083],
 [270    R. Tapia
  Name: Name, dtype: object,
  220673,
  -0.22142303],
 [5677    M. Senesi
  Name: Name, dtype: object,
  236506,
  -0.2222465],
 [6755    D. Ćaleta-Car
  Name: Name, dtype: object,
  225263,
  -0.22418281],
 [1756    M. Akanji
  Name: Name, dtype: object,
  229237,
  -0.2290572],
 [755    Éder Militão
  Name: Name, dtype: object,
  240130,
  -0.23067477],
 [2546    C. Lenglet
  Name: Name, dtype: object,
  220440,
  -0.23528442],
 [3981    M. Keane
  Name: Name, dtype: object,
  207599,
  -0.23763005],
 [7614    Gabriel
  Name: Name, dtype: object,
  232580,
  -0.23853621],
 [3239    S. de Vrij
  Name: Name, dtype: object,
  198176,
  -0.24158387],
 [3595    B. Godfrey
  Name: Name, dtype: object,
  225793,
  -0.2417983],
 [1419    M. Ginter
  Name: Name, dtype: object,
  207862,
  -0.24228115],
 [2403    J. Denayer
  Name: Name, dtype: object,
  220182,
  -0.24393044],
 [972    N. Mukiele
  Name: Name, dtype: object,
  226166,
  -0.2508891],
 [8749    W. Orban
  Name: Name, dtype: object,
  204638,
  -0.25169507],
 [6019    Lucas Veríssimo
  Name: Name, dtype: object,
  235688,
  -0.25487882],
 [3797    C. Romero
  Name: Name, dtype: object,
  232488,
  -0.2558372],
 [1346    A. Mandi
  Name: Name, dtype: object,
  201143,
  -0.2572439],
 [13    D. Alaba
  Name: Name, dtype: object,
  197445,
  -0.26044074],
 [1453    J. Stones
  Name: Name, dtype: object,
  203574,
  -0.2640547],
 [4639    J. Gomez
  Name: Name, dtype: object,
  225100,
  -0.26441622],
 [4059    C. Mbemba
  Name: Name, dtype: object,
  210897,
  -0.26500833],
 [1897    R. Varane
  Name: Name, dtype: object,
  201535,
  -0.26691154],
 [852    L. Hernández
  Name: Name, dtype: object,
  220814,
  -0.27536136],
 [899    Juiano Mestres
  Name: Name, dtype: object,
  230225,
  -0.27611136],
 [1199    A. Laporte
  Name: Name, dtype: object,
  212218,
  -0.2761238],
 [3819    C. Söyüncü
  Name: Name, dtype: object,
  232119,
  -0.27989513],
 [617    Palhinha
  Name: Name, dtype: object,
  229391,
  -0.28186992],
 [611    D. Zakaria
  Name: Name, dtype: object,
  229261,
  -0.28472096],
 [5975    A. Romagnoli
  Name: Name, dtype: object,
  210413,
  -0.2848123],
 [578    R. Bensebaini
  Name: Name, dtype: object,
  224196,
  -0.28529635],
 [3091    J. Matip
  Name: Name, dtype: object,
  197061,
  -0.28634423],
 [2783    Josué Chiamulera
  Name: Name, dtype: object,
  230375,
  -0.28890976],
 [1574    P. Kimpembe
  Name: Name, dtype: object,
  225850,
  -0.2893647],
 [7167    G. Mancini
  Name: Name, dtype: object,
  229582,
  -0.2893647],
 [2357    K. Zouma
  Name: Name, dtype: object,
  204311,
  -0.29024234],
 [853    Mario Hermoso
  Name: Name, dtype: object,
  229668,
  -0.29096916],
 [2332    Yeray
  Name: Name, dtype: object,
  227950,
  -0.2912838],
 [49    T. Delaney
  Name: Name, dtype: object,
  193283,
  -0.2937782],
 [3911    D. Djené
  Name: Name, dtype: object,
  217940,
  -0.29379854],
 [2451    A. Rüdiger
  Name: Name, dtype: object,
  205452,
  -0.2949342],
 [4089    M. Škriniar
  Name: Name, dtype: object,
  232363,
  -0.29506508],
 [218    W. Ndidi
  Name: Name, dtype: object,
  226790,
  -0.2952691],
 [5053    J. Giménez
  Name: Name, dtype: object,
  216460,
  -0.2955917],
 [3121    J. Tarkowski
  Name: Name, dtype: object,
  202695,
  -0.29610193],
 [8698    N. Süle
  Name: Name, dtype: object,
  212190,
  -0.29659435],
 [1905    Diego Carlos
  Name: Name, dtype: object,
  219693,
  -0.30291277],
 [371    Marquinhos
  Name: Name, dtype: object,
  207865,
  -0.32903597],
 [2754    Rúben Dias
  Name: Name, dtype: object,
  239818,
  -0.33745667],
 [241    V. van Dijk
  Name: Name, dtype: object,
  203376,
  -0.3478955],
 [1591    H. Maguire
  Name: Name, dtype: object,
  203263,
  -0.3478955]]